(** * Control/Geometric.v
    Geometric control theory on smooth manifolds.

    The basic objects: a control-affine system on a smooth manifold M is
        ẋ = f₀(x) + Σᵢ uᵢ fᵢ(x),    u ∈ U ⊆ ℝᵐ
    with f₀ a "drift" vector field and f₁,…,fₘ "control" vector fields.

    Key questions formalized here:
      - Which states are reachable from a given starting point?
      - When does the Lie algebra rank condition (LARC) hold?
      - When is the system controllable (Chow–Rashevskii)?
      - What is the structure of the optimal-control problem (Pontryagin)?

    References:
      Agrachev–Sachkov, *Control Theory from the Geometric Viewpoint*,
        chapters 2 (vector fields, brackets), 3 (orbits), 4–5 (controllability),
        12–13 (optimal control / Pontryagin).
      Bullo–Lewis, *Geometric Control of Mechanical Systems*, chapters 6–7.
      Sontag, *Mathematical Control Theory* (reference).
*)

From Stdlib Require Import List Arith Reals.
From CAG Require Import DiffGeom.SmoothManifold.

Local Open Scope R_scope.

(* ================================================================== *)
(** * 1. Control-affine systems                                         *)
(* ================================================================== *)

(** A control-affine system: a drift vector field plus a finite list of
    control vector fields. *)
Record ControlSystem (M : SmoothManifold) : Type := mkCS {
  cs_drift : VectorField M;
  cs_controls : list (VectorField M);
}.

Arguments cs_drift {M} _.
Arguments cs_controls {M} _.

(** A system is *driftless* if its drift vanishes identically. *)
Definition is_driftless {M : SmoothManifold} (S : ControlSystem M) : Prop :=
  cs_drift S = zero_vf M.

(** Number of control inputs. *)
Definition cs_num_controls {M : SmoothManifold} (S : ControlSystem M) : nat :=
  length (cs_controls S).

(* ================================================================== *)
(** * 2. The Lie algebra generated by a control system                  *)
(* ================================================================== *)

(** The Lie algebra rank condition (LARC) at a point p ∈ M is the
    statement that the Lie algebra generated (under bracketing) by the
    drift and control vector fields spans T_p M. We formalize this as
    the existence of a finite list of iterated brackets whose values at
    p span [TangentSpace M p].

    Axiomatized here as a predicate; concrete combinations have to be
    verified case-by-case in any actual application. *)
(* CAG zero-dependent Parameter LieAlgRankCondition theories/Control/Geometric.v:61 BEGIN
Parameter LieAlgRankCondition :
  forall {M : SmoothManifold} (S : ControlSystem M) (p : sm_carrier M), Prop.
   CAG zero-dependent Parameter LieAlgRankCondition theories/Control/Geometric.v:61 END *)

(** Bracket-generating distribution: the smallest involutive distribution
    containing the control vector fields. *)
(* CAG zero-dependent Parameter bracket_generating_distribution theories/Control/Geometric.v:66 BEGIN
Parameter bracket_generating_distribution :
  forall {M : SmoothManifold} (S : ControlSystem M), Distribution M.
   CAG zero-dependent Parameter bracket_generating_distribution theories/Control/Geometric.v:66 END *)

(* ================================================================== *)
(** * 3. Reachable sets and orbits                                      *)
(* ================================================================== *)

(** The set of states reachable from [p] in arbitrary nonnegative time
    using piecewise-constant controls in U. Axiomatized; concrete
    descriptions depend on the control set. *)
(* CAG zero-dependent Parameter reachable_set theories/Control/Geometric.v:80 BEGIN
Parameter reachable_set :
  forall {M : SmoothManifold}
         (S : ControlSystem M)
         (U : list R -> Prop)        (* admissible control values *)
         (p : sm_carrier M),
    sm_carrier M -> Prop.
   CAG zero-dependent Parameter reachable_set theories/Control/Geometric.v:80 END *)

(** A control system is *(globally) controllable* if every point can
    reach every other point. *)
(* CAG zero-dependent Definition is_globally_controllable theories/Control/Geometric.v:89 BEGIN
Definition is_globally_controllable
    {M : SmoothManifold} (S : ControlSystem M) (U : list R -> Prop) : Prop :=
  forall p q : sm_carrier M, reachable_set S U p q.
   CAG zero-dependent Definition is_globally_controllable theories/Control/Geometric.v:89 END *)

(** A system is *small-time locally controllable at p* if [p] is in
    the interior of its reachable set in arbitrarily small time. *)
(* CAG zero-dependent Parameter is_STLC theories/Control/Geometric.v:95 BEGIN
Parameter is_STLC :
  forall {M : SmoothManifold}
         (S : ControlSystem M) (U : list R -> Prop) (p : sm_carrier M), Prop.
   CAG zero-dependent Parameter is_STLC theories/Control/Geometric.v:95 END *)

(* ================================================================== *)
(** * 4. Chow–Rashevskii theorem                                        *)
(* ================================================================== *)

(** Chow–Rashevskii: for a *driftless* control-affine system on a
    connected manifold, the LARC at every point implies global
    controllability with unrestricted controls.

    Stated as Axiom — a 50+ page proof in Agrachev–Sachkov. *)
(* CAG zero-dependent Conjecture chow_rashevskii theories/Control/Geometric.v:104 BEGIN
Conjecture chow_rashevskii :
  forall {M : SmoothManifold}
         (S : ControlSystem M),
    is_driftless S ->
    (forall p : sm_carrier M, LieAlgRankCondition S p) ->
    is_globally_controllable S (fun _ => True).
   CAG zero-dependent Conjecture chow_rashevskii theories/Control/Geometric.v:104 END *)

(** Sussmann's small-time local controllability sufficient condition:
    if the LARC holds at [p] and certain bracket symmetry conditions are
    satisfied, then the system is STLC at [p]. Stated as Axiom. *)
(* CAG zero-dependent Parameter sussmann_brackets_balanced theories/Control/Geometric.v:118 BEGIN
Parameter sussmann_brackets_balanced :
  forall {M : SmoothManifold} (S : ControlSystem M) (p : sm_carrier M), Prop.
   CAG zero-dependent Parameter sussmann_brackets_balanced theories/Control/Geometric.v:118 END *)

(* CAG zero-dependent Conjecture sussmann_stlc theories/Control/Geometric.v:117 BEGIN
Conjecture sussmann_stlc :
  forall {M : SmoothManifold}
         (S : ControlSystem M) (U : list R -> Prop) (p : sm_carrier M),
    LieAlgRankCondition S p ->
    sussmann_brackets_balanced S p ->
    is_STLC S U p.
   CAG zero-dependent Conjecture sussmann_stlc theories/Control/Geometric.v:117 END *)

(* ================================================================== *)
(** * 5. Open problems                                                  *)
(* ================================================================== *)

(** Following Coron's "Control and nonlinearity" survey, several
    well-known open problems in geometric control: *)

(** ** Open question (small-time local controllability for affine systems).

    Sussmann's sufficient condition for STLC is far from necessary. Coron
    has asked: is there a clean *necessary and sufficient* condition for
    STLC of a control-affine system at an equilibrium of the drift?
    Status: open in general; resolved only for restricted classes. *)
(* CAG zero-dependent Definition open_question_STLC_characterization theories/Control/Geometric.v:147 BEGIN
Definition open_question_STLC_characterization : Prop :=
  exists (P : forall {M : SmoothManifold} (S : ControlSystem M)
              (U : list R -> Prop) (p : sm_carrier M), Prop),
    forall {M : SmoothManifold} (S : ControlSystem M)
           (U : list R -> Prop) (p : sm_carrier M),
      vf_fn (cs_drift S) p = ts_zero ->
      P S U p <-> is_STLC S U p.
   CAG zero-dependent Definition open_question_STLC_characterization theories/Control/Geometric.v:147 END *)

(** ** Open question (sub-Riemannian geodesics: smoothness).

    For sub-Riemannian metrics, are length-minimizing geodesics always
    C^∞? In Riemannian geometry yes; in sub-Riemannian the question is
    open in general because of "abnormal" minimizers. The Sard-type
    conjecture for end-point maps is the canonical formulation. *)
Definition open_question_sR_geodesic_smoothness : Prop :=
  forall {M : SmoothManifold} (S : ControlSystem M),
    is_driftless S ->
    (* every length-minimizer is C^∞; placeholder predicate for now *)
    True.

(** ** Open question (controllability of incompressible Euler from boundary).

    Coron's specific open question: is the 3D incompressible Euler
    equation controllable from the boundary in arbitrarily small time?
    Status: 2D resolved (Coron); 3D open. Stated here only as a marker
    — needs PDE infrastructure to formalize properly. *)
Definition open_question_3d_euler_boundary_controllability : Prop :=
  True.  (* placeholder; needs PDE infrastructure *)

(* ================================================================== *)
(** * 6. Notes / status                                                 *)
(* ================================================================== *)

(** This file is a SCAFFOLD. To do anything substantial:

    [G1] Need a concrete model of [Rn] and its [TangentSpace] in terms
         of standard real-vector-space operations from [Reals_extra].
         Then the [TangentSpace], [VectorField], etc. parameters can be
         specialized.

    [G2] Need a calculus chain: differentiation, integration, ODE
         existence/uniqueness. The project has [ConstructiveCauchyReals]
         + [Reals] from Stdlib, but no automatic-differentiation or ODE
         infrastructure.

    [G3] [LieAlgRankCondition] and [bracket_generating_distribution]
         are Parameters; they would be inductive definitions over
         finite Lie polynomials in the control vector fields.

    [G4] [reachable_set] needs a notion of "trajectory" (a piecewise-smooth
         curve solving the controlled ODE), which depends on [G2].

    [G5] Stating the Pontryagin maximum principle requires a cotangent
         bundle and Hamiltonian flow on T*M. Not in this file.

    Realistic next step: complete [G1] (concrete model of Rⁿ + T_pℝⁿ ≅ ℝⁿ)
    and prove a single concrete Chow-style theorem on a small example,
    e.g. controllability of the Heisenberg distribution. *)
