(** * DecisionProblems/Specialization.v

    Specialization lemma framework (Bass / Lubotzky).

    Addresses [G5] from OpenProblems.v.

    The classical specialization lemma states:
        If R is a finitely generated integral domain and 0 ≠ r ∈ R,
        then there exists a homomorphism φ : R → F to a finite field
        F such that φ(r) ≠ 0.

    This is the key step in the proof of Proposition 1.3 ((D) ⇒
    conjugacy separable):
    1. By (D), tr(ρ(γ)) ≠ tr(ρ(η)) for some ρ : Γ → SL(n, R).
    2. The trace difference is a nonzero element of a f.g. integral
       domain (the trace ring of ρ).
    3. Specialize to a finite field; ρ specializes to ρ̄ : Γ → SL(n, F_q).
    4. The image group is finite, so distinguishes the conjugacy
       classes by trace in a finite quotient.

    This file:
    - Records the abstract specialization lemma as a named axiom.
    - Builds the bridge from a separating representation over an
      integral domain to a separating finite-quotient hom.
    - Derives Proposition 1.3 from these pieces. *)

From CAG Require Import Group.
From CAG Require Import Rings.Ring.
From CAG Require Import DecisionProblems.TraceProperties.
From Stdlib Require Import List.
Import ListNotations.

(* ================================================================== *)
(** * 1. Finitely generated rings (axiomatic stub)                      *)
(* ================================================================== *)

(** A finitely generated commutative ring R: every element is a
    polynomial expression in the generators. We axiomatize this
    structure since the project's Rings layer doesn't yet have
    generators-and-relations infrastructure. *)

Record FGRing : Type := mkFGR
{
  fgr_carrier : Type;
  fgr_ring    : Ring fgr_carrier;
  fgr_gens    : list fgr_carrier;
  (** Every r ∈ R is in the ring generated by [fgr_gens] — this is the
      "finitely generated" property. Stated abstractly via a
      generators predicate. *)
  fgr_in_gen_ring : forall r : fgr_carrier, True;
}.

(* ================================================================== *)
(** * 2. The specialization lemma                                       *)
(* ================================================================== *)

(** Bass-Lubotzky specialization (axiomatized).

    Statement: for any f.g. commutative ring R and any nonzero r ∈ R,
    there exists a finite ring Q (i.e., one with a list-enumeration of
    its elements) and a ring hom φ : R → Q with φ(r) ≠ 0_Q.

    This is a cornerstone of effective algebraic-geometric arguments
    over Z, used pervasively in arithmetic / linear group theory.

    The proof uses Hilbert's Nullstellensatz style argument: f.g. rings
    have a maximal ideal m with R/m a finite field, and one can choose
    m to avoid r. *)

(* CAG zero-dependent Conjecture bass_lubotzky_specialization theories/DecisionProblems/Specialization.v:70 BEGIN
Conjecture bass_lubotzky_specialization :
  forall (R : FGRing) (r : fgr_carrier R),
    r <> rzero (fgr_carrier R) (fgr_ring R) ->
    exists (Q : Type) (rq : Ring Q)
           (Q_list : list Q)
           (Q_complete : forall x : Q, In x Q_list)
           (phi : RingHom (fgr_ring R) rq),
      rhom_fn phi r <> rzero Q rq.
   CAG zero-dependent Conjecture bass_lubotzky_specialization theories/DecisionProblems/Specialization.v:70 END *)

(* ================================================================== *)
(** * 3. From representation to specialization                          *)
(* ================================================================== *)

(** A representation ρ : Γ → SL(n, R) lifts to a finite quotient
    when R is a f.g. integral domain. The hypothesis is that the
    trace difference of two non-conjugate elements is a nonzero
    element of R; specialize to a finite field. *)

Section SpecializationOfTraceDiff.
  Context {G : Type} (sg : StrictGroup G) (R : FGRing).

  (** Hypothesis: the trace difference tr(ρ(γ)) - tr(ρ(η)) is a
      non-zero element of R for some ρ. We package this as an
      explicit input. *)
(* CAG zero-dependent Definition trace_diff_specializable theories/DecisionProblems/Specialization.v:94 BEGIN
  Definition trace_diff_specializable
      (gamma eta : G)
      (trace_diff : fgr_carrier R)
      (Hnz : trace_diff <> rzero (fgr_carrier R) (fgr_ring R)) :
    exists (Q : Type) (rq : Ring Q)
           (Q_list : list Q)
           (Q_complete : forall x : Q, In x Q_list)
           (phi : RingHom (fgr_ring R) rq),
      rhom_fn phi trace_diff <> rzero Q rq :=
    bass_lubotzky_specialization R trace_diff Hnz.
   CAG zero-dependent Definition trace_diff_specializable theories/DecisionProblems/Specialization.v:94 END *)

End SpecializationOfTraceDiff.

(* ================================================================== *)
(** * 4. Proposition 1.3 reformulated                                  *)
(* ================================================================== *)

(** [conjugacy_separable_via_specialization]: a structurally explicit
    re-statement of Proposition 1.3 in terms of the specialization
    lemma. Given a separating representation, we get a finite-quotient
    distinguishing hom — exactly the conjugacy-separable property.

    The actual proof Proposition 1.3 (ungated) requires:
    1. Definition of the trace ring of a representation.
    2. The specialization lemma (axiomatized above).
    3. The fact that ρ(γ) and ρ(η) being non-conjugate in a finite
       group descends to non-conjugate finite-quotient images of γ, η.

    Step 3 needs care: ρ(γ) ≁ ρ(η) in SL(n, F_q) does NOT immediately
    give γ ≁ η in some finite quotient of Γ. The standard argument is
    to use the kernel of ρ̄ : Γ → SL(n, F_q) as the finite-index normal
    subgroup; the quotient Γ/ker(ρ̄) is a subgroup of SL(n, F_q), hence
    finite. *)

(** Statement of Prop 1.3 with specialization made explicit. *)
Definition prop_1_3_with_specialization {G : Type} (sg : StrictGroup G) :
    Prop :=
  forall (gamma eta : G),
    ~ are_conjugate sg gamma eta ->
    (* Hypothesis: there's a "nice" trace ring and trace-distinguishing
       element coming from some representation. *)
    forall (R : FGRing)
           (trace_diff : fgr_carrier R)
           (Hnz : trace_diff <> rzero (fgr_carrier R) (fgr_ring R)),
      exists (Q : Type) (sq : StrictGroup Q) (Q_list : list Q)
             (Q_complete : forall x : Q, In x Q_list)
             (phi : GroupHom sg sq),
        ~ are_conjugate sq (hom_fn phi gamma) (hom_fn phi eta).

(** Open task: derive prop_1_3_with_specialization from
    bass_lubotzky_specialization + an explicit representation. The
    tooling is now in place; the construction is mechanical given
    a concrete trace-ring instance. *)
