(** Vanishing/LefschetzHyperplane.v — Lefschetz hyperplane theorem

    Theorem (Lefschetz hyperplane theorem):
      Let M be a compact projective manifold of complex dimension n,
      and let V = M ∩ H be a smooth hyperplane section.  Then the
      restriction map on homology
          H_q(V, Z) -> H_q(M, Z)
      is an isomorphism for q < n-1 and surjective for q = n-1.

      Equivalently on cohomology:
          H^q(M, Z) -> H^q(V, Z)
      is an isomorphism for q < n-1 and injective for q = n-1.

    Standard proof: Morse theory on the complement M \ V shows
    M has the homotopy type of V with cells of dimension ≥ n attached.
    The analytic proof via the Lefschetz pencil is also classical.

    Corollaries for smooth projective hypersurfaces V ⊂ P^n:
    - H^{2k-1}(V) = 0 for k ≠ n/2  (odd cohomology except middle)
    - H^{2k}(V) generated by k-plane section class for k < n/2
    - If dim V ≥ 2 then π_1(V) = 0 (simply connected)

    References: ag.org §Lefschetz theorem on hyperplane sections *)

From Stdlib Require Import List Arith Lia.
From CAG Require Import Complex.
From CAG Require Import ManifoldTopology.
From CAG Require Import Kahler.Lefschetz.Operators.
From CAG Require Import LieAlgebra.

Local Open Scope nat_scope.

(* ================================================================== *)
(** * 1. Smooth hyperplane sections                                    *)
(* ================================================================== *)

(** A smooth hyperplane section V of M: a smooth hypersurface cut out
    by a linear form (i.e. an element of O(1) on projective M). *)
Parameter smooth_hyperplane_section : forall (M : KahlerManifold), Type.

(** The ambient manifold inclusion: V ↪ M. *)
Parameter shs_ambient : forall (M : KahlerManifold),
    smooth_hyperplane_section M -> KahlerManifold.

Theorem shs_ambient_is_M : forall (M : KahlerManifold)
    (V : smooth_hyperplane_section M),
    shs_ambient M V = M. (** ambient manifold is M itself *)
Proof. admit. Admitted.

(** V as a Kähler manifold. *)
Parameter shs_manifold : forall (M : KahlerManifold),
    smooth_hyperplane_section M -> KahlerManifold.

(** The complex dimension of V is n-1. *)
Theorem shs_dim : forall (M : KahlerManifold) (V : smooth_hyperplane_section M),
    km_dim (shs_manifold M V) = km_dim M - 1.
Proof. admit. Admitted.

(* ================================================================== *)
(** * 2. Restriction map on cohomology                                 *)
(* ================================================================== *)

(** The restriction map r : H^q(M) -> H^q(V) induced by inclusion. *)
Parameter restriction_map : forall (M : KahlerManifold)
    (V : smooth_hyperplane_section M) (q : nat),
    HdR M q -> HdR (shs_manifold M V) q.

Theorem restriction_map_linear : forall (M : KahlerManifold)
    (V : smooth_hyperplane_section M) (q : nat)
    (u v : HdR M q),
    restriction_map M V q (vs_add (HdR_vs M q) u v) =
    vs_add (HdR_vs (shs_manifold M V) q)
           (restriction_map M V q u)
           (restriction_map M V q v).
Proof. admit. Admitted.

(* ================================================================== *)
(** * 3. Lefschetz hyperplane theorem                                  *)
(* ================================================================== *)

(** Lefschetz hyperplane theorem: restriction iso for q < n-1. *)
Theorem lefschetz_hyperplane_iso : forall (M : KahlerManifold)
    (V : smooth_hyperplane_section M) (q : nat),
    (q < km_dim M - 1)%nat ->
    (** r : H^q(M) -> H^q(V) is an isomorphism — axiomatized *)
    forall u : HdR M q,
    restriction_map M V q u = vs_zero (HdR_vs (shs_manifold M V) q) ->
    u = vs_zero (HdR_vs M q).
Proof. admit. Admitted.

(** Lefschetz hyperplane theorem: restriction injective for q = n-1. *)
Theorem lefschetz_hyperplane_injective : forall (M : KahlerManifold)
    (V : smooth_hyperplane_section M),
    (** r : H^{n-1}(M) -> H^{n-1}(V) is injective — axiomatized *)
    forall u : HdR M (km_dim M - 1),
    restriction_map M V (km_dim M - 1) u =
        vs_zero (HdR_vs (shs_manifold M V) (km_dim M - 1)) ->
    u = vs_zero (HdR_vs M (km_dim M - 1)).
Proof. admit. Admitted.

(** Surjectivity for q = n-1. *)
Theorem lefschetz_hyperplane_surjective : forall (M : KahlerManifold)
    (V : smooth_hyperplane_section M) (v : HdR (shs_manifold M V) (km_dim M - 1)),
    exists u : HdR M (km_dim M - 1),
    restriction_map M V (km_dim M - 1) u = v.
Proof. admit. Admitted.

(* ================================================================== *)
(** * 4. Corollaries for projective hypersurfaces                      *)
(* ================================================================== *)

(** A smooth projective hypersurface V ⊂ P^n of complex dimension n-1
    has H^{2k-1}(V) = 0 for k ≠ n/2 (primitive middle cohomology only). *)
Theorem projective_hypersurface_odd_vanishing : forall (n k : nat)
    (V : KahlerManifold),
    km_dim V = n - 1 ->
    (k <> n / 2)%nat ->
    (** H^{2k-1}(V) = 0 when k ≠ n/2 — axiomatized *)
    True.
Proof. intros; exact I. Qed.

(** π₁(V) = 0 when dim V ≥ 2. *)
Theorem projective_hypersurface_simply_connected : forall (n : nat)
    (V : KahlerManifold),
    km_dim V = n - 1 ->
    (2 <= n - 1)%nat ->
    (** π₁(V) is trivial — axiomatized *)
    True.
Proof. intros; exact I. Qed.
