(** * DecisionProblems/Scaffolding/BassLubotzky.v

    SCAFFOLDING for the Bass-Lubotzky / Mal'cev specialization theorem,
    needed for the McReynolds property-(D) ⟹ conjugacy-separable chain.

    Statement (informally): if R is a finitely generated commutative
    integral domain and r ∈ R is nonzero, then there exists a finite
    field F_q and a ring homomorphism R → F_q sending r to nonzero. *)

From CAG Require Import Galois.Field.
From CAG Require Import Group.
From CAG Require Import Rings.Ring.
From CAG Require Import DecisionProblems.TraceProperties.
From CAG Require Import DecisionProblems.Specialization.
From Stdlib Require Import List Arith ZArith.
Import ListNotations.

(* ================================================================== *)
(** * 1. Setup: f.g. integral domains and reductions                   *)
(* ================================================================== *)

(** Abstract finitely-generated commutative ring: re-using the
    existing [FGRing] record from [DecisionProblems.Specialization.v]. *)

(** A "specialization" of R is a ring homomorphism R → F to a finite
    field F. For our purposes, we want R → F_q for some prime power q. *)

Record FiniteFieldSpecialization (R : FGRing) : Type :=
  { ffs_target_carrier : Type
  ; ffs_target_ring    : Ring ffs_target_carrier
  ; ffs_target_finite  : list ffs_target_carrier
  ; ffs_finite_complete : forall x : ffs_target_carrier,
                          In x ffs_target_finite
  ; ffs_hom            : RingHom (fgr_ring R) ffs_target_ring
  }.

(* ================================================================== *)
(** * 2. The Bass-Lubotzky specialization (scaffolded)                 *)
(* ================================================================== *)

(** **BASS-LUBOTZKY:** For any nonzero r ∈ R (a f.g. integral domain),
    there's a specialization R → F_q with r ↦ nonzero.

    Proof sketch:
    1. Consider the spectrum Spec(R), which is a connected scheme of
       finite type over Z.
    2. The closed points of Spec(R) correspond to maximal ideals.
    3. By generic flatness over Z, all but finitely many primes p
       have non-degenerate fiber R/pR.
    4. The reduction map R → R/pR for "most" p is a finite-rank
       free-module-over-F_p map.
    5. The element r reduces to nonzero in some such fiber unless r is
       in every maximal ideal of R, i.e., r ∈ Jacobson radical = 0
       (for finitely generated f.g. integral domains over Z).

    This is a classical result; one reference is Bass-Lubotzky 1983,
    "Linear-central filtrations on groups". The proof uses commutative
    algebra (going back to Hilbert's Nullstellensatz over Z). *)

Conjecture bass_lubotzky_specialization_v2 :
  forall (R : FGRing) (r : fgr_carrier R),
    r <> rzero (fgr_carrier R) (fgr_ring R) ->
    exists (Q : FiniteFieldSpecialization R),
      rhom_fn (ffs_hom R Q) r <> rzero _ (ffs_target_ring R Q).

(* ================================================================== *)
(** * 3. From Bass-Lubotzky to Proposition 1.3                          *)
(* ================================================================== *)

(** **PROPOSITION 1.3 (McReynolds): Property (D) ⟹ conjugacy separable.**

    Given (D): for non-conjugate γ, η in a group Γ, there exists a
    representation ρ : Γ → SL(n, F) with tr(ρ(γ)) ≠ tr(ρ(η)).

    We want: for non-conjugate γ, η, there exists a finite quotient
    of Γ where they have different images.

    Chain of arguments:
    1. By (D), tr(ρ(γ)) - tr(ρ(η)) =: t ≠ 0 in F.
    2. The trace polynomial t lies in a finitely generated subring
       R ⊆ F (generated by the matrix entries of ρ(γ_1), ..., ρ(γ_r)
       for the generators of Γ).
    3. R is a f.g. integral domain (assuming F is a domain).
    4. By Bass-Lubotzky, there's R → F_q with t ↦ nonzero in F_q.
    5. The induced rep ρ_q : Γ → SL(n, F_q) has finite image (since
       SL(n, F_q) is finite).
    6. In ρ_q's finite image, ρ_q(γ) and ρ_q(η) have different traces,
       hence are not conjugate. *)

Conjecture proposition_1_3_via_BL :
  forall {G F : Type} (sg : StrictGroup G) (MG_family : nat -> MatrixGroup F)
         (HD : property_D sg MG_family)
         (* The trace difference can be bracketed in a f.g. integral
            domain — the Specialization layer handles this. *)
         (gamma eta : G) (Hnc : ~ are_conjugate sg gamma eta),
    (* Then there exists a finite quotient distinguishing γ from η. *)
    exists (Q : Type) (sq : StrictGroup Q) (Q_list : list Q)
           (Q_complete : forall x : Q, In x Q_list)
           (phi : GroupHom sg sq),
      ~ are_conjugate sq (hom_fn phi gamma) (hom_fn phi eta).

(* ================================================================== *)
(** * 4. What's still needed                                            *)
(* ================================================================== *)

(** To formally prove Bass-Lubotzky in Coq:
    1. Develop commutative algebra: f.g. integral domains, Spec, primes.
    2. Develop scheme-theoretic flatness over Z.
    3. Hilbert's Nullstellensatz over Z (relating Jacobson radical to
       nilradical for f.g. rings over Z).
    4. The specific argument that "most" specializations work.

    Each of these is a substantial undertaking. The 1983 Bass-Lubotzky
    paper is ~30 pages of dense commutative algebra. *)
