(** * DecisionProblems/Scaffolding/HallFreeGroup.v

    SCAFFOLDING for Marshall Hall's theorem on subgroups of finitely
    generated free groups, restricted to what's needed for the
    Hall-Frobenius construction in the McReynolds property-(B) chain.

    Hall (1949): every finitely generated subgroup H of a free group
    F is itself free, and every finitely generated subgroup is a free
    factor of a finite-index subgroup of F.

    For our application (theorem_1_6_free_groups): given γ ∈ F_r,
    Hall's theorem provides a finite-index normal subgroup Δ ⊴ F_r
    such that ⟨γ⟩ is a free factor of Δ. From this Δ, the induced
    representation construction + Frobenius trace formula gives a
    representation distinguishing γ from any non-conjugate η. *)

From CAG Require Import Group FreeGroup.
From CAG Require Import DecisionProblems.OpenProblems.
From CAG Require Import DecisionProblems.HallTheorem.
From Stdlib Require Import List Arith.
Import ListNotations.

(* ================================================================== *)
(** * 1. Subgroup structure for free groups                            *)
(* ================================================================== *)

(** A finitely generated subgroup of [RWord r], represented as a list
    of generators. *)

Definition fg_subgroup (r : nat) := list (RWord r).

(** Membership in the subgroup generated by a list of elements. *)
Inductive subgroup_gen {r : nat} (gens : fg_subgroup r) : RWord r -> Prop :=
  | sg_e : subgroup_gen gens (@rword_e r)
  | sg_gen : forall g, In g gens -> subgroup_gen gens g
  | sg_inv : forall g, subgroup_gen gens g ->
                       subgroup_gen gens (rword_inv g)
  | sg_mul : forall g h, subgroup_gen gens g -> subgroup_gen gens h ->
                         subgroup_gen gens (rword_mul g h).

(* ================================================================== *)
(** * 2. Hall's theorems (scaffolded)                                  *)
(* ================================================================== *)

(** **HALL'S THEOREM (Nielsen-Schreier):** Every subgroup of a free
    group is free.

    For our purposes, we need the FINITELY GENERATED, FINITE INDEX
    case: every finite-index subgroup of F_r is itself free of finite
    rank, with rank computable via the Schreier formula:
      rank(H) = 1 + [F_r : H] · (r - 1)

    Proof sketch: build a Schreier transversal for H, get a free
    generating set from the "Schreier generators" — a standard
    construction. *)

Lemma hall_subgroup_is_free :
  forall (r : nat) (H : RWord r -> Prop)
         (Hsub : forall x y, H x -> H y -> H (rword_mul x y))
         (Hinv : forall x, H x -> H (rword_inv x))
         (Hid  : H (@rword_e r)),
    (* H is a free group on some set of generators *)
    True. (* placeholder *)
Proof. intros. exact I. Qed.

(** **HALL'S FREE FACTOR THEOREM:** Given γ ∈ F_r with γ ≠ e, there
    exists a finite-index subgroup Δ ≤ F_r such that γ is part of a
    free generating set for Δ (so ⟨γ⟩ is a free factor of Δ).

    The proof uses Stallings folding / Schreier coset graphs:
    1. Build the coset graph of ⟨γ⟩ in F_r (infinite).
    2. Fold it into a finite "core" graph using Stallings folding.
    3. The core graph has finitely many vertices and edges.
    4. Add edges to create a finite-index subgroup containing ⟨γ⟩
       as a free factor. *)

(** This is what's already in [HallTheorem.hall_finite_index_free_factor]. *)

(** **STALLINGS FOLDING:** A Stallings folding takes a finite labeled
    graph and produces an "immersed" graph by identifying edges with
    the same label and same source. This is the algorithmic core of
    Hall's free factor construction. *)

Inductive stallings_folding (r : nat) : Type :=
  | sf_node : list (RWord r) -> stallings_folding r.

(** Folding step: identify two edges from the same vertex with the
    same label. *)

Lemma stallings_fold_step :
  forall (r : nat) (g : stallings_folding r),
    {g' : stallings_folding r | True}.  (* placeholder *)
Proof. intros. exists g. exact I. Qed.

(** Folding is terminating: any finite labeled graph reaches an
    immersed graph in finitely many steps. *)

Lemma stallings_fold_terminates :
  forall (r : nat) (g : stallings_folding r),
    exists k, forall (n : nat), k <= n -> True.  (* placeholder *)
Proof. intros. exists 0%nat. intros. exact I. Qed.

(* ================================================================== *)
(** * 3. The free-factor decomposition (scaffolded)                    *)
(* ================================================================== *)

(** Given a finitely generated subgroup H ≤ F_r and the corresponding
    Stallings core graph G, decompose H = ⟨S₁⟩ * ⟨S₂⟩ * ... * ⟨S_k⟩
    where each S_i is a free factor obtained from a "loop" in the core. *)

Lemma stallings_free_factor_decomposition :
  forall (r : nat) (H_gens : list (RWord r)),
    (* H = subgroup generated by H_gens decomposes as a free product
       of "loop" subgroups in its Stallings core. *)
    True. (* placeholder *)
Proof. intros. exact I. Qed.

(* ================================================================== *)
(** * 4. From Hall to property (B)                                     *)
(* ================================================================== *)

(** **CHAIN to theorem_1_6_free_groups:**

    1. Given γ ∈ F_r with γ ≠ e, [hall_finite_index_free_factor] gives
       Δ ⊴ F_r with [F_r : Δ] = k and ⟨γ⟩ a free factor of Δ.

    2. For any matrix group MG, take ρ : ⟨γ⟩ → MG sending γ to a
       chosen matrix A with tr(A) chosen so that tr(A^j) ≠ tr(A^l)
       for j ≠ l up to some bound. Such A always exists (e.g.,
       hyperbolic).

    3. Extend ρ to ρ_Δ : Δ → MG via the free-factor structure (trivially
       on the other factors).

    4. Induce ρ_Δ to ρ_F_r : F_r → SL(k·n, F) via Frobenius induction.

    5. The trace formula gives:
         tr(ρ_F_r(g)) = Σ_{i: σ_g(i)=i} tr(ρ_Δ(h_i))
       where σ_g is the coset permutation, h_i is the cocycle.

    6. For γ itself: σ_γ has fixed points exactly at cosets where γ
       acts trivially on the index. The trace becomes a polynomial in
       tr(A^j) values.

    7. For η non-conjugate to γ: σ_η has DIFFERENT fixed-point structure,
       giving a different trace polynomial. *)

(** Formalization status:
    - [hall_finite_index_free_factor] : axiomatized in HallTheorem.v.
    - [hall_free_factor_decomp]: axiomatized.
    - [hall_construction_separates]: the full construction, axiomatized.

    To fully PROVE theorem_1_6_free_groups, we'd need to prove all three
    Hall-related axioms via Stallings folding + Schreier transversals +
    Frobenius character formula. Each is doable but represents
    substantial combinatorial group theory infrastructure. *)
