(** * DecisionProblems/Scaffolding/Procesi.v

    SCAFFOLDING for Procesi's theorem on polynomial invariants of
    n-tuples of n×n matrices under simultaneous conjugation, restricted
    to what's needed to attack [open_SLn_trace_pair n] for n ≥ 3.

    Procesi (1976): The ring of polynomial invariants of m-tuples of
    n×n matrices under simultaneous conjugation is generated by traces
    of all monomials of length ≤ n² in the m matrices.

    For our application (open_SLn_trace_pair): if two F_r elements have
    equal traces under EVERY SL(n,ℂ) representation (equivalently, equal
    trace polynomials in r matrix variables under SL(n) conjugation),
    Procesi gives that they're identified in the GIT quotient
    SL(n,ℂ)^r / SL(n,ℂ). Combined with Procesi's separation refinement,
    this would imply they're either conjugate or differ by a "boundary"
    in the GIT quotient.

    We do NOT prove Procesi here — it's a major theorem in invariant
    theory. We scaffold the statement and the chain of reductions. *)

From CAG Require Import Galois.Field.
From CAG Require Import Group FreeGroup.
From CAG Require Import LinAlg.Matrix2 LinAlg.SL2.
From CAG Require Import DecisionProblems.TraceProperties.
From CAG Require Import DecisionProblems.OpenProblems.
From Stdlib Require Import List Arith.
Import ListNotations.

(* ================================================================== *)
(** * 1. Polynomial invariants of m-tuples of n×n matrices             *)
(* ================================================================== *)

(** A "matrix word" of length k in m matrix variables is a list of
    indices in {0, ..., m-1} of length k, denoting the corresponding
    product. *)

Definition matrix_word (m : nat) := list nat.

(** The trace of the matrix word evaluated at an m-tuple of n×n
    matrices in SL(n, F). For our purposes, we work abstractly: a
    "matrix variable assignment" maps {0..m-1} to elements of a
    MatrixGroup, and the trace polynomial is the trace of the product. *)

Section MatrixWordTrace.
  Context {F : Type} (fld : Field F) (n m : nat).

  (** Abstract matrix variable assignment. *)
  Definition mat_assignment :=
    forall i : nat, i < m -> mg_carrier (SL2_as_MG fld).
    (* For full Procesi we'd need SL(n) not SL(2); keeping SL(2) for
       illustration. The full SL(n) version requires Mat_n infrastructure. *)

  (** Matrix word evaluation requires looking up each index in the
      assignment and multiplying. Since we don't have Fin-bounded
      lookups in our matrix_word (which uses [nat] indices), this is
      partial. In the full version we'd use Fin.t m. *)

End MatrixWordTrace.

(* ================================================================== *)
(** * 2. The Procesi statement (scaffolded)                            *)
(* ================================================================== *)

(** PROCESI'S FUNDAMENTAL THEOREM (specialized): The ring of polynomial
    invariants of m-tuples of n×n matrices under simultaneous conjugation
    by SL(n, ℂ) is generated by the trace functions of products of length
    ≤ n² of the matrix variables.

    Equivalently: if two products W_1, W_2 of the matrix variables have
    the same trace as polynomials in the entries (under SL(n)
    conjugation), then their image in the GIT quotient is the same.

    For our application: if γ, η ∈ F_r have tr(ρ(γ)) = tr(ρ(η)) for
    every ρ : F_r → SL(n, ℂ) (equivalently, every assignment of γ, η
    to product expressions), then they're conjugate in SL(n, ℂ)
    via the GIT closure. *)

(** Procesi trace separation: trace agreement on all reps implies
    GIT-equivalence.
    Informal: if gamma, eta in F_r have tr(rho(gamma)) = tr(rho(eta))
    for every SL(n, F) representation rho, then gamma and eta lie in
    the same orbit of the SL(n, F)-conjugation action on
    Hom(F_r, SL(n, F)) modulo GIT, i.e. their orbit closures coincide.
    For n >= 3 over the complex numbers, GIT-equivalence and
    conjugation-equivalence coincide off the unipotent boundary.
    Pending the [GIT_equiv] / [orbit_closure] predicate; encoded as
    signature-bearing reflexive on (n_dim, r).
    Ref: Procesi "The invariant theory of n x n matrices",
    Adv. Math. 19 (1976) 306-381 [Theorem 3.4]; Mumford-Fogarty-Kirwan
    "Geometric Invariant Theory" §1.4; Drensky "Free Algebras and
    PI-algebras" Ch. 4. *)
(* CAG zero-dependent Conjecture procesi_trace_separation theories/DecisionProblems/Scaffolding/Procesi.v:93 BEGIN
Conjecture procesi_trace_separation :
  forall {F : Type} (fld : Field F) (n_dim : nat) (r : nat)
         (gamma eta : RWord r),
    (forall rho : Representation (FreeGroup r) (SL2_as_MG fld),
        trace_at rho gamma = trace_at rho eta) ->
    (n_dim + r)%nat = (n_dim + r)%nat.
   CAG zero-dependent Conjecture procesi_trace_separation theories/DecisionProblems/Scaffolding/Procesi.v:93 END *)

(* ================================================================== *)
(** * 3. Reduction to open_SLn_trace_pair                              *)
(* ================================================================== *)

(** Procesi gives one direction of:

    OPEN: For F_r with r ≥ 2 and n ≥ 3, there is NO non-conjugate
    pair (γ, η) with tr(ρ(γ)) = tr(ρ(η)) for every SL(n)-rep ρ.

    The forward direction (γ ∼ η ⟹ trace agreement) is sl2-style and
    is one direction of [conjugate_implies_SLn_trace_equivalent].

    The reverse direction is the OPEN question. Procesi's theorem
    almost gives it: if traces agree for all reps, then γ, η lie in
    the same GIT orbit. The remaining gap: GIT-orbits in SL(n)^r
    coincide with conjugation-orbits when restricted to a certain
    "stable" locus.

    PROOF SKETCH for n ≥ 3:
    1. By Procesi, trace polynomials separate GIT orbits.
    2. F_r has a "thick" set of conjugacy classes whose representations
       are all stable (e.g., irreducible reps).
    3. For stable orbits, GIT-equivalence = conjugation-equivalence.
    4. So trace-equivalence at SL(n) for n ≥ 3 implies conjugacy
       (modulo a measure-zero locus we can sidestep). *)

(* ================================================================== *)
(** * 4. Length bounds for trace generation                            *)
(* ================================================================== *)

(** Procesi's theorem provides an EFFECTIVE BOUND: trace functions of
    monomials of length ≤ n² suffice. This is the basis for our
    empirical search: at length 11 with n=3, we cover 11 ≥ 3² = 9, so
    if no pair exists of length ≤ 11, Procesi suggests none exists at
    all. (Modulo: Procesi's bound is for the GENERATORS of the trace
    ring, not for full conjugacy separation.)

    For a complete attack, we'd need:
    1. Procesi's effective bound theorem (length ≤ n² for generators).
    2. The "stable locus" argument.
    3. Verification that empirical search exhausts all candidate pairs
       up to that length. *)

(** Procesi's effective length bound for trace-invariant generators.
    Informal: the trace polynomials of monomials of length <= n^2
    generate the full ring of SL(n, C) trace invariants on the
    representation variety Hom(F_r, SL(n, C)).  This is the
    "fundamental theorem of matrix invariants" with explicit length
    bound n^2.  Pending the [generates] predicate on the trace-ring;
    encoded as signature-bearing reflexive on n^2.
    Ref: Procesi (1976) Adv. Math. 19, Theorem 4.5; Razmyslov,
    Math. USSR Izvestiya 8 (1974); Donkin "Invariants of several
    matrices", Invent. Math. 110 (1992) [refined bound]. *)
(* CAG zero-dependent Conjecture procesi_length_bound theories/DecisionProblems/Scaffolding/Procesi.v:153 BEGIN
Conjecture procesi_length_bound :
  forall (n : nat),
    (n * n)%nat = (n * n)%nat.
   CAG zero-dependent Conjecture procesi_length_bound theories/DecisionProblems/Scaffolding/Procesi.v:153 END *)

(* ================================================================== *)
(** * 5. What's still open after Procesi                               *)
(* ================================================================== *)

(** Even with Procesi, the question "no SL(n)-trace pair for n ≥ 3"
    requires MORE: Procesi separates GIT orbits but the gap from GIT
    orbit to conjugation orbit involves the "trace-only" boundary
    (where reps degenerate to non-irreducible).

    Concretely, at SL(2,F): Procesi-Horowitz gives that trace-equivalence
    coincides with conjugacy modulo INVERSION (γ ∼ η or γ ∼ η⁻¹). The
    "modulo inversion" is the trace-boundary phenomenon.

    For n ≥ 3, the analogous "mod boundary" is more elaborate. A clean
    statement for n=3 would be:

      "If γ, η ∈ F_r are SL(3,ℂ)-trace-equivalent, then they are
       conjugate in F_r modulo a finite group of automorphisms of F_r
       (perhaps including inversion and other symmetries)."

    No such clean statement is currently known. *)
