(** * Domains/DedekindHasseNorm.v — Dedekind-Hasse norms

    A Dedekind-Hasse norm witnesses that a domain is a PID.

    Reference: Dummit & Foote §8.2. *)

From CAG Require Import Rings.Ring Domains.Divisibility Domains.Associates
                        Domains.IrreduciblePrime Domains.UFD Domains.PID_UFD.
From Stdlib Require Import Arith Lia Classical.

(* ================================================================== *)
(** ** Dedekind-Hasse norm *)
(* ================================================================== *)

Section DedekindHasse.
  Context {R : Type} (d : IntegralDomain R).

  Let r : Ring R := id_r d.

  (** A Dedekind-Hasse norm is a function N : R -> nat satisfying:
      For any nonzero a, b ∈ R, if a ∉ (b) (a does not divide b in the ideal sense),
      then there exists nonzero r ∈ (a, b) (in the ideal generated by a and b)
      with N(r) < N(b). *)
  Record IsDedekindHasseNorm (N : R -> nat) : Prop := {
    dhn_zero : N (rzero R r) = 0;
    dhn_pos  : forall a : R, a <> rzero R r -> 0 < N a;
    dhn_div_or_smaller :
      forall a b : R,
        b <> rzero R r ->
        (** Either a ∈ (b) (b divides a) *)
        divides r b a \/
        (** Or there exists nonzero ρ ∈ (a,b) = aR + bR with N(ρ) < N(b) *)
        (exists rho : R,
          rho <> rzero R r /\
          (exists x y : R,
            rho = radd R r (rmul R r x a) (rmul R r y b)) /\
          N rho < N b);
  }.

  (** Multiplicative norm: N(ab) = N(a) * N(b) *)
  Definition is_multiplicative_norm (N : R -> nat) : Prop :=
    forall a b : R, N (rmul R r a b) = N a * N b.

  (** A PID has a Dedekind-Hasse norm *)
  Axiom pid_has_dedekind_hasse_norm :
    is_pid d ->
    exists N : R -> nat, IsDedekindHasseNorm N.

  (** A domain with a Dedekind-Hasse norm is a PID *)
  Axiom dedekind_hasse_norm_is_pid :
    forall N : R -> nat,
      IsDedekindHasseNorm N ->
      is_pid d.

  (** In a UFD, define a multiplicative Dedekind-Hasse norm by prime factorization:
      N(0) = 0, N(unit) = 1, N(a) = 2^(number of irreducible factors of a) *)
  (** Placeholder norm; the axioms below characterize its properties *)
  Definition ufd_norm (H : IsUFD d) (a : R) : nat := 0.

  (** The norm defined via factorization length is multiplicative and Dedekind-Hasse *)
  (** Full proof requires the axiom of choice and detailed UFD machinery *)
  Axiom ufd_norm_multiplicative : forall (H : IsUFD d),
      is_multiplicative_norm (ufd_norm H).

  Axiom ufd_norm_dedekind_hasse : forall (H : IsUFD d),
      IsDedekindHasseNorm (ufd_norm H).

End DedekindHasse.

Arguments IsDedekindHasseNorm {R} d N.
