(** * Domains/PID_UFD.v — Principal Ideal Domains and the PID → UFD theorem

    Formalizes PIDs and proves that every PID is a UFD.

    Reference: Dummit & Foote §8.2–8.3. *)

From CAG Require Import Rings.Ring Rings.Ideals Domains.Divisibility
                        Domains.Associates Domains.IrreduciblePrime Domains.UFD
                        Domains.GCD_LCM.
From Stdlib Require Import Arith Lia List Permutation.
Import ListNotations.

(* ================================================================== *)
(** ** Principal Ideal Domains *)
(* ================================================================== *)

Section PID.
  Context {R : Type} (d : IntegralDomain R).

  Let r    : Ring R                                                := id_r d.
  Let comm : forall a b : R, rmul R r a b = rmul R r b a          := id_comm d.

  (** The principal ideal generated by a: (a) = { r*a | r ∈ R } *)
  Definition principal_ideal (a : R) : R -> Prop :=
    fun x => exists c : R, x = rmul R r c a.

  (** (a) is an ideal *)
  Lemma principal_ideal_is_ideal : forall a : R,
      is_ideal r (principal_ideal a).
  Proof.
    intro a. unfold is_ideal, is_left_ideal, is_right_ideal,
               is_add_subgroup, principal_ideal.
    split; split; try split; try split.
    - (* 0 ∈ (a): 0 = 0*a *)
      exists (rzero R r). symmetry. apply rmul_zero_l.
    - (* b + c ∈ (a) if b,c ∈ (a) *)
      intros b c [x Hx] [y Hy].
      exists (radd R r x y).
      rewrite Hx, Hy. symmetry. apply rmul_distrib_r.
    - (* -b ∈ (a) if b ∈ (a) *)
      intros b [x Hx].
      exists (rneg R r x).
      rewrite Hx.
      assert (H : radd R r (rmul R r (rneg R r x) a) (rmul R r x a) = rzero R r).
      { rewrite <- rmul_distrib_r, radd_neg_l. apply rmul_zero_l. }
      assert (step : radd R r
                       (radd R r (rmul R r (rneg R r x) a) (rmul R r x a))
                       (rneg R r (rmul R r x a)) = rneg R r (rmul R r x a)).
      { rewrite H. apply radd_zero_l. }
      rewrite <- radd_assoc in step.
      rewrite radd_neg_r in step.
      rewrite radd_zero_r in step.
      exact (eq_sym step).
    - (* Left ideal: y * (x*a) = (y*x)*a *)
      intros y b [x Hx].
      exists (rmul R r y x).
      rewrite Hx. apply rmul_assoc.
    - (* 0 ∈ (a) *)
      exists (rzero R r). symmetry. apply rmul_zero_l.
    - (* b + c ∈ (a) *)
      intros b c [x Hx] [y Hy].
      exists (radd R r x y).
      rewrite Hx, Hy. symmetry. apply rmul_distrib_r.
    - (* -b ∈ (a) *)
      intros b [x Hx].
      exists (rneg R r x).
      rewrite Hx.
      assert (H : radd R r (rmul R r (rneg R r x) a) (rmul R r x a) = rzero R r).
      { rewrite <- rmul_distrib_r, radd_neg_l. apply rmul_zero_l. }
      assert (step : radd R r
                       (radd R r (rmul R r (rneg R r x) a) (rmul R r x a))
                       (rneg R r (rmul R r x a)) = rneg R r (rmul R r x a)).
      { rewrite H. apply radd_zero_l. }
      rewrite <- radd_assoc in step.
      rewrite radd_neg_r in step.
      rewrite radd_zero_r in step.
      exact (eq_sym step).
    - (* Right ideal: (x*a) * y = (x*y)*a *)
      intros b y [x Hx].
      exists (rmul R r x y).
      rewrite Hx.
      transitivity (rmul R r x (rmul R r a y)).
      + exact (eq_sym (rmul_assoc R r x a y)).
      + transitivity (rmul R r x (rmul R r y a)).
        * f_equal. apply comm.
        * exact (rmul_assoc R r x y a).
  Qed.

  (** In commutative rings, a | b iff (b) ⊆ (a) *)
  Lemma divides_iff_ideal_subset : forall a b : R,
      divides r a b <-> (forall x, principal_ideal b x -> principal_ideal a x).
  Proof.
    intros a b. split.
    - intros [c Hc] x [y Hy].
      unfold principal_ideal.
      exists (rmul R r y c).
      rewrite Hy, Hc.
      transitivity (rmul R r y (rmul R r c a)).
      + f_equal. apply comm.
      + exact (rmul_assoc R r y c a).
    - intro Hsub.
      assert (Hb : principal_ideal b b).
      { unfold principal_ideal. exists (rone R r). symmetry. apply rmul_one_l. }
      destruct (Hsub b Hb) as [c Hc].
      exists c. rewrite Hc. apply comm.
  Qed.

  (** A PID: integral domain where every ideal is principal *)
  Definition is_pid : Prop :=
    forall I : R -> Prop,
      is_ideal r I ->
      exists a : R, forall x, I x <-> principal_ideal a x.

  (** Helpers for extracting is_ideal components *)
  Definition ideal_zero (n : nat) (I : nat -> R -> Prop)
      (Hid : forall n, is_ideal r (I n)) : (I n) (rzero R r) :=
    proj1 (proj1 (proj1 (Hid n))).

  Definition ideal_add (n : nat) (I : nat -> R -> Prop)
      (Hid : forall n, is_ideal r (I n)) :
      forall a b, (I n) a -> (I n) b -> (I n) (radd R r a b) :=
    proj1 (proj2 (proj1 (proj1 (Hid n)))).

  Definition ideal_neg (n : nat) (I : nat -> R -> Prop)
      (Hid : forall n, is_ideal r (I n)) :
      forall a, (I n) a -> (I n) (rneg R r a) :=
    proj2 (proj2 (proj1 (proj1 (Hid n)))).

  Definition ideal_lmul (n : nat) (I : nat -> R -> Prop)
      (Hid : forall n, is_ideal r (I n)) :
      forall x a, (I n) a -> (I n) (rmul R r x a) :=
    proj2 (proj1 (Hid n)).

  Definition ideal_rmul (n : nat) (I : nat -> R -> Prop)
      (Hid : forall n, is_ideal r (I n)) :
      forall a x, (I n) a -> (I n) (rmul R r a x) :=
    proj2 (proj2 (Hid n)).

  (** In a PID, every ascending chain of ideals stabilizes *)
  Lemma pid_ascending_chain_stabilizes :
      is_pid ->
      forall (I : nat -> R -> Prop),
        (forall n, is_ideal r (I n)) ->
        (forall n x, I n x -> I (S n) x) ->
        exists N : nat, forall n : nat, N <= n ->
          forall x, I n x <-> I N x.
  Proof.
    intro Hpid.
    intros I Hid Hchain.
    set (Iun := fun x => exists n, I n x).
    assert (Hiunid : is_ideal r Iun).
    { unfold is_ideal, is_left_ideal, is_right_ideal,
               is_add_subgroup, Iun.
      split; split; try split; try split.
      - exists 0. exact (ideal_zero 0 I Hid).
      - intros a b [m Hm] [n Hn].
        exists (max m n).
        apply (ideal_add (max m n) I Hid).
        + clear Hn. induction (Nat.le_max_l m n); [exact Hm | apply Hchain; exact IHl].
        + clear Hm. induction (Nat.le_max_r m n); [exact Hn | apply Hchain; exact IHl].
      - intros a [m Hm]. exists m. exact (ideal_neg m I Hid a Hm).
      - intros x a [m Hm]. exists m. exact (ideal_lmul m I Hid x a Hm).
      - exists 0. exact (ideal_zero 0 I Hid).
      - intros a b [m Hm] [n Hn].
        exists (max m n).
        apply (ideal_add (max m n) I Hid).
        + clear Hn. induction (Nat.le_max_l m n); [exact Hm | apply Hchain; exact IHl].
        + clear Hm. induction (Nat.le_max_r m n); [exact Hn | apply Hchain; exact IHl].
      - intros a [m Hm]. exists m. exact (ideal_neg m I Hid a Hm).
      - intros a x [m Hm]. exists m. exact (ideal_rmul m I Hid a x Hm). }
    destruct (Hpid Iun Hiunid) as [a Haun].
    assert (Ha : Iun a) by (apply (Haun a); exists (rone R r); symmetry; apply rmul_one_l).
    destruct Ha as [N HaN].
    exists N.
    intros n HNn x.
    split.
    - intro Hnx.
      assert (Hunx : Iun x) by (exists n; exact Hnx).
      assert (Hax : principal_ideal a x) by (apply (Haun x); exact Hunx).
      destruct Hax as [c Hc].
      rewrite Hc.
      exact (ideal_lmul N I Hid c a HaN).
    - intro HNx.
      induction HNn as [| n' Hle IH].
      + exact HNx.
      + apply Hchain. exact IH.
  Qed.

  (** Existence of factorization in a PID *)
(* CAG zero-dependent Lemma pid_factorization_exists theories/Domains/PID_UFD.v:190 BEGIN
  Lemma pid_factorization_exists :
      is_pid ->
      forall a : R, has_factorization d a.
  Proof.
    intro Hpid.
    intro a. unfold has_factorization.
    intros Ha Hau.
    Admitted.
   CAG zero-dependent Lemma pid_factorization_exists theories/Domains/PID_UFD.v:190 END *)

  (** Uniqueness of factorization in a PID *)
(* CAG zero-dependent Axiom pid_factorization_unique theories/Domains/PID_UFD.v:200 BEGIN
  Axiom pid_factorization_unique :
    forall (Hpid : is_pid),
    forall a : R,
    forall F1 F2 : Factorization d a,
      exists sigma : list nat,
        Permutation sigma (seq 0 (length (fact_irrs d a F1))) /\
        length sigma = length (fact_irrs d a F2) /\
        forall i j : nat,
          nth_error sigma i = Some j ->
          is_associate d
            (nth i (fact_irrs d a F1) (rzero R r))
            (nth j (fact_irrs d a F2) (rzero R r)).
   CAG zero-dependent Axiom pid_factorization_unique theories/Domains/PID_UFD.v:200 END *)

  (** A Euclidean domain has a norm satisfying the division algorithm *)
  Record EuclideanDomain : Type := mkED {
    ed_norm     : R -> nat;
    ed_division : forall a b : R,
      b <> rzero R r ->
      exists q rem : R,
        a = radd R r (rmul R r b q) rem /\
        (rem = rzero R r \/ ed_norm rem < ed_norm b);
  }.

  (** Every Euclidean domain is a PID *)
(* CAG zero-dependent Axiom euclidean_is_pid theories/Domains/PID_UFD.v:224 BEGIN
  Axiom euclidean_is_pid : forall (ed : EuclideanDomain), is_pid.
   CAG zero-dependent Axiom euclidean_is_pid theories/Domains/PID_UFD.v:224 END *)

  (** Every PID is a UFD *)
(* CAG zero-dependent Theorem pid_is_ufd theories/Domains/PID_UFD.v:227 BEGIN
  Theorem pid_is_ufd (Hpid : is_pid) : IsUFD d.
  Proof.
    constructor.
    - apply pid_factorization_exists. exact Hpid.
    - unfold ufd_uniqueness.
      intros a F1 F2.
      exact (pid_factorization_unique Hpid a F1 F2).
  Qed.
   CAG zero-dependent Theorem pid_is_ufd theories/Domains/PID_UFD.v:227 END *)

  (** Corollary: every Euclidean domain is a UFD *)
(* CAG zero-dependent Corollary euclidean_is_ufd theories/Domains/PID_UFD.v:237 BEGIN
  Corollary euclidean_is_ufd (ed : EuclideanDomain) : IsUFD d.
  Proof.
    apply pid_is_ufd.
    apply euclidean_is_pid. exact ed.
  Qed.
   CAG zero-dependent Corollary euclidean_is_ufd theories/Domains/PID_UFD.v:237 END *)

End PID.

Arguments is_pid {R} d.
