(** * Domains/PID_UFD.v — Principal Ideal Domains and the PID → UFD theorem

    Formalizes PIDs and proves that every PID is a UFD.

    Reference: Dummit & Foote §8.2–8.3. *)

From CAG Require Import Rings.Ring Rings.Ideals Domains.Divisibility
                        Domains.Associates Domains.IrreduciblePrime Domains.UFD
                        Domains.GCD_LCM.
From Stdlib Require Import Arith Lia List Permutation Classical
                           IndefiniteDescription.
Import ListNotations.

(* ================================================================== *)
(** ** Principal Ideal Domains *)
(* ================================================================== *)

Section PID.
  Context {R : Type} (d : IntegralDomain R).

  Let r    : Ring R                                                := id_r d.
  Let comm : forall a b : R, rmul R r a b = rmul R r b a          := id_comm d.

  (** The principal ideal generated by a: (a) = { r*a | r ∈ R } *)
  Definition principal_ideal (a : R) : R -> Prop :=
    fun x => exists c : R, x = rmul R r c a.

  (** (a) is an ideal *)
  Lemma principal_ideal_is_ideal : forall a : R,
      is_ideal r (principal_ideal a).
  Proof.
    intro a. unfold is_ideal, is_left_ideal, is_right_ideal,
               is_add_subgroup, principal_ideal.
    split; split; try split; try split.
    - (* 0 ∈ (a): 0 = 0*a *)
      exists (rzero R r). symmetry. apply rmul_zero_l.
    - (* b + c ∈ (a) if b,c ∈ (a) *)
      intros b c [x Hx] [y Hy].
      exists (radd R r x y).
      rewrite Hx, Hy. symmetry. apply rmul_distrib_r.
    - (* -b ∈ (a) if b ∈ (a) *)
      intros b [x Hx].
      exists (rneg R r x).
      rewrite Hx.
      assert (H : radd R r (rmul R r (rneg R r x) a) (rmul R r x a) = rzero R r).
      { rewrite <- rmul_distrib_r, radd_neg_l. apply rmul_zero_l. }
      assert (step : radd R r
                       (radd R r (rmul R r (rneg R r x) a) (rmul R r x a))
                       (rneg R r (rmul R r x a)) = rneg R r (rmul R r x a)).
      { rewrite H. apply radd_zero_l. }
      rewrite <- radd_assoc in step.
      rewrite radd_neg_r in step.
      rewrite radd_zero_r in step.
      exact (eq_sym step).
    - (* Left ideal: y * (x*a) = (y*x)*a *)
      intros y b [x Hx].
      exists (rmul R r y x).
      rewrite Hx. apply rmul_assoc.
    - (* 0 ∈ (a) *)
      exists (rzero R r). symmetry. apply rmul_zero_l.
    - (* b + c ∈ (a) *)
      intros b c [x Hx] [y Hy].
      exists (radd R r x y).
      rewrite Hx, Hy. symmetry. apply rmul_distrib_r.
    - (* -b ∈ (a) *)
      intros b [x Hx].
      exists (rneg R r x).
      rewrite Hx.
      assert (H : radd R r (rmul R r (rneg R r x) a) (rmul R r x a) = rzero R r).
      { rewrite <- rmul_distrib_r, radd_neg_l. apply rmul_zero_l. }
      assert (step : radd R r
                       (radd R r (rmul R r (rneg R r x) a) (rmul R r x a))
                       (rneg R r (rmul R r x a)) = rneg R r (rmul R r x a)).
      { rewrite H. apply radd_zero_l. }
      rewrite <- radd_assoc in step.
      rewrite radd_neg_r in step.
      rewrite radd_zero_r in step.
      exact (eq_sym step).
    - (* Right ideal: (x*a) * y = (x*y)*a *)
      intros b y [x Hx].
      exists (rmul R r x y).
      rewrite Hx.
      transitivity (rmul R r x (rmul R r a y)).
      + exact (eq_sym (rmul_assoc R r x a y)).
      + transitivity (rmul R r x (rmul R r y a)).
        * f_equal. apply comm.
        * exact (rmul_assoc R r x y a).
  Qed.

  (** In commutative rings, a | b iff (b) ⊆ (a) *)
  Lemma divides_iff_ideal_subset : forall a b : R,
      divides r a b <-> (forall x, principal_ideal b x -> principal_ideal a x).
  Proof.
    intros a b. split.
    - intros [c Hc] x [y Hy].
      unfold principal_ideal.
      exists (rmul R r y c).
      rewrite Hy, Hc.
      transitivity (rmul R r y (rmul R r c a)).
      + f_equal. apply comm.
      + exact (rmul_assoc R r y c a).
    - intro Hsub.
      assert (Hb : principal_ideal b b).
      { unfold principal_ideal. exists (rone R r). symmetry. apply rmul_one_l. }
      destruct (Hsub b Hb) as [c Hc].
      exists c. rewrite Hc. apply comm.
  Qed.

  (** A PID: integral domain where every ideal is principal *)
  Definition is_pid : Prop :=
    forall I : R -> Prop,
      is_ideal r I ->
      exists a : R, forall x, I x <-> principal_ideal a x.

  (** Helpers for extracting is_ideal components *)
  Definition ideal_zero (n : nat) (I : nat -> R -> Prop)
      (Hid : forall n, is_ideal r (I n)) : (I n) (rzero R r) :=
    proj1 (proj1 (proj1 (Hid n))).

  Definition ideal_add (n : nat) (I : nat -> R -> Prop)
      (Hid : forall n, is_ideal r (I n)) :
      forall a b, (I n) a -> (I n) b -> (I n) (radd R r a b) :=
    proj1 (proj2 (proj1 (proj1 (Hid n)))).

  Definition ideal_neg (n : nat) (I : nat -> R -> Prop)
      (Hid : forall n, is_ideal r (I n)) :
      forall a, (I n) a -> (I n) (rneg R r a) :=
    proj2 (proj2 (proj1 (proj1 (Hid n)))).

  Definition ideal_lmul (n : nat) (I : nat -> R -> Prop)
      (Hid : forall n, is_ideal r (I n)) :
      forall x a, (I n) a -> (I n) (rmul R r x a) :=
    proj2 (proj1 (Hid n)).

  Definition ideal_rmul (n : nat) (I : nat -> R -> Prop)
      (Hid : forall n, is_ideal r (I n)) :
      forall a x, (I n) a -> (I n) (rmul R r a x) :=
    proj2 (proj2 (Hid n)).

  (** In a PID, every ascending chain of ideals stabilizes *)
  Lemma pid_ascending_chain_stabilizes :
      is_pid ->
      forall (I : nat -> R -> Prop),
        (forall n, is_ideal r (I n)) ->
        (forall n x, I n x -> I (S n) x) ->
        exists N : nat, forall n : nat, N <= n ->
          forall x, I n x <-> I N x.
  Proof.
    intro Hpid.
    intros I Hid Hchain.
    set (Iun := fun x => exists n, I n x).
    assert (Hiunid : is_ideal r Iun).
    { unfold is_ideal, is_left_ideal, is_right_ideal,
               is_add_subgroup, Iun.
      split; split; try split; try split.
      - exists 0. exact (ideal_zero 0 I Hid).
      - intros a b [m Hm] [n Hn].
        exists (max m n).
        apply (ideal_add (max m n) I Hid).
        + clear Hn. induction (Nat.le_max_l m n); [exact Hm | apply Hchain; exact IHl].
        + clear Hm. induction (Nat.le_max_r m n); [exact Hn | apply Hchain; exact IHl].
      - intros a [m Hm]. exists m. exact (ideal_neg m I Hid a Hm).
      - intros x a [m Hm]. exists m. exact (ideal_lmul m I Hid x a Hm).
      - exists 0. exact (ideal_zero 0 I Hid).
      - intros a b [m Hm] [n Hn].
        exists (max m n).
        apply (ideal_add (max m n) I Hid).
        + clear Hn. induction (Nat.le_max_l m n); [exact Hm | apply Hchain; exact IHl].
        + clear Hm. induction (Nat.le_max_r m n); [exact Hn | apply Hchain; exact IHl].
      - intros a [m Hm]. exists m. exact (ideal_neg m I Hid a Hm).
      - intros a x [m Hm]. exists m. exact (ideal_rmul m I Hid a x Hm). }
    destruct (Hpid Iun Hiunid) as [a Haun].
    assert (Ha : Iun a) by (apply (Haun a); exists (rone R r); symmetry; apply rmul_one_l).
    destruct Ha as [N HaN].
    exists N.
    intros n HNn x.
    split.
    - intro Hnx.
      assert (Hunx : Iun x) by (exists n; exact Hnx).
      assert (Hax : principal_ideal a x) by (apply (Haun x); exact Hunx).
      destruct Hax as [c Hc].
      rewrite Hc.
      exact (ideal_lmul N I Hid c a HaN).
    - intro HNx.
      induction HNn as [| n' Hle IH].
      + exact HNx.
      + apply Hchain. exact IH.
  Qed.

  (* ================================================================== *)
  (** ** Existence of factorization (PID)                               *)
  (*                                                                    *)
  (** Strategy: classical contradiction.  If [a] is a non-zero non-unit
      with no factorization, build an infinite chain of strictly
      ascending principal ideals via [dependent_choice], contradicting
      [pid_ascending_chain_stabilizes].                                  *)
  (* ================================================================== *)

  (** Trivial factorization for an irreducible element: [a = 1 * (a * 1)]. *)
  Lemma irreducible_has_factorization (a : R) :
      is_irreducible d a -> Factorization d a.
  Proof.
    intro Hirr.
    refine (mkFact d a (rone R r) [a] (unit_one r) _ _).
    - intros p [Heq | []]. subst p. exact Hirr.
    - simpl. rewrite rmul_one_l, rmul_one_r. reflexivity.
  Defined.

  (** Concatenating two factorizations yields a factorization of the product. *)
  Lemma factorization_product (b c : R) :
      Factorization d b -> Factorization d c -> Factorization d (rmul R r b c).
  Proof.
    intros [ub bs Hub Hbs Hb_eq] [uc cs Huc Hcs Hc_eq].
    refine (mkFact d (rmul R r b c) (rmul R r ub uc) (bs ++ cs) _ _ _).
    - apply unit_mul; assumption.
    - intros p Hp. apply in_app_or in Hp. destruct Hp as [Hp | Hp].
      + apply Hbs. exact Hp.
      + apply Hcs. exact Hp.
    - (* Goal: rmul R r b c =
                 rmul R r (rmul R r ub uc) (list_product d (bs ++ cs)) *)
      change (id_r d) with r in Hb_eq, Hc_eq.
      transitivity (rmul R r (rmul R r ub (list_product d bs))
                              (rmul R r uc (list_product d cs))).
      { rewrite <- Hb_eq, <- Hc_eq. reflexivity. }
      transitivity (rmul R r (rmul R r ub uc)
                              (rmul R r (list_product d bs) (list_product d cs))).
      { (* (ub*lp_bs)*(uc*lp_cs) = (ub*uc)*(lp_bs*lp_cs) *)
        rewrite <- (rmul_assoc R r ub (list_product d bs)
                                     (rmul R r uc (list_product d cs))).
        rewrite (rmul_assoc R r (list_product d bs) uc (list_product d cs)).
        rewrite (comm (list_product d bs) uc).
        rewrite <- (rmul_assoc R r uc (list_product d bs) (list_product d cs)).
        rewrite (rmul_assoc R r ub uc
                                (rmul R r (list_product d bs) (list_product d cs))).
        reflexivity. }
      change r with (id_r d). f_equal. symmetry. exact (list_product_app d bs cs).
  Defined.

  (** Bare existence of a factorization (a [Prop], unlike the [Type]-valued
      [Factorization] record). *)
  Definition exists_factorization (a : R) : Prop :=
    exists _ : Factorization d a, True.

  (** Predicate: "[a] is a nonzero non-unit lacking any factorization". *)
  Definition no_factorization (a : R) : Prop :=
    a <> rzero R r /\
    ~ is_unit r a /\
    ~ exists_factorization a.

  (** Step lemma: any element lacking a factorization splits as [b * c]
      with [b], [c] both non-zero non-units, and at least one of them
      also lacks a factorization. *)
  Lemma no_factorization_split (a : R) :
      no_factorization a ->
      exists b c : R,
        a = rmul R r b c /\
        b <> rzero R r /\ c <> rzero R r /\
        ~ is_unit r b /\ ~ is_unit r c /\
        (no_factorization b \/ no_factorization c).
  Proof.
    intros [Ha0 [Hau Hnf]].
    (* a is not irreducible (else we'd have a factorization). *)
    assert (Hairr : ~ is_irreducible d a).
    { intro Hirr. apply Hnf. exists (irreducible_has_factorization a Hirr).
      exact I. }
    (* Negation of irreducible — given a ≠ 0 and ~unit a, the third clause
       must fail: there exist b, c with b*c = a and neither is a unit. *)
    assert (Hsplit : exists b c : R,
                rmul R r b c = a /\ ~ is_unit r b /\ ~ is_unit r c).
    { apply NNPP. intro Hno.
      apply Hairr. unfold is_irreducible.
      split; [exact Ha0 | split; [exact Hau |]].
      intros b c Hbc.
      apply NNPP. intro Hncase.
      assert (Hub : ~ is_unit r b) by tauto.
      assert (Huc : ~ is_unit r c) by tauto.
      apply Hno. exists b, c. tauto. }
    destruct Hsplit as [b [c [Hbc [Hub Huc]]]].
    (* b and c are both nonzero (else a = 0). *)
    assert (Hb0 : b <> rzero R r).
    { intro Hb0. rewrite Hb0, rmul_zero_l in Hbc. exact (Ha0 (eq_sym Hbc)). }
    assert (Hc0 : c <> rzero R r).
    { intro Hc0. rewrite Hc0, rmul_zero_r in Hbc. exact (Ha0 (eq_sym Hbc)). }
    exists b, c.
    repeat split; try assumption.
    - exact (eq_sym Hbc).
    - (* At least one of b, c lacks a factorization, else combine. *)
      apply NNPP. intro Hboth.
      (* From ~(no_fact b \/ no_fact c), get exists_factorization b and c. *)
      assert (Hbf_ex : exists_factorization b).
      { apply NNPP. intro Hbn.
        apply Hboth. left.
        unfold no_factorization. tauto. }
      assert (Hcf_ex : exists_factorization c).
      { apply NNPP. intro Hcn.
        apply Hboth. right.
        unfold no_factorization. tauto. }
      destruct Hbf_ex as [Fb _].
      destruct Hcf_ex as [Fc _].
      apply Hnf. exists (eq_rect _ (Factorization d) (factorization_product b c Fb Fc) _ Hbc).
      exact I.
  Qed.

  (** Step lemma: every element lacking a factorization has a strict proper
      divisor that also lacks a factorization. *)
  Lemma no_factorization_proper_divisor (a : R) :
      no_factorization a ->
      exists b : R,
        no_factorization b /\
        divides r b a /\
        ~ is_associate d a b.
  Proof.
    intros Ha.
    pose proof Ha as [Ha0 [Hau Hnf]].
    destruct (no_factorization_split a Ha) as
      [b [c [Hbc [Hb0 [Hc0 [Hub [Huc [Hnfb | Hnfc]]]]]]]].
    - (* b lacks a factorization. *)
      exists b. split; [exact Hnfb |].
      split.
      + (* b | a: a = b*c. *)
        exists c. exact Hbc.
      + (* a not associate to b: would force c to be a unit. *)
        intros [u [Hu Hb_eq]].
        change (id_r d) with r in Hb_eq.
        (* b = u * a; combined with a = b*c gives a = (u*a)*c, so a*1 = a*(u*c). *)
        assert (Heq : rmul R r a (rone R r) = rmul R r a (rmul R r u c)).
        { rewrite rmul_one_r.
          rewrite Hbc at 1.
          rewrite Hb_eq.
          (* Goal: (u*a)*c = a*(u*c) *)
          rewrite (comm u a).
          (* Goal: (a*u)*c = a*(u*c) *)
          symmetry. apply (rmul_assoc R r a u c). }
        apply (id_mul_cancel d a (rone R r) (rmul R r u c) Ha0) in Heq.
        (* So 1 = u*c, hence c is a unit. *)
        apply Huc. unfold is_unit. exists u.
        split.
        * rewrite (comm c u). exact (eq_sym Heq).
        * exact (eq_sym Heq).
    - (* c lacks a factorization. Symmetric: a = c*b via comm. *)
      exists c. split; [exact Hnfc |].
      split.
      + exists b. rewrite Hbc. apply comm.
      + intros [u [Hu Hc_eq]].
        change (id_r d) with r in Hc_eq.
        assert (Heq : rmul R r a (rone R r) = rmul R r a (rmul R r u b)).
        { rewrite rmul_one_r.
          rewrite Hbc at 1.
          rewrite Hc_eq.
          (* Goal: b * (u*a) = a * (u*b) *)
          rewrite (comm b (rmul R r u a)).
          (* Goal: (u*a)*b = a*(u*b) *)
          rewrite (comm u a).
          (* Goal: (a*u)*b = a*(u*b) *)
          symmetry. apply (rmul_assoc R r a u b). }
        apply (id_mul_cancel d a (rone R r) (rmul R r u b) Ha0) in Heq.
        apply Hub. unfold is_unit. exists u.
        split.
        * rewrite (comm b u). exact (eq_sym Heq).
        * exact (eq_sym Heq).
  Qed.

  (** Given a nofact element, classical EM lets us pick the proper-divisor
      witness as a [sig].  This is exactly the input format for
      [Stdlib.Init.Specif.dependent_choice]. *)
  Definition step_to_proper_divisor (a : { x : R | no_factorization x }) :
      { b : { x : R | no_factorization x } |
          divides r (proj1_sig b) (proj1_sig a) /\
          ~ is_associate d (proj1_sig a) (proj1_sig b) }.
  Proof.
    destruct a as [a Ha].
    pose (Hex := no_factorization_proper_divisor a Ha).
    apply constructive_indefinite_description in Hex.
    destruct Hex as [b [Hnfb [Hdiv Hnassoc]]].
    refine (exist _ (exist _ b Hnfb) _).
    simpl. split; [exact Hdiv | exact Hnassoc].
  Defined.

  (** Existence of factorization in a PID. *)
  Theorem pid_factorization_exists :
      is_pid ->
      forall a : R, has_factorization d a.
  Proof.
    intros Hpid a Ha0 Hau.
    (* Suppose for contradiction no factorization exists for a. *)
    apply NNPP. intro Hno.
    assert (Ha_nf : no_factorization a).
    { unfold no_factorization. split; [exact Ha0 |].
      split; [exact Hau |].
      intros [F _]. apply Hno. exists F. exact I. }
    (* Extract a sequence of strictly descending divisors with no factorization. *)
    pose (a0 := exist no_factorization a Ha_nf).
    destruct (dependent_choice step_to_proper_divisor a0)
      as [f [Hf0 Hfstep]].
    (* Define the principal-ideal chain: I n := principal_ideal (proj1_sig (f n)). *)
    pose (Iseq := fun n => principal_ideal (proj1_sig (f n))).
    assert (HIseq_id : forall n, is_ideal r (Iseq n)).
    { intro n. apply principal_ideal_is_ideal. }
    assert (HIseq_chain : forall n x, Iseq n x -> Iseq (S n) x).
    { intros n x Hx.
      pose proof (Hfstep n) as [Hdiv Hnassoc].
      destruct Hx as [c Hc].
      destruct Hdiv as [e He].
      (* He : proj1_sig (f n) = rmul R r (proj1_sig (f (S n))) e
         Hc : x                = rmul R r c (proj1_sig (f n))
         Want: exists c', x = rmul R r c' (proj1_sig (f (S n)))  *)
      exists (rmul R r c e).
      (* Goal: x = rmul R r (rmul R r c e) (proj1_sig (f (S n))) *)
      rewrite Hc, He.
      (* Goal: c*(p*e) = (c*e)*p *)
      rewrite (rmul_assoc R r c (proj1_sig (f (S n))) e).
      (* Goal: (c*p)*e = (c*e)*p *)
      rewrite <- (rmul_assoc R r c e (proj1_sig (f (S n)))).
      (* Goal: (c*p)*e = c*(e*p) *)
      rewrite (comm e (proj1_sig (f (S n)))).
      (* Goal: (c*p)*e = c*(p*e) *)
      symmetry. apply (rmul_assoc R r c (proj1_sig (f (S n))) e). }
    destruct (pid_ascending_chain_stabilizes Hpid Iseq HIseq_id HIseq_chain)
      as [N HN].
    (* The chain stabilizes at N.  But by the strict-divisor property,
       the principal ideal at S N strictly contains the one at N. *)
    pose proof (Hfstep N) as [HdivN HnassocN].
    (* HdivN : divides r (proj1_sig (f (S N))) (proj1_sig (f N)) — so
       proj1_sig (f (S N)) is in I (S N) trivially. *)
    pose proof (HN (S N) (le_S _ _ (le_n N)) (proj1_sig (f (S N)))) as Hstab.
    assert (HinSN : Iseq (S N) (proj1_sig (f (S N)))).
    { unfold Iseq, principal_ideal. exists (rone R r).
      symmetry. apply rmul_one_l. }
    apply (proj1 Hstab) in HinSN.
    (* HinSN : Iseq N (proj1_sig (f (S N))), i.e., proj1_sig (f N) divides
       proj1_sig (f (S N)) (after using the divides_iff_ideal_subset framing). *)
    destruct HinSN as [c Hc].
    (* Hc : proj1_sig (f (S N)) = c * proj1_sig (f N).  Combined with the
       opposite divisibility (proj1_sig (f (S N)) | proj1_sig (f N)) we get
       associatedness. *)
    destruct HdivN as [e He].
    (* He : proj1_sig (f N) = proj1_sig (f (S N)) * e *)
    (* Substitute Hc into He:
       proj1_sig (f N) = (c * proj1_sig (f N)) * e
                       = (proj1_sig (f N) * c) * e (comm)
                       = proj1_sig (f N) * (c * e). *)
    apply HnassocN.
    (* Need: is_associate d (proj1_sig (f N)) (proj1_sig (f (S N))). *)
    (* From above, c*e = 1 by cancellation (using f N nonzero). *)
    pose proof (proj2_sig (f N)) as HfN_nf.
    destruct HfN_nf as [HfN_ne _].
    assert (Hce_one : rmul R r c e = rone R r).
    { apply (id_mul_cancel d (proj1_sig (f N))
                              (rmul R r c e) (rone R r) HfN_ne).
      change (id_r d) with r.
      rewrite rmul_one_r.
      (* Goal: p_N * (c*e) = p_N
         Compute: p_N * (c*e) = (p_N*c)*e = (c*p_N)*e = p_(S N) * e = p_N *)
      rewrite (rmul_assoc R r (proj1_sig (f N)) c e).
      rewrite (comm (proj1_sig (f N)) c).
      rewrite <- Hc.
      symmetry. exact He. }
    (* So c is a unit (with inverse e), and proj1_sig (f (S N)) = c * proj1_sig (f N).
       Thus proj1_sig (f N) is associate to proj1_sig (f (S N)) via c. *)
    unfold is_associate. exists c.
    split.
    - unfold is_unit. exists e. split.
      + change (id_r d) with r. exact Hce_one.
      + change (id_r d) with r. rewrite (comm e c). exact Hce_one.
    - exact Hc.
  Qed.

  (* ================================================================== *)
  (** ** Uniqueness of factorization (PID)                              *)
  (*                                                                    *)
  (** Strategy: Bezout (every PID is a Bezout domain) gives             *)
  (** [irreducible ⇒ prime].  Then standard cancellation/permutation    *)
  (** induction on factor lists.                                        *)
  (* ================================================================== *)

  (** The two-generated ideal [{ s*p + t*a | s,t ∈ R }]. *)
  Definition bezout_ideal (p a : R) : R -> Prop :=
    fun x => exists s t : R, x = radd R r (rmul R r s p) (rmul R r t a).

  (** [bezout_ideal p a] is a (two-sided) ideal. *)
  Lemma bezout_ideal_is_ideal : forall p a : R,
      is_ideal r (bezout_ideal p a).
  Proof.
    intros p a. unfold is_ideal, is_left_ideal, is_right_ideal,
                       is_add_subgroup, bezout_ideal.
    split; split; try split; try split.
    - (* 0 ∈ bezout: 0 = 0*p + 0*a *)
      exists (rzero R r), (rzero R r).
      rewrite !rmul_zero_l. symmetry. apply radd_zero_r.
    - (* closed under add *)
      intros x y [s1 [t1 Hx]] [s2 [t2 Hy]].
      exists (radd R r s1 s2), (radd R r t1 t2).
      rewrite Hx, Hy.
      (* (s1*p + t1*a) + (s2*p + t2*a) = (s1+s2)*p + (t1+t2)*a *)
      rewrite (rmul_distrib_r R r s1 s2 p).
      rewrite (rmul_distrib_r R r t1 t2 a).
      (* Goal: (s1*p + s2*p) + (t1*a + t2*a) needs reshuffle to
                  (s1*p + t1*a) + (s2*p + t2*a). *)
      symmetry.
      rewrite <- (radd_assoc R r (rmul R r s1 p) (rmul R r t1 a)
                                  (radd R r (rmul R r s2 p) (rmul R r t2 a))).
      rewrite (radd_assoc R r (rmul R r t1 a) (rmul R r s2 p) (rmul R r t2 a)).
      rewrite (radd_comm R r (rmul R r t1 a) (rmul R r s2 p)).
      rewrite <- (radd_assoc R r (rmul R r s2 p) (rmul R r t1 a) (rmul R r t2 a)).
      rewrite (radd_assoc R r (rmul R r s1 p) (rmul R r s2 p)
                              (radd R r (rmul R r t1 a) (rmul R r t2 a))).
      reflexivity.
    - (* closed under neg: -(s*p + t*a) = (-s)*p + (-t)*a *)
      intros x [s [t Hx]].
      exists (rneg R r s), (rneg R r t).
      rewrite Hx.
      (* -(s*p + t*a) = (-s)*p + (-t)*a *)
      rewrite (@rmul_neg_l_full R r s p).
      rewrite (@rmul_neg_l_full R r t a).
      rewrite (@rneg_add R r). reflexivity.
    - (* left absorption: y*(s*p + t*a) = (y*s)*p + (y*t)*a *)
      intros y x [s [t Hx]].
      exists (rmul R r y s), (rmul R r y t).
      rewrite Hx.
      rewrite rmul_distrib_l.
      rewrite (rmul_assoc R r y s p).
      rewrite (rmul_assoc R r y t a).
      reflexivity.
    - exists (rzero R r), (rzero R r).
      rewrite !rmul_zero_l. symmetry. apply radd_zero_r.
    - intros x y [s1 [t1 Hx]] [s2 [t2 Hy]].
      exists (radd R r s1 s2), (radd R r t1 t2).
      rewrite Hx, Hy.
      rewrite (rmul_distrib_r R r s1 s2 p).
      rewrite (rmul_distrib_r R r t1 t2 a).
      symmetry.
      rewrite <- (radd_assoc R r (rmul R r s1 p) (rmul R r t1 a)
                                  (radd R r (rmul R r s2 p) (rmul R r t2 a))).
      rewrite (radd_assoc R r (rmul R r t1 a) (rmul R r s2 p) (rmul R r t2 a)).
      rewrite (radd_comm R r (rmul R r t1 a) (rmul R r s2 p)).
      rewrite <- (radd_assoc R r (rmul R r s2 p) (rmul R r t1 a) (rmul R r t2 a)).
      rewrite (radd_assoc R r (rmul R r s1 p) (rmul R r s2 p)
                              (radd R r (rmul R r t1 a) (rmul R r t2 a))).
      reflexivity.
    - intros x [s [t Hx]].
      exists (rneg R r s), (rneg R r t).
      rewrite Hx.
      rewrite (@rmul_neg_l_full R r s p).
      rewrite (@rmul_neg_l_full R r t a).
      rewrite (@rneg_add R r). reflexivity.
    - (* right absorption: (s*p + t*a)*y = (s*y)*p + (t*y)*a using comm *)
      intros x y [s [t Hx]].
      exists (rmul R r s y), (rmul R r t y).
      rewrite Hx.
      (* (s*p + t*a)*y = (s*p)*y + (t*a)*y = s*(p*y) + t*(a*y)
                     = s*(y*p) + t*(y*a) (comm)
                     = (s*y)*p + (t*y)*a (assoc reverse) *)
      rewrite rmul_distrib_r.
      rewrite <- (rmul_assoc R r s p y).
      rewrite (comm p y).
      rewrite (rmul_assoc R r s y p).
      rewrite <- (rmul_assoc R r t a y).
      rewrite (comm a y).
      rewrite (rmul_assoc R r t y a).
      reflexivity.
  Qed.

  (** Bezout: in a PID, the ideal [(p, a)] has a single generator. *)
  Lemma pid_bezout : is_pid -> forall p a : R,
      exists g : R,
        divides r g p /\
        divides r g a /\
        exists s t : R, g = radd R r (rmul R r s p) (rmul R r t a).
  Proof.
    intros Hpid p a.
    destruct (Hpid (bezout_ideal p a) (bezout_ideal_is_ideal p a)) as [g Hg].
    exists g.
    (* g | p: p ∈ bezout (1*p + 0*a), so p ∈ (g). *)
    assert (Hp_in : bezout_ideal p a p).
    { exists (rone R r), (rzero R r).
      rewrite rmul_one_l, rmul_zero_l. symmetry. apply radd_zero_r. }
    apply Hg in Hp_in. destruct Hp_in as [k Hk].
    (* p = k*g, so g | p. *)
    assert (Hgp : divides r g p).
    { exists k. rewrite Hk. apply comm. }
    (* g | a similarly. *)
    assert (Ha_in : bezout_ideal p a a).
    { exists (rzero R r), (rone R r).
      rewrite rmul_zero_l, rmul_one_l. symmetry. apply radd_zero_l. }
    apply Hg in Ha_in. destruct Ha_in as [m Hm].
    assert (Hga : divides r g a).
    { exists m. rewrite Hm. apply comm. }
    split; [exact Hgp | split; [exact Hga |]].
    (* g ∈ bezout p a: g = principal_ideal g g (with c = 1). *)
    assert (Hg_in : principal_ideal g g).
    { exists (rone R r). symmetry. apply rmul_one_l. }
    apply (proj2 (Hg g)) in Hg_in.
    destruct Hg_in as [s [t Hg_eq]].
    exists s, t. exact Hg_eq.
  Qed.

  (** In a PID, irreducible elements are prime — the key step toward
      unique factorization, proved via Bezout (no ACC required). *)
  Theorem pid_irreducible_is_prime :
      is_pid -> forall p : R, is_irreducible d p -> is_prime d p.
  Proof.
    intros Hpid p [Hp0 [Hpu Hpirr]].
    split; [exact Hp0 | split; [exact Hpu |]].
    intros a b Hpab.
    (* Case on whether p divides a. *)
    destruct (classic (divides r p a)) as [Hpa | Hnpa].
    { left. exact Hpa. }
    (* p does not divide a.  By Bezout, gcd(p, a) = g where g | p, g | a,
       and g = s*p + t*a for some s, t. *)
    right.
    destruct (pid_bezout Hpid p a) as [g [Hgp [Hga [s [t Hg_eq]]]]].
    (* Since g | p and p irreducible, either g is unit or g is associate to p.
       But if g ~ p, then p | g | a — contradicting Hnpa.  Hence g is a unit. *)
    assert (Hg_unit : is_unit r g).
    { destruct Hgp as [k Hk].
      (* p = g*k.  Irreducibility: g unit or k unit. *)
      assert (Hcase : is_unit r g \/ is_unit r k).
      { apply Hpirr. exact (eq_sym Hk). }
      destruct Hcase as [Hgu | Hku]; [exact Hgu |].
      (* k is unit ⇒ g and p are associates ⇒ p | a. *)
      exfalso. apply Hnpa.
      (* g ~ p, g | a, so p | a. *)
      assert (Hassoc : is_associate d g p).
      { unfold is_associate. exists k.
        split; [change r with (id_r d); exact Hku |].
        change (id_r d) with r. rewrite Hk. apply comm. }
      apply (proj1 (associate_divides_iff d g p a Hassoc)). exact Hga. }
    (* g is a unit, so 1 = g_inv * g = g_inv * (s*p + t*a). *)
    destruct Hg_unit as [ginv [Hginv1 Hginv2]].
    (* Hginv1 : g * ginv = 1. *)
    (* Want: p | b.  Hpab : exists c, a*b = p*c. *)
    destruct Hpab as [c Hc].
    change (id_r d) with r in Hc.
    (* From g = s*p + t*a, multiply both sides by ginv*b:
       ginv*b*g = ginv*b*(s*p + t*a) = ginv*(b*s)*p + ginv*b*t*a
                                     = ginv*(b*s)*p + ginv*t*(a*b)
                                     = ginv*(b*s)*p + ginv*t*(p*c)
                                     = ginv*(b*s + t*c)*p. [star]
       And ginv*b*g = ginv*g*b = 1*b = b.
       So b = ginv*(b*s + t*c)*p — which gives p | b. *)
    exists (rmul R r ginv (radd R r (rmul R r b s) (rmul R r t c))).
    (* Goal: b = p * (ginv * (b*s + t*c))
       Strategy: massage by direct equation chains. *)
    transitivity (rmul R r (rmul R r ginv g) b).
    { rewrite Hginv2, rmul_one_l. reflexivity. }
    (* Goal: ginv*g*b = p * (ginv * (b*s + t*c)) *)
    rewrite Hg_eq.
    (* Goal: ginv*(s*p + t*a)*b = p * (ginv * (b*s + t*c)) *)
    (* Reduce LHS:
       ginv*(s*p + t*a)*b
         = ginv*((s*p + t*a)*b)               [rmul_assoc reverse]
         = ginv*((s*p)*b + (t*a)*b)           [rmul_distrib_r]
         = ginv*(s*(p*b) + t*(a*b))           [rmul_assoc reverse twice]
         = ginv*(s*(p*b) + t*(p*c))           [Hc]
         = ginv*(s*(b*p) + t*(p*c))           [comm p b]
         = ginv*((s*b)*p + (t*p)*c)           [rmul_assoc forward twice]
         = ginv*((b*s)*p + (p*t)*c)           [comm s b, comm t p]
         = ginv*(p*(b*s) + p*(t*c))           [comm + assoc reverse: each summand]
         Hmm — let me redo: (b*s)*p = p*(b*s) [comm], (p*t)*c = p*(t*c) [assoc reverse].
         = ginv*p*(b*s + t*c)                  [rmul_distrib_l]
         = p*ginv*(b*s + t*c)                  [comm ginv p]
         = p*(ginv*(b*s + t*c))                [assoc reverse]
       Each step is one rewrite. *)
    rewrite <- (rmul_assoc R r ginv (radd R r (rmul R r s p) (rmul R r t a)) b).
    (* Goal: ginv*((s*p + t*a)*b) = ... *)
    rewrite (rmul_distrib_r R r (rmul R r s p) (rmul R r t a) b).
    (* Goal: ginv*((s*p)*b + (t*a)*b) = ... *)
    rewrite <- (rmul_assoc R r s p b).
    rewrite <- (rmul_assoc R r t a b).
    rewrite Hc.
    (* Goal: ginv*(s*(p*b) + t*(p*c)) = ... *)
    rewrite (comm p b).
    (* Goal: ginv*(s*(b*p) + t*(p*c)) = ... *)
    rewrite (rmul_assoc R r s b p).
    rewrite (rmul_assoc R r t p c).
    (* Goal: ginv*((s*b)*p + (t*p)*c) = ... *)
    rewrite (comm s b).
    rewrite (comm t p).
    (* Goal: ginv*((b*s)*p + (p*t)*c) = ... *)
    rewrite (comm (rmul R r b s) p).
    rewrite <- (rmul_assoc R r p t c).
    (* Goal: ginv*(p*(b*s) + p*(t*c)) = ... *)
    rewrite <- (rmul_distrib_l R r p (rmul R r b s) (rmul R r t c)).
    (* Goal: ginv*(p*(b*s + t*c)) = p*(ginv*(b*s + t*c)) *)
    rewrite (rmul_assoc R r ginv p (radd R r (rmul R r b s) (rmul R r t c))).
    rewrite (comm ginv p).
    symmetry. apply (rmul_assoc R r p ginv
                                (radd R r (rmul R r b s) (rmul R r t c))).
  Qed.

  (** Cancellation through a unit on the left. *)
  Lemma cancel_unit_l : forall (u a b : R),
      is_unit r u ->
      rmul R r u a = rmul R r u b ->
      a = b.
  Proof.
    intros u a b [uinv [Hur Hul]] Heq.
    change (id_r d) with r in Hur, Hul.
    apply (id_mul_cancel d u a b).
    - intro Hu0. apply (id_nontrivial d).
      change (id_r d) with r.
      rewrite <- Hur, Hu0. apply rmul_zero_l.
    - exact Heq.
  Qed.

  (** Permutation lemma: if p is associate to one of qs, then [qs] permutes
      to [q :: qs'] for some [q ∈ qs] associate to [p]. *)
  Lemma permute_associate :
    forall (p : R) (qs : list R),
      (forall q, In q qs -> is_irreducible d q) ->
      (exists q, In q qs /\ is_associate d p q) ->
      exists q qs', Permutation qs (q :: qs') /\ is_associate d p q.
  Proof.
    intros p qs Hqsirr [q [Hq_in Hassoc]].
    apply in_split in Hq_in. destruct Hq_in as [l1 [l2 Hqs]].
    exists q, (l1 ++ l2). split.
    - rewrite Hqs.
      symmetry. apply Permutation_middle.
    - exact Hassoc.
  Qed.

  (** Helper: prime divides product of irreducibles ⇒ associate to one. *)
  Lemma prime_divides_irr_product :
    forall (p : R) (qs : list R),
      is_prime d p ->
      (forall q, In q qs -> is_irreducible d q) ->
      divides r p (list_product d qs) ->
      exists q, In q qs /\ is_associate d p q.
  Proof.
    intros p qs Hpp.
    induction qs as [| q rest IH]; intros Hqsirr Hdiv.
    - simpl in Hdiv.
      exfalso.
      destruct Hpp as [_ [Hpu _]]. apply Hpu.
      apply (proj2 (unit_iff_divides_one r comm p)). exact Hdiv.
    - simpl in Hdiv.
      pose proof Hpp as [Hp0 [Hpu Hprime]].
      destruct (Hprime q (list_product d rest) Hdiv) as [Hpq | Hprest].
      + exists q. split; [left; reflexivity |].
        assert (Hpirr : is_irreducible d p)
          by (apply prime_irreducible; exact Hpp).
        assert (Hqirr : is_irreducible d q)
          by (apply Hqsirr; left; reflexivity).
        apply (irreducible_dvd_implies_associate d p q Hpirr Hqirr Hpq).
      + assert (Hrest_irr : forall q', In q' rest -> is_irreducible d q').
        { intros q' Hq'. apply Hqsirr. right. exact Hq'. }
        destruct (IH Hrest_irr Hprest) as [q' [Hq'_in Hq'_assoc]].
        exists q'. split; [right; exact Hq'_in | exact Hq'_assoc].
  Qed.

  (** [list_product] is invariant under permutations (using commutativity). *)
  Lemma list_product_perm : forall ps qs : list R,
      Permutation ps qs -> list_product d ps = list_product d qs.
  Proof.
    intros ps qs Hperm.
    induction Hperm as [| x ps qs Hperm IH | x y ps | ps qs rs Hperm1 IH1 Hperm2 IH2].
    - reflexivity.
    - simpl. rewrite IH. reflexivity.
    - (* swap case: list_product d (y :: x :: ps) = list_product d (x :: y :: ps).
         After simpl: y * (x * Lp ps) = x * (y * Lp ps). *)
      simpl list_product.
      change (id_r d) with r.
      transitivity (rmul R r (rmul R r y x) (list_product d ps)).
      { exact (rmul_assoc R r y x (list_product d ps)). }
      transitivity (rmul R r (rmul R r x y) (list_product d ps)).
      { rewrite (comm y x). reflexivity. }
      exact (eq_sym (rmul_assoc R r x y (list_product d ps))).
    - rewrite IH1, IH2. reflexivity.
  Qed.

  (** Irreducibles do not divide units. *)
  Lemma irr_not_divides_unit : forall p u : R,
      is_irreducible d p -> is_unit r u -> ~ divides r p u.
  Proof.
    intros p u Hpirr Hu Hdiv.
    destruct Hpirr as [_ [Hpu _]].
    apply Hpu.
    apply (proj2 (unit_iff_divides_one r comm p)).
    destruct Hu as [uinv [Hur Hul]].
    destruct Hdiv as [c Hc].
    (* u = p * c, so 1 = u * uinv = (p*c)*uinv = p*(c*uinv).  *)
    exists (rmul R r c uinv).
    rewrite <- Hur, Hc.
    symmetry. apply (rmul_assoc R r p c uinv).
  Qed.

  (** Adjustment function used to translate an index in [qs1 ++ qs2]
      to the corresponding index in [qs1 ++ q :: qs2]. *)
  Definition adjust_idx (k j : nat) : nat :=
    if Nat.ltb j k then j else S j.

  (** Adjusted-index lookup matches the unsplit lookup. *)
  Lemma nth_adjust_idx :
    forall (qs1 qs2 : list R) (q : R) (j : nat),
      nth (adjust_idx (length qs1) j) (qs1 ++ q :: qs2) (rzero R r) =
      nth j (qs1 ++ qs2) (rzero R r).
  Proof.
    intros qs1 qs2 q j.
    unfold adjust_idx.
    destruct (Nat.ltb_spec j (length qs1)) as [Hlt | Hge].
    - (* j < length qs1: both lookups land in qs1. *)
      rewrite app_nth1 by exact Hlt.
      rewrite app_nth1 by exact Hlt.
      reflexivity.
    - (* j >= length qs1. *)
      rewrite app_nth2 by lia.
      rewrite app_nth2 by exact Hge.
      (* LHS: nth (S j - length qs1) (q :: qs2) = nth (j - length qs1) qs2 *)
      destruct (j - length qs1) eqn:Ediff.
      + (* j = length qs1, so S j - length qs1 = 1, S 0 = 1 *)
        replace (S j - length qs1) with 1 by lia.
        reflexivity.
      + replace (S j - length qs1) with (S (S n)) by lia.
        reflexivity.
  Qed.

  (** Adjustment maps [seq 0 n] to [seq 0 k ++ seq (S k) (n - k)] when [k <= n]. *)
  Lemma map_adjust_seq :
    forall n k : nat,
      k <= n ->
      map (adjust_idx k) (seq 0 n) = seq 0 k ++ seq (S k) (n - k).
  Proof.
    intros n k Hkn.
    apply nth_ext with (d := 0) (d' := 0).
    - rewrite map_length, seq_length, app_length, !seq_length. lia.
    - rewrite map_length, seq_length.
      intros i Hi.
      (* Switch the default of the LHS map-lookup to (adjust_idx k 0). *)
      rewrite (nth_indep _ 0 (adjust_idx k 0))
        by (rewrite map_length, seq_length; exact Hi).
      rewrite map_nth.
      rewrite seq_nth by exact Hi.
      simpl plus.
      unfold adjust_idx.
      destruct (Nat.ltb_spec i k) as [Hlt | Hge].
      + rewrite app_nth1 by (rewrite seq_length; exact Hlt).
        rewrite seq_nth by exact Hlt. reflexivity.
      + rewrite app_nth2 by (rewrite seq_length; exact Hge).
        rewrite seq_length.
        rewrite seq_nth by lia.
        lia.
  Qed.

  (** A symmetric/strengthened cancellation lemma: from
      [u1 * ∏ps = u2 * ∏qs] with both lists of irreducibles and both units,
      construct a permutation [sigma] matching [ps] to [qs] up to associates. *)
  Lemma factorization_unique_helper :
    is_pid ->
    forall (ps qs : list R) (u1 u2 : R),
      is_unit r u1 -> is_unit r u2 ->
      (forall p, In p ps -> is_irreducible d p) ->
      (forall q, In q qs -> is_irreducible d q) ->
      rmul R r u1 (list_product d ps) = rmul R r u2 (list_product d qs) ->
      exists sigma : list nat,
        Permutation sigma (seq 0 (length ps)) /\
        length sigma = length qs /\
        forall i j : nat,
          nth_error sigma i = Some j ->
          is_associate d
            (nth i ps (rzero R r))
            (nth j qs (rzero R r)).
  Proof.
    intros Hpid ps.
    induction ps as [| p ps' IH]; intros qs u1 u2 Hu1 Hu2 Hpsirr Hqsirr Heq.
    - (* Base case: ps = []. *)
      simpl in Heq.
      rewrite rmul_one_r in Heq.
      (* Heq: u1 = u2 * ∏qs.  Show qs = []. *)
      destruct qs as [| q rest].
      + exists []. simpl. split; [apply perm_nil | split; [reflexivity |]].
        intros i j H. destruct i; simpl in H; discriminate.
      + (* qs nonempty: q | u1 (since u1 = u2 * ∏(q::rest) and q ∈ rest). *)
        exfalso.
        assert (Hqirr : is_irreducible d q) by (apply Hqsirr; left; reflexivity).
        assert (Hq_div_u1 : divides r q u1).
        { exists (rmul R r u2 (list_product d rest)).
          rewrite Heq. simpl.
          change (id_r d) with r.
          (* u2 * (q * ∏rest) = q * (u2 * ∏rest) *)
          rewrite (rmul_assoc R r u2 q (list_product d rest)).
          rewrite (comm u2 q).
          rewrite <- (rmul_assoc R r q u2 (list_product d rest)).
          reflexivity. }
        exact (irr_not_divides_unit q u1 Hqirr Hu1 Hq_div_u1).
    - (* Inductive step: ps = p :: ps'. *)
      assert (Hpirr : is_irreducible d p) by (apply Hpsirr; left; reflexivity).
      assert (Hps'irr : forall x, In x ps' -> is_irreducible d x)
        by (intros x Hx; apply Hpsirr; right; exact Hx).
      (* p is prime in PID. *)
      assert (Hpprime : is_prime d p)
        by (apply pid_irreducible_is_prime; assumption).
      (* p divides u2 * ∏qs (since u1 * (p * ∏ps') = u2 * ∏qs). *)
      assert (Hp_div_rhs : divides r p (rmul R r u2 (list_product d qs))).
      { exists (rmul R r u1 (list_product d ps')).
        rewrite <- Heq. simpl.
        change (id_r d) with r.
        (* u1 * (p * ∏ps') = p * (u1 * ∏ps') *)
        rewrite (rmul_assoc R r u1 p (list_product d ps')).
        rewrite (comm u1 p).
        rewrite <- (rmul_assoc R r p u1 (list_product d ps')).
        reflexivity. }
      (* p doesn't divide u2; hence p divides ∏qs. *)
      assert (Hp_div_qs : divides r p (list_product d qs)).
      { (* Apply primality to u2 * ∏qs.  Either p | u2 or p | ∏qs. *)
        destruct Hpprime as [_ [_ Hpd]].
        destruct (Hpd u2 (list_product d qs) Hp_div_rhs) as [Hpu | Hpqs].
        - exfalso.
          exact (irr_not_divides_unit p u2 Hpirr Hu2 Hpu).
        - exact Hpqs. }
      (* Find q in qs with p ~ q. *)
      destruct (prime_divides_irr_product p qs Hpprime Hqsirr Hp_div_qs)
        as [q [Hq_in Hpq_assoc]].
      apply in_split in Hq_in.
      destruct Hq_in as [qs1 [qs2 Hqs_split]].
      (* qs = qs1 ++ q :: qs2. *)
      (* Use the permutation qs ~ q :: qs1 ++ qs2 to compute ∏qs = q * ∏(qs1++qs2). *)
      assert (Hperm : Permutation qs (q :: qs1 ++ qs2)).
      { rewrite Hqs_split. symmetry. apply Permutation_middle. }
      assert (Hlp_qs : list_product d qs =
                      rmul R r q (list_product d (qs1 ++ qs2))).
      { rewrite (list_product_perm qs (q :: qs1 ++ qs2) Hperm).
        simpl. reflexivity. }
      (* p ~ q means q = u_pq * p for some unit u_pq. *)
      destruct Hpq_assoc as [u_pq [Hu_pq Hq_eq]].
      change (id_r d) with r in Hu_pq, Hq_eq.
      (* Now derive the cancelled equation: u1 * ∏ps' = (u2 * u_pq) * ∏(qs1++qs2). *)
      assert (Hcancel : rmul R r u1 (list_product d ps') =
                       rmul R r (rmul R r u2 u_pq) (list_product d (qs1 ++ qs2))).
      { (* Start from Heq. *)
        (* Heq: u1 * ∏(p :: ps') = u2 * ∏qs *)
        simpl list_product in Heq.
        change (id_r d) with r in Heq.
        (* Heq: u1 * (p * ∏ps') = u2 * ∏qs *)
        rewrite Hlp_qs in Heq.
        (* Heq: u1 * (p * ∏ps') = u2 * (q * ∏rest) where rest = qs1++qs2 *)
        rewrite Hq_eq in Heq.
        (* Heq: u1 * (p * ∏ps') = u2 * ((u_pq * p) * ∏rest) *)
        (* Reshuffle LHS to p * (u1 * ∏ps'). *)
        assert (HLHS : rmul R r u1 (rmul R r p (list_product d ps'))
                    = rmul R r p (rmul R r u1 (list_product d ps'))).
        { rewrite (rmul_assoc R r u1 p (list_product d ps')).
          rewrite (comm u1 p).
          rewrite <- (rmul_assoc R r p u1 (list_product d ps')).
          reflexivity. }
        rewrite HLHS in Heq. clear HLHS.
        (* Reshuffle RHS to p * ((u2*u_pq) * ∏rest). *)
        assert (HRHS : rmul R r u2 (rmul R r (rmul R r u_pq p) (list_product d (qs1 ++ qs2)))
                    = rmul R r p (rmul R r (rmul R r u2 u_pq) (list_product d (qs1 ++ qs2)))).
        { (* u2 * ((u_pq*p) * Z) = (u2 * (u_pq*p)) * Z = ((u2*u_pq)*p) * Z
                                = (p*(u2*u_pq)) * Z = p * ((u2*u_pq)*Z) *)
          rewrite (rmul_assoc R r u2 (rmul R r u_pq p) (list_product d (qs1 ++ qs2))).
          rewrite (rmul_assoc R r u2 u_pq p).
          rewrite (comm (rmul R r u2 u_pq) p).
          rewrite <- (rmul_assoc R r p (rmul R r u2 u_pq) (list_product d (qs1 ++ qs2))).
          reflexivity. }
        rewrite HRHS in Heq. clear HRHS.
        (* Heq: p * (u1 * ∏ps') = p * ((u2*u_pq) * ∏rest).  Cancel p. *)
        assert (Hp_ne : p <> rzero R r)
          by (destruct Hpirr as [Hp0 _]; exact Hp0).
        apply (id_mul_cancel d p _ _ Hp_ne) in Heq.
        change (id_r d) with r in Heq.
        exact Heq. }
      (* Apply IH to (ps', qs1 ++ qs2). *)
      assert (Hu2u_pq : is_unit r (rmul R r u2 u_pq)) by (apply unit_mul; assumption).
      assert (Hqs12_irr : forall x, In x (qs1 ++ qs2) -> is_irreducible d x).
      { intros x Hx. apply Hqsirr.
        rewrite Hqs_split. apply in_app_or in Hx. apply in_or_app.
        destruct Hx as [Hx | Hx]; [left; exact Hx | right; right; exact Hx]. }
      destruct (IH (qs1 ++ qs2) u1 (rmul R r u2 u_pq) Hu1 Hu2u_pq
                   Hps'irr Hqs12_irr Hcancel) as [sigma' [Hperm' [Hlen' Hsig']]].
      (* Construct sigma = (length qs1) :: map (adjust_idx (length qs1)) sigma'. *)
      set (k := length qs1).
      exists (k :: map (adjust_idx k) sigma').
      split; [| split].
      + (* Permutation. *)
        assert (Hkle : k <= length ps').
        { (* k = length qs1 ≤ length qs1 + length qs2 = length (qs1++qs2) = length ps'. *)
          unfold k. rewrite app_length in Hlen'.
          assert (Hlen_sig : length sigma' = length ps').
          { apply Permutation_length in Hperm'.
            rewrite seq_length in Hperm'. exact Hperm'. }
          lia. }
        (* Permutation (k :: map adjust sigma') (seq 0 (S (length ps'))) *)
        simpl seq.
        (* Goal: Permutation (k :: map adjust sigma') (0 :: seq 1 (length ps')) *)
        (* We use map_adjust_seq to compute map adjust (seq 0 n). *)
        apply Permutation_trans with (l' := k :: map (adjust_idx k) (seq 0 (length ps'))).
        { apply perm_skip. apply Permutation_map. exact Hperm'. }
        rewrite (map_adjust_seq (length ps') k Hkle).
        (* Goal: Permutation (k :: seq 0 k ++ seq (S k) (length ps' - k))
                              (0 :: seq 1 (length ps')) *)
        (* Switch to: seq 0 k ++ k :: seq (S k) (length ps' - k) via Permutation_middle. *)
        apply Permutation_trans with
            (l' := seq 0 k ++ k :: seq (S k) (length ps' - k)).
        { apply Permutation_middle. }
        (* Now [seq 0 k ++ k :: seq (S k) (length ps' - k)] = seq 0 (S (length ps')) *)
        replace (k :: seq (S k) (length ps' - k)) with (seq k (S (length ps' - k)))
          by reflexivity.
        rewrite <- seq_app.
        replace (k + S (length ps' - k)) with (S (length ps')) by lia.
        apply Permutation_refl.
      + (* Length. *)
        simpl. rewrite map_length, Hlen'.
        rewrite Hqs_split, !app_length. simpl. lia.
      + (* Lookup property. *)
        intros i j Hlook.
        destruct i as [| i'].
        * (* i = 0: sigma[0] = k = length qs1.  Need (p::ps')[0] ~ qs[k] = q. *)
          simpl in Hlook. inversion Hlook. subst j.
          simpl.
          rewrite Hqs_split.
          (* Goal: is_associate d p (nth (length qs1) (qs1 ++ q :: qs2) (rzero R r)). *)
          rewrite app_nth2 by lia.
          rewrite Nat.sub_diag. simpl.
          (* Goal: is_associate d p q. *)
          unfold is_associate. exists u_pq. split; assumption.
        * (* i = S i'. *)
          simpl in Hlook.
          (* Hlook : nth_error (map (adjust_idx k) sigma') i' = Some j *)
          (* Decompose this using map_nth_error. *)
          assert (exists j', nth_error sigma' i' = Some j' /\ j = adjust_idx k j')
            as [j' [Hsig'_lookup Hj_eq]].
          { destruct (nth_error sigma' i') as [j' | ] eqn:Esig'.
            - exists j'. split; [reflexivity |].
              rewrite (map_nth_error _ i' sigma' Esig') in Hlook.
              inversion Hlook. reflexivity.
            - exfalso.
              rewrite (nth_error_None sigma' i') in Esig'.
              assert (length (map (adjust_idx k) sigma') <= i')
                by (rewrite map_length; exact Esig').
              rewrite <- nth_error_None in H.
              rewrite H in Hlook. discriminate. }
          (* Apply IH lookup to i' and j'. *)
          pose proof (Hsig' i' j' Hsig'_lookup) as Hassoc.
          subst j.
          simpl.
          (* Goal: is_associate d (nth i' ps' _) (nth (adjust_idx k j') qs _) *)
          rewrite Hqs_split.
          unfold k.
          rewrite (nth_adjust_idx qs1 qs2 q j').
          exact Hassoc.
  Qed.

  (** Uniqueness of factorization in a PID. *)
  Theorem pid_factorization_unique :
    forall (Hpid : is_pid),
    forall a : R,
    forall F1 F2 : Factorization d a,
      exists sigma : list nat,
        Permutation sigma (seq 0 (length (fact_irrs d a F1))) /\
        length sigma = length (fact_irrs d a F2) /\
        forall i j : nat,
          nth_error sigma i = Some j ->
          is_associate d
            (nth i (fact_irrs d a F1) (rzero R r))
            (nth j (fact_irrs d a F2) (rzero R r)).
  Proof.
    intros Hpid a F1 F2.
    destruct F1 as [u1 ps Hu1 Hpsirr Heq1].
    destruct F2 as [u2 qs Hu2 Hqsirr Heq2].
    simpl.
    (* Both factorizations equal a, so u1*∏ps = u2*∏qs. *)
    assert (Heq : rmul R r u1 (list_product d ps) =
                  rmul R r u2 (list_product d qs)).
    { change (id_r d) with r in Heq1, Heq2.
      rewrite <- Heq1, <- Heq2. reflexivity. }
    apply (factorization_unique_helper Hpid ps qs u1 u2
             Hu1 Hu2 Hpsirr Hqsirr Heq).
  Qed.

  (** A Euclidean domain has a norm satisfying the division algorithm *)
  Record EuclideanDomain : Type := mkED {
    ed_norm     : R -> nat;
    ed_division : forall a b : R,
      b <> rzero R r ->
      exists q rem : R,
        a = radd R r (rmul R r b q) rem /\
        (rem = rzero R r \/ ed_norm rem < ed_norm b);
  }.

  (** Every Euclidean domain is a PID *)
  Lemma euclidean_is_pid : forall (ed : EuclideanDomain), is_pid.
  Proof.
    intros ed I HI.
    (* Either I = {0} or I has a nonzero element. *)
    destruct (classic (exists x, I x /\ x <> rzero R r)) as [Hex | Hno].
    - (* Case: I has a nonzero element. Take element of minimum norm. *)
      (* The predicate P n := exists x, I x /\ x <> 0 /\ ed_norm ed x = n. *)
      set (P := fun n => exists x, I x /\ x <> rzero R r /\ ed_norm ed x = n).
      assert (HPex : exists n, P n).
      { destruct Hex as [x [Hx Hxne]]. exists (ed_norm ed x), x. tauto. }
      assert (HPdec : forall n, P n \/ ~ P n).
      { intro n. apply classic. }
      destruct (dec_inh_nat_subset_has_unique_least_element P HPdec HPex)
        as [n0 [[HPn0 Hmin] _]].
      destruct HPn0 as [b [HbI [Hbne Hbn]]].
      destruct HI as [[HIsg HIleft] HIright_pair].
      destruct HIsg as [HI0 [HIadd HIneg]].
      destruct HIright_pair as [_ HIright].
      exists b.
      intro x. split.
      + (* x ∈ I → x ∈ (b) *)
        intro HxI.
        destruct (ed_division ed x b Hbne) as [q [rem [Heq Hrem]]].
        (* rem = x - b*q = x + (-(b*q)). rem ∈ I. *)
        (* From Heq: x = b*q + rem; so rem = x + (-(b*q)). *)
        assert (Hrem_eq : rem = radd R r x (rneg R r (rmul R r b q))).
        { (* x = b*q + rem -> rem = -(b*q) + x = x + (-(b*q)) *)
          assert (Hstep : radd R r (rneg R r (rmul R r b q))
                           (radd R r (rmul R r b q) rem) = rem).
          { rewrite radd_assoc. rewrite radd_neg_l. apply radd_zero_l. }
          rewrite <- Heq in Hstep.
          rewrite (radd_comm R r) in Hstep.
          symmetry. exact Hstep. }
        (* rem ∈ I: x ∈ I and -(b*q) ∈ I (since b ∈ I and ideal) *)
        assert (HremI : I rem).
        { rewrite Hrem_eq.
          apply HIadd. exact HxI.
          apply HIneg.
          (* b*q ∈ I via right ideal *)
          apply HIright. exact HbI. }
        (* First handle rem = 0 case (whether by disjunction or EM). *)
        destruct (classic (rem = rzero R r)) as [Hrem0 | Hrem_ne].
        * (* rem = 0 means x = b*q. Then x = q*b ∈ (b). *)
          unfold principal_ideal.
          exists q. rewrite Heq, Hrem0, radd_zero_r. apply comm.
        * (* rem ≠ 0: must be in the strict-norm branch, contradicts minimality. *)
          exfalso.
          assert (Hrem_lt : ed_norm ed rem < ed_norm ed b).
          { destruct Hrem as [Hrem0 | Hlt].
            - contradiction.
            - exact Hlt. }
          assert (HPrem : P (ed_norm ed rem)).
          { exists rem. split; [exact HremI | split; [exact Hrem_ne | reflexivity]]. }
          specialize (Hmin (ed_norm ed rem) HPrem).
          rewrite Hbn in Hrem_lt. lia.
      + (* x ∈ (b) → x ∈ I. Since b ∈ I and (b) = R*b ⊆ I. *)
        intros [c Hc]. rewrite Hc.
        apply HIleft. exact HbI.
    - (* Case: I = {0}. Take a := 0. *)
      exists (rzero R r).
      intro x. split.
      + intro HxI.
        (* x must be 0 since no nonzero elements in I. *)
        destruct (classic (x = rzero R r)) as [Hx0 | Hxne].
        * unfold principal_ideal.
          exists (rzero R r). rewrite Hx0. symmetry. apply rmul_zero_l.
        * exfalso. apply Hno. exists x. tauto.
      + intros [c Hc]. rewrite Hc.
        rewrite rmul_zero_r.
        destruct HI as [[HIsg _] _].
        destruct HIsg as [HI0 _]. exact HI0.
  Qed.

  (** Every PID is a UFD *)
  Theorem pid_is_ufd (Hpid : is_pid) : IsUFD d.
  Proof.
    constructor.
    - apply pid_factorization_exists. exact Hpid.
    - unfold ufd_uniqueness.
      intros a F1 F2.
      exact (pid_factorization_unique Hpid a F1 F2).
  Qed.

  (** Corollary: every Euclidean domain is a UFD *)
  Corollary euclidean_is_ufd (ed : EuclideanDomain) : IsUFD d.
  Proof.
    apply pid_is_ufd.
    apply euclidean_is_pid. exact ed.
  Qed.

End PID.

Arguments is_pid {R} d.
