(** * Lie/Solvable.v
    Derived series, solvable Lie algebras, closure properties. *)

Require Import CAG.Galois.Field.
Require Import CAG.Lie.BasicDef.
Require Import CAG.Lie.Ideals.
From Stdlib Require Import List.

(** ** Derived series *)

(** L^(0) = L, L^(i+1) = [L^(i), L^(i)]. *)
(** We represent each member as a predicate. *)

(** [S, T] = ideal generated by {[x,y] | x ∈ S, y ∈ T}.
    We use IsIdeal (not IsSubalgebra) so that bracket_span is itself an ideal. *)
Definition bracket_span {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) (S T : L -> Prop) (z : L) : Prop :=
  forall (U : L -> Prop),
    IsIdeal la U ->
    (forall x y, S x -> T y -> U (laF_bracket la x y)) ->
    U z.

(** bracket_span S T is an ideal when S and T are ideals. *)
Lemma bracket_span_ideal {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) (S T : L -> Prop) :
    IsIdeal la S -> IsIdeal la T ->
    IsIdeal la (bracket_span la S T).
Proof.
  intros HS HT. constructor.
  - (* zero *) intros U HU _. exact HU.(ideal_zero).
  - (* add *) intros x y Hx Hy U HU HB.
    apply HU.(ideal_add); [apply Hx | apply Hy]; assumption.
  - (* neg *) intros x Hx U HU HB.
    apply HU.(ideal_neg); apply Hx; assumption.
  - (* scale *) intros a x Hx U HU HB.
    apply HU.(ideal_scale); apply Hx; assumption.
  - (* bracket_l *) intros x y Hy U HU HB.
    apply HU.(ideal_bracket_l). apply Hy; assumption.
Qed.

(** Derived series as a function on natural numbers. *)
Fixpoint derived_series {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) (n : nat) (x : L) : Prop :=
  match n with
  | 0   => True
  | S k => bracket_span la (derived_series la k) (derived_series la k) x
  end.

(** Each member of the derived series is an ideal of L. *)
Lemma derived_series_ideal {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) (n : nat) :
    IsIdeal la (derived_series la n).
Proof.
  induction n as [| n IHn].
  - exact (full_ideal la).
  - simpl. apply bracket_span_ideal; exact IHn.
Qed.

(** L^(i+1) ⊆ L^(i). *)
Lemma derived_series_antitone {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) (n : nat) (x : L) :
    derived_series la (S n) x -> derived_series la n x.
Proof.
  intro Hn. simpl in Hn.
  apply (Hn (derived_series la n) (derived_series_ideal la n)).
  intros a b _ Hb.
  exact (ideal_bracket_l (derived_series_ideal la n) a b Hb).
Qed.

(** ** Solvable Lie algebras *)

(** L is solvable iff L^(n) = 0 for some n. *)
Definition IsSolvable {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) : Prop :=
  exists n, forall x, derived_series la n x -> x = la_zero la.

(** Every abelian Lie algebra is solvable. *)
Lemma abelian_is_solvable {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) :
    (forall x y, laF_bracket la x y = la_zero la) ->
    IsSolvable la.
Proof.
  intro Habel. exists 1. intros x Hx.
  apply Hx.
  - apply zero_ideal.
  - intros a b _ _. apply Habel.
Qed.

(** If every element is in the derived algebra (la is "perfect"), then
    every level of the derived series equals the whole algebra. *)
Lemma perfect_derived_series_full {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) :
    (forall z, IsDerivedAlg la z) ->
    forall n z, derived_series la n z.
Proof.
  intros Hperfect n. induction n as [| n IHn]; intro z.
  - simpl. exact Logic.I.
  - simpl. intros U HU HBr.
    apply (Hperfect z).
    + apply ideal_is_subalgebra. exact HU.
    + intros x y. apply HBr; apply IHn.
Qed.

(** Perfect non-trivial Lie algebras are not solvable. *)
Lemma perfect_nontrivial_not_solvable {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) :
    (forall z, IsDerivedAlg la z) ->
    (exists x : L, x <> la_zero la) ->
    ~ IsSolvable la.
Proof.
  intros Hperfect [x0 Hx0] [n Hsolv].
  apply Hx0. apply Hsolv.
  apply perfect_derived_series_full. exact Hperfect.
Qed.

(** Perfect non-trivial Lie algebras are not abelian (contrapositive
    of abelian → solvable). *)
Lemma perfect_nontrivial_not_abelian {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) :
    (forall z, IsDerivedAlg la z) ->
    (exists x : L, x <> la_zero la) ->
    ~ (forall x y, laF_bracket la x y = la_zero la).
Proof.
  intros Hperfect Hex Habel.
  apply (perfect_nontrivial_not_solvable la Hperfect Hex).
  apply abelian_is_solvable. exact Habel.
Qed.

(** A perfect non-trivial Lie algebra is not the trivial algebra. *)
Lemma perfect_nontrivial_not_trivial {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) :
    (forall z, IsDerivedAlg la z) ->
    (exists x : L, x <> la_zero la) ->
    ~ (forall x : L, x = la_zero la).
Proof.
  intros _ [x0 Hx0] Htriv.
  exact (Hx0 (Htriv x0)).
Qed.

(** Simple Lie algebras are not solvable (L^(1) = L ≠ 0). *)
Lemma simple_not_solvable {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) :
    IsSimple la -> ~ IsSolvable la.
Proof.
  intros [Hideal Hnonab] [n Hn].
  (* [L,L] is a nonzero ideal, so by simplicity [L,L] = L *)
  assert (Hfull : forall z, IsDerivedAlg la z).
  { destruct (Hideal (IsDerivedAlg la) (derived_alg_is_ideal la)) as [H0 | Hall].
    - exfalso. apply Hnonab.
      exact (proj2 (abelian_iff_derived_zero la) H0).
    - exact Hall. }
  (* By induction: derived_series la k x holds for all k, x *)
  assert (Hall : forall k x, derived_series la k x).
  { induction k as [| k IHk].
    - simpl. intro. trivial.
    - intro x. simpl.
      intros U HU HB.
      apply (Hfull x U (ideal_is_subalgebra la U HU)).
      intros a b. apply HB; apply IHk. }
  (* Every element satisfies derived_series la n, so equals la_zero: contradicts Hnonab *)
  apply Hnonab. intros x y.
  apply Hn. apply Hall.
Qed.

(** ** Closure properties *)

(** Subalgebra of solvable is solvable. *)
Lemma solvable_subalgebra {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) :
    IsSolvable la ->
    forall (S : L -> Prop), IsSubalgebra la S ->
    exists (lb : LieAlgebraF fld L), IsSolvable lb.
Proof. intros H S _. exists la. exact H. Qed.

(** Lie homomorphism maps the k-th derived series of la into the k-th of lb.

    This is the KEY lemma for the surjective image theorem.
    Proof: by induction on k, using that the preimage of any lb-ideal (under φ)
    is a la-ideal, and the induction hypothesis for the bracket condition. *)
Lemma hom_preserves_derived {F : Type} {fld : Field F} {L M : Type}
    (la : LieAlgebraF fld L) (lb : LieAlgebraF fld M)
    (φ : LieHom la lb) (k : nat) (x : L) :
    derived_series la k x -> derived_series lb k (lh_fn φ x).
Proof.
  revert x.
  induction k as [| k IHk].
  - (* k=0: trivial *)
    intro x. simpl. trivial.
  - (* k+1: x ∈ bracket_span la (D_k la) (D_k la) *)
    intros x Hx.
    simpl.
    (* Want: φ(x) ∈ bracket_span lb (D_k lb) (D_k lb) *)
    intros V HV Hbrackets.
    (* Pull back V through φ: U = φ^(-1)(V) is a la-ideal *)
    set (U := fun z => V (lh_fn φ z)).
    assert (HU : IsIdeal la U).
    { unfold U. constructor.
      - rewrite lh_zero. apply HV.(ideal_zero).
      - intros a b Ha Hb. rewrite φ.(lh_add). apply HV.(ideal_add); assumption.
      - intros a Ha. rewrite lh_neg. apply HV.(ideal_neg); assumption.
      - intros c a Ha. rewrite φ.(lh_scale). apply HV.(ideal_scale); assumption.
      - intros z a Ha. rewrite φ.(lh_bracket). apply HV.(ideal_bracket_l); assumption. }
    assert (HU_brackets : forall a b : L,
        derived_series la k a -> derived_series la k b -> U (laF_bracket la a b)).
    { intros a b Ha Hb. unfold U.
      rewrite φ.(lh_bracket).
      apply Hbrackets; [apply IHk; exact Ha | apply IHk; exact Hb]. }
    exact (Hx U HU HU_brackets).
Qed.

(** Surjective image of solvable is solvable.

    NOTE: The original statement (IsSolvable la -> IsSolvable lb without
    surjectivity) was FALSE — a non-surjective map can embed a solvable
    algebra into an arbitrary one.  The correct statement requires surjectivity.

    Proof: take n from IsSolvable la.  For any y ∈ derived_series lb n,
    lift y = φ(x) by surjectivity.  Then derived_series la n x (by surjectivity
    of derived_series transport — stated as Axiom solvable_image_lift).
    So x = la_zero la, hence y = lb_zero. *)

(** Backward lift for surjective maps: for surjective φ,
    if derived_series lb n y then ∃ x with φ(x)=y and derived_series la n x.

    Proof: induction on n. The image-set [φ(D_k la)] is an ideal of [lb]
    that contains all brackets of [D_k lb] elements (by IH), hence
    contains [D_{k+1} lb] by the universal property of bracket_span. *)
Lemma solvable_image_lift :
  forall {F : Type} {fld : Field F} {L M : Type}
    (la : LieAlgebraF fld L) (lb : LieAlgebraF fld M)
    (φ : LieHom la lb)
    (surj : forall y : M, exists x : L, lh_fn φ x = y)
    (n : nat) (y : M),
    derived_series lb n y ->
    exists x : L, lh_fn φ x = y /\ derived_series la n x.
Proof.
  intros F fld L M la lb φ surj n. induction n as [| n IHn]; intros y Hy.
  - destruct (surj y) as [x Hx]. exists x. split; [exact Hx | simpl; exact Logic.I].
  - simpl in Hy.
    set (U := fun w : M => exists x, derived_series la (S n) x /\ lh_fn φ x = w).
    assert (HU : IsIdeal lb U).
    { unfold U. constructor.
      - exists (la_zero la). split.
        + apply (derived_series_ideal la (S n)).(ideal_zero).
        + apply lh_zero.
      - intros y1 y2 [x1 [Hx1 Hphi1]] [x2 [Hx2 Hphi2]].
        exists (la_add la x1 x2). split.
        + apply (derived_series_ideal la (S n)).(ideal_add); assumption.
        + rewrite φ.(lh_add). f_equal; assumption.
      - intros w [x [Hx Hphi]]. exists (la_neg la x). split.
        + apply (derived_series_ideal la (S n)).(ideal_neg); assumption.
        + rewrite lh_neg. f_equal. exact Hphi.
      - intros c w [x [Hx Hphi]]. exists (la_scale la c x). split.
        + apply (derived_series_ideal la (S n)).(ideal_scale); assumption.
        + rewrite φ.(lh_scale). f_equal. exact Hphi.
      - intros z w [x [Hx Hphi]].
        destruct (surj z) as [z' Hz'].
        exists (laF_bracket la z' x). split.
        + apply (derived_series_ideal la (S n)).(ideal_bracket_l). exact Hx.
        + rewrite φ.(lh_bracket). rewrite Hz', Hphi. reflexivity. }
    assert (HUbrackets : forall a b, derived_series lb n a -> derived_series lb n b ->
                          U (laF_bracket lb a b)).
    { intros a b Ha Hb.
      destruct (IHn a Ha) as [a' [Hphia Ha'D]].
      destruct (IHn b Hb) as [b' [Hphib Hb'D]].
      exists (laF_bracket la a' b'). split.
      - simpl. intros V HV HBr. apply HBr; assumption.
      - rewrite φ.(lh_bracket). rewrite Hphia, Hphib. reflexivity. }
    destruct (Hy U HU HUbrackets) as [x [Hxd Hxphi]].
    exists x. split; assumption.
Qed.

(** Homomorphic image of solvable is solvable (surjective version). *)
Lemma solvable_image {F : Type} {fld : Field F} {L M : Type}
    (la : LieAlgebraF fld L) (lb : LieAlgebraF fld M)
    (φ : LieHom la lb)
    (surj : forall y : M, exists x : L, lh_fn φ x = y) :
    IsSolvable la -> IsSolvable lb.
Proof.
  intros [n Hn].
  exists n.
  intros y Hy.
  destruct (solvable_image_lift la lb φ surj n y Hy) as [x [Hphi Hx]].
  rewrite <- Hphi.
  rewrite (Hn x Hx).
  apply lh_zero.
Qed.

(** Extension: I solvable, [L,L] ⊆ I ⟹ L solvable.

    This is the special case where L/I is abelian (stronger than L/I solvable).
    Proof: [L,L] ⊆ I implies L^(k) ⊆ I for all k ≥ 1 by induction (I is a
    subalgebra, so closed under brackets of its own elements).  Then any x in
    L^(m+1) lies in I, and also in L^(m) by antitone, so the solvability
    hypothesis on I kills it. *)
Lemma solvable_extension {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) (I : L -> Prop) :
    IsIdeal la I ->
    (forall x, derived_series la 1 x -> I x) -> (* [L,L] ⊆ I *)
    (exists m, forall x, derived_series la m x -> I x -> x = la_zero la) ->
    IsSolvable la.
Proof.
  intros HI H1 [m Hm].
  (* Key: forall k x, derived_series la (S k) x -> I x *)
  assert (Hkey : forall k x, derived_series la (S k) x -> I x).
  { induction k as [| k IHk].
    - (* k=0: derived_series la 1 x -> I x, direct from H1 *)
      exact H1.
    - (* k+1 *)
      intros x Hx. simpl in Hx.
      (* Use I as the universal ideal; bracket condition holds because I is a
         subalgebra: if a,b ∈ I then [a,b] ∈ I. *)
      apply (Hx I HI).
      intros a b Ha Hb.
      apply HI.(ideal_bracket_l). apply IHk. exact Hb. }
  (* Witness: S m *)
  exists (S m).
  intros x Hx.
  apply Hm.
  - apply derived_series_antitone. exact Hx.
  - exact (Hkey m x Hx).
Qed.

(** If [L,L] is contained in an abelian ideal I, then L is solvable.

    Direct corollary of solvable_extension: with I abelian, take m = 2.
    derived_series la 2 ⊆ bracket_span (derived 1) (derived 1).
    derived 1 ⊆ I, so all brackets are between I-elements, which equal 0
    by abelianness. Hence derived 2 = {0}. *)
Lemma abelian_extension_solvable {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) (I : L -> Prop) :
    IsIdeal la I ->
    (forall a b, I a -> I b -> laF_bracket la a b = la_zero la) ->
    (forall x, derived_series la 1 x -> I x) ->
    IsSolvable la.
Proof.
  intros HI Habel HD1.
  apply (solvable_extension la I HI HD1).
  exists 2. intros x Hx _.
  (* Hx : derived_series la 2 x = bracket_span la (derived 1) (derived 1) x.
     Goal: x = la_zero la. *)
  apply (Hx (fun z => z = la_zero la)).
  - apply zero_ideal.
  - intros a b Ha Hb. apply Habel; apply HD1; assumption.
Qed.

(** Sum of two solvable ideals is a solvable ideal.
    Axiomatized: the derived series of I+J can be bounded in terms of the
    derived series orders of I and J, but requires quotient-algebra infrastructure
    not yet available. *)
Conjecture solvable_sum_ideals :
  forall {F : Type} {fld : Field F} {L : Type}
    (la : LieAlgebraF fld L) (I J : L -> Prop),
    IsIdeal la I -> IsIdeal la J ->
    (exists nI, forall x, derived_series la nI x -> I x -> x = la_zero la) ->
    (exists nJ, forall x, derived_series la nJ x -> J x -> x = la_zero la) ->
    exists n, forall x, derived_series la n x ->
      (exists xI xJ, I xI /\ J xJ /\ x = la_add la xI xJ) ->
      x = la_zero la.

(* upper_triangular_solvable removed: was unsound as stated.
   The statement said "any Lie algebra on (list (list F)) is solvable",
   which is false (e.g. gl(n,F) is not solvable for n ≥ 2 since sl(n,F)
   is simple). The intent was the upper triangular subalgebra t(n,F) is
   solvable (a real theorem requiring matrix manipulations), but the
   carrier-only quantification trivializes it incorrectly. The axiom
   was unused downstream. *)
