(** * AxTheory/GluingSetup.v
    The specific gluing setup used in the proof of the conservativity theorem
    (Discussion 4.10.5 / Theorem 4.10.7).

    Setup:
    - E  = Cl(Th)      (algebraic classifying category, FP)
    - E' = AxCl(Th)    (Ax classifying CCC)
    - I  : E → E'      (the canonical FP-functor from RelativeFreeCCC.v)
    - TC = E'          (the relatively free CCC generated by E)
    - T  : E' → [E^op, Set]  defined as T := よ_{E'} composed with precomposition by I
    - Gl(T) is the glued category
    - J  : E → Gl(T)   is the functor defined by the Yoneda elements

    Key facts:
    - Gl(T) is a CCC (Lemma 4.10.3)
    - P2 : Gl(T) → E' is a CCC functor
    - J is full, faithful, and preserves finite products
    - P2 ∘ J = I (on objects)
    - By relative freeness, there is a CCC functor Ī : E' → Gl(T)
      with P2 ∘ Ī ≅ id_{E'}
    - Fullness and faithfulness of I follows *)

Require Import CAG.ATT.Signature.
Require Import CAG.ATT.Theory.
Require Import CAG.ATT.ClassifyingCategory.
Require Import CAG.AxTheory.Syntax.
Require Import CAG.AxTheory.Theory.
Require Import CAG.AxTheory.ClassifyingCategory.
Require Import CAG.AxTheory.RelativeFreeCCC.
Require Import CAG.Category.Core.
Require Import CAG.Category.Functor.
Require Import CAG.Category.Products.
Require Import CAG.Category.CartesianClosed.
Require Import CAG.Category.Gluing.
Require Import CAG.Category.Yoneda.
Require Import CAG.Category.Representable.
From Stdlib Require Import Lists.List.
Import ListNotations.

Set Universe Polymorphism.
Open Scope cat_scope.

(** ** The functor T : AxCl(Sg) → [Cl(Sg)^op, Set]

    T is defined as the composite:
      E' --よ_{E'}--> [E'^op, Set] --P(-∘I)--> [E^op, Set]

    where よ_{E'} is the Yoneda embedding and P(-∘I) is precomposition with I. *)

Definition T_functor (Sg : Signature) :
    Functor (AxCl Sg) TypeCat.
Proof.
  Admitted.

(** ** Full statement of the gluing setup

    We package the key data as a record. *)

Record GluingData (Sg : Signature) : Type := {

  (** The categories *)
  gd_E  : Category := Cl Sg;
  gd_Ep : Category := AxCl Sg;

  (** Structures *)
  gd_hE  : HasFiniteProducts gd_E  := cl_finite_products Sg;
  gd_cEp : IsCartesianClosed gd_Ep := axcl_ccc Sg;

  (** The functor T : E' → TypeCat (playing the role of [E^op, Set]) *)
  gd_T   : Functor gd_Ep TypeCat;

  (** The glued category Gl(T) *)
  gd_Gl  : Category := Gl gd_T;

  (** The CCC structure on Gl(T) *)
  gd_cGl : IsCartesianClosed gd_Gl;

  (** P2 : Gl(T) → E' is a CCC functor *)
  gd_P2  : CCCFunctor gd_cGl gd_cEp;

  (** J : E → Gl(T) is full, faithful, and FP-preserving *)
  gd_J   : FPtoCCCFunctor gd_hE gd_cGl;
  gd_J_full     : forall αs βs (g : gd_Gl ⟦ gd_J ## αs, gd_J ## βs ⟧),
                    exists f : gd_E ⟦ αs, βs ⟧, gd_J #> f = g;
  gd_J_faithful : forall αs βs (f g : gd_E ⟦ αs, βs ⟧),
                    gd_J #> f = gd_J #> g -> f = g;

  (** P2 ∘ J = I on objects *)
  gd_P2_J_eq_I : forall αs, gd_P2 ## (gd_J ## αs) = I_obj αs;

}.

(** ** The gluing data exists (admitted — requires full development) *)

Theorem gluing_data_exists : forall (Sg : Signature), GluingData Sg.
Proof. admit. Admitted.

(** ** Key corollary: I : E → E' is full and faithful

    From the gluing data:
    - J is full and faithful  (gd_J_full, gd_J_faithful)
    - P2 is a CCC functor
    - P2 ∘ J = I
    - By relative freeness, there exists Ī : E' → Gl(T) with P2 ∘ Ī ≅ id_{E'}
    - Combining: I is full and faithful

    The formal proof requires the relative freeness of Cl(Th') and is admitted. *)

Theorem I_is_full (Sg : Signature) :
    forall (αs βs : list Sg.(sg_ty))
           (g : AxCl Sg ⟦ I_obj αs, I_obj βs ⟧),
    exists f : Cl Sg ⟦ αs, βs ⟧, I_map αs βs f = g.
Proof.
  Admitted.

Theorem I_is_faithful (Sg : Signature) :
    forall (αs βs : list Sg.(sg_ty))
           (f g : Cl Sg ⟦ αs, βs ⟧),
    I_map αs βs f = I_map αs βs g -> f = g.
Proof.
  Admitted.
