(** * AxTheory/RelativeFreeCCC.v
    Relatively free cartesian closed category generated by a
    finite-product category.

    Given a category C with finite products, a relatively free CCC
    generated by C is a CCC TC together with a finite-product-preserving
    functor J : C → TC such that:

    1. (Universal extension) For every CCC D and every
       finite-product-preserving functor F : C → D,
       there exists a CCC functor F̄ : TC → D with
       F̄ ∘ J naturally isomorphic to F.

    2. (Uniqueness) The extension F̄ is unique up to unique
       natural isomorphism compatible with the comparison F̄ ∘ J ≅ F.

    Proposition 4.10.2 states that the functor
       I : Cl(Th) → Cl(Th')
    (from the algebraic classifying category into the Ax classifying category)
    presents Cl(Th') as the relatively free CCC generated by Cl(Th). *)

Require Import CAG.ATT.Signature.
Require Import CAG.ATT.Theory.
Require Import CAG.AxTheory.Syntax.
Require Import CAG.AxTheory.Theory.
Require Import CAG.AxTheory.ClassifyingCategory.
Require Import CAG.ATT.ClassifyingCategory.
Require Import CAG.Category.Core.
Require Import CAG.Category.Functor.
Require Import CAG.Category.Products.
Require Import CAG.Category.CartesianClosed.
From Stdlib Require Import Lists.List.
Import ListNotations.

Set Universe Polymorphism.
Open Scope cat_scope.

(** ** FP-functor into a CCC

    A finite-product-preserving functor from a category with FP into a CCC. *)

Record FPtoCCCFunctor {C D : Category} (hC : HasFiniteProducts C)
    (cD : IsCartesianClosed D) : Type := {
  fptoccc_funct    :> Functor C D;
  fptoccc_pres_term : fptoccc_funct ## (projT1 (@fp_terminal C hC)) =
                      projT1 (@fp_terminal D cD.(ccc_fp));
  fptoccc_pres_prod : forall A B,
                        fptoccc_funct ## (A ×{@fp_binary C hC} B) =
                        fptoccc_funct ## A ×{@fp_binary D cD.(ccc_fp)} fptoccc_funct ## B;
}.

Arguments fptoccc_funct    {C D hC cD}.
Arguments fptoccc_pres_term {C D hC cD}.
Arguments fptoccc_pres_prod {C D hC cD}.

(** ** Natural isomorphism (object-wise equality version)

    For our purposes we use pointwise equality of objects as the
    notion of "natural isomorphism" of functors.  A proper treatment
    would use NatTrans with iso components. *)

Definition FunctorObjEq {C D : Category} (F G : Functor C D) : Prop :=
  forall A, F ## A = G ## A.

(** ** Relatively free CCC *)

Record RelativelyFreeCCC
    {C : Category} (hC : HasFiniteProducts C)
    {TC : Category} (cTC : IsCartesianClosed TC)
    (J : FPtoCCCFunctor hC cTC) : Type := {

  (** Universal extension: any FP-functor F : C → D into a CCC
      extends to a CCC functor F̄ : TC → D *)
  rfccc_ext : forall {D : Category} (cD : IsCartesianClosed D)
                (F : FPtoCCCFunctor hC cD),
              CCCFunctor cTC cD;

  (** Comparison: F̄ ∘ J ≅ F on objects *)
  rfccc_cmp : forall {D : Category} (cD : IsCartesianClosed D)
                (F : FPtoCCCFunctor hC cD),
              FunctorObjEq
                (rfccc_ext cD F ∘F J.(fptoccc_funct))
                F.(fptoccc_funct);

  (** Uniqueness: if F̄' also extends F then F̄' ≅ F̄ *)
  rfccc_uniq : forall {D : Category} (cD : IsCartesianClosed D)
                 (F : FPtoCCCFunctor hC cD)
                 (Fbar' : CCCFunctor cTC cD),
               FunctorObjEq (Fbar' ∘F J.(fptoccc_funct)) F.(fptoccc_funct) ->
               FunctorObjEq Fbar' (rfccc_ext cD F);
}.

Arguments rfccc_ext  {C hC TC cTC J} _ {D cD}.
Arguments rfccc_cmp  {C hC TC cTC J} _ {D cD}.
Arguments rfccc_uniq {C hC TC cTC J} _ {D cD}.

(** ** Generated Ax-theory and the functor I

    Given an algebraic theory Th, its generated Ax-theory Th' has:
    - same signature as Th
    - no axioms (beta/eta are structural in AxThEq)
    The classifying category Cl(Th') = AxCl Th.(th_sig) is a CCC.

    The functor I : Cl(Th) → AxCl(Th) sends:
    - a list [α₁,...,αₙ] in Cl(Th) to the iterated product α₁ ×ax ... ×ax αₙ
    - a morphism (tuple of terms) to a corresponding single Ax-term via pairing *)

Definition alg_to_ax_type {Sg : Signature} (τ : Sg.(sg_ty)) : AxType Sg :=
  ax_ground τ.

(** Iterated product of a list of Ax-types (left-nested) *)
Fixpoint ax_iter_prod {Sg : Signature} (αs : list (AxType Sg)) : AxType Sg :=
  match αs with
  | []      => ax_unit
  | [α]     => α
  | α :: αs => ax_prod α (ax_iter_prod αs)
  end.

(** I on objects: map a list of ground sorts to their iterated product *)
Definition I_obj {Sg : Signature} (αs : list Sg.(sg_ty)) : AxType Sg :=
  ax_iter_prod (List.map ax_ground αs).

(** Projection terms: project the j-th component out of an iterated product *)
(* CAG zero-dependent Admitted ax_iter_proj theories/AxTheory/RelativeFreeCCC.v:129 BEGIN
Theorem ax_iter_proj : forall {Sg : Signature} (αs : list (AxType Sg))
    (j : nat) (α : AxType Sg),
    List.nth_error αs j = Some α ->
    AxHasType Sg [ax_iter_prod αs] (ax_var 0) (ax_iter_prod αs) ->
    AxHasType Sg [ax_iter_prod αs] (ax_var 0) α.
Proof. admit. Admitted.
   CAG zero-dependent Admitted ax_iter_proj theories/AxTheory/RelativeFreeCCC.v:129 END *)
    (* Placeholder: real projection navigates the nested pairs *)

(** I on morphisms (admitted — requires iterated projections and pairing) *)
(* CAG zero-dependent Theorem I_map theories/AxTheory/RelativeFreeCCC.v:135 BEGIN
Theorem I_map : forall {Sg : Signature}
    (αs βs : list Sg.(sg_ty))
    (f : Cl Sg ⟦ αs, βs ⟧),
    AxCl Sg ⟦ I_obj αs, I_obj βs ⟧.
Proof. admit. Admitted.
   CAG zero-dependent Theorem I_map theories/AxTheory/RelativeFreeCCC.v:135 END *)

(** I is a functor (admitted) *)
(* CAG zero-dependent Theorem I_fmap_id theories/AxTheory/RelativeFreeCCC.v:142 BEGIN
Theorem I_fmap_id : forall {Sg : Signature} (αs : list Sg.(sg_ty)),
    I_map αs αs ((Cl Sg).(id) αs) = (AxCl Sg).(id) (I_obj αs).
Proof. admit. Admitted.
   CAG zero-dependent Theorem I_fmap_id theories/AxTheory/RelativeFreeCCC.v:142 END *)

(* CAG zero-dependent Theorem I_fmap_comp theories/AxTheory/RelativeFreeCCC.v:146 BEGIN
Theorem I_fmap_comp : forall {Sg : Signature}
    (αs βs γs : list Sg.(sg_ty))
    (g : Cl Sg ⟦ βs, γs ⟧) (f : Cl Sg ⟦ αs, βs ⟧),
    I_map αs γs (g ∘ f) = I_map βs γs g ∘ I_map αs βs f.
Proof. admit. Admitted.
   CAG zero-dependent Theorem I_fmap_comp theories/AxTheory/RelativeFreeCCC.v:146 END *)

(* CAG zero-dependent Definition I_functor theories/AxTheory/RelativeFreeCCC.v:152 BEGIN
Definition I_functor (Sg : Signature) : Functor (Cl Sg) (AxCl Sg) :=
  Build_Functor (Cl Sg) (AxCl Sg)
    I_obj
    (fun αs βs f => I_map αs βs f)
    I_fmap_id
    I_fmap_comp.
   CAG zero-dependent Definition I_functor theories/AxTheory/RelativeFreeCCC.v:152 END *)

(** ** Proposition 4.10.2

    The functor I : Cl(Th) → Cl(Th') presents Cl(Th') as the
    relatively free CCC generated by Cl(Th).

    The proof is the main content of Section 4.10 and is admitted here. *)

Require Import CAG.ATT.ClassifyingCategory.

(* CAG zero-dependent Definition I_fp_functor theories/AxTheory/RelativeFreeCCC.v:168 BEGIN
Definition I_fp_functor (Sg : Signature) :
    FPtoCCCFunctor (cl_finite_products Sg) (axcl_ccc Sg).
Proof.
  Admitted.
   CAG zero-dependent Definition I_fp_functor theories/AxTheory/RelativeFreeCCC.v:168 END *)

(* CAG zero-dependent Admitted classifying_CCC_is_relatively_free theories/AxTheory/RelativeFreeCCC.v:174 BEGIN
Theorem classifying_CCC_is_relatively_free (Sg : Signature) :
    RelativelyFreeCCC (cl_finite_products Sg) (axcl_ccc Sg) (I_fp_functor Sg).
Proof.
  Admitted.
   CAG zero-dependent Admitted classifying_CCC_is_relatively_free theories/AxTheory/RelativeFreeCCC.v:174 END *)
