(** * AxTheory/RelativeFreeCCC.v
    Relatively free cartesian closed category generated by a
    finite-product category.

    Given a category C with finite products, a relatively free CCC
    generated by C is a CCC TC together with a finite-product-preserving
    functor J : C → TC such that:

    1. (Universal extension) For every CCC D and every
       finite-product-preserving functor F : C → D,
       there exists a CCC functor F̄ : TC → D with
       F̄ ∘ J naturally isomorphic to F.

    2. (Uniqueness) The extension F̄ is unique up to unique
       natural isomorphism compatible with the comparison F̄ ∘ J ≅ F.

    Proposition 4.10.2 states that the functor
       I : Cl(Th) → Cl(Th')
    (from the algebraic classifying category into the Ax classifying category)
    presents Cl(Th') as the relatively free CCC generated by Cl(Th). *)

Require Import CAG.ATT.Signature.
Require Import CAG.ATT.Syntax.
Require Import CAG.ATT.Theory.
Require Import CAG.AxTheory.Syntax.
Require Import CAG.AxTheory.Theory.
Require Import CAG.AxTheory.ClassifyingCategory.
Require Import CAG.ATT.ClassifyingCategory.
Require Import CAG.Category.Core.
Require Import CAG.Category.Functor.
Require Import CAG.Category.Products.
Require Import CAG.Category.CartesianClosed.
From Stdlib Require Import Lists.List.
From Stdlib Require Import Arith.Arith.
From Stdlib Require Import micromega.Lia.
Import ListNotations.

Set Universe Polymorphism.
Open Scope cat_scope.

(** ** FP-functor into a CCC

    A finite-product-preserving functor from a category with FP into a CCC.

    α-A.2.next refactor (2026-05-01): the preservation conditions are
    relaxed from STRICT EQUALITY of objects to ISOMORPHISMS in the
    target category D.  This is needed for [I_fp_functor] (cf. the
    documented structural obstruction below): under strict equality
    the equation [I_obj (αs ++ βs) = I_obj αs ×ax I_obj βs] is false
    (e.g. αs = βs = [] would force [ax_unit = ax_prod ax_unit ax_unit]
    refutable on the [AxType] inductive), but under isomorphism it
    is provable via [pack]/[unpack] η-laws in [AxThEq].

    The strict-equality version is recovered as a degenerate special
    case where each iso is [iso_refl].  See [FPtoCCCFunctor_strict]
    below for the convenience constructor. *)

Record FPtoCCCFunctor {C D : Category} (hC : HasFiniteProducts C)
    (cD : IsCartesianClosed D) : Type := {
  fptoccc_funct    :> Functor C D;
  (** Iso witness: F(1_C) ≅ 1_D *)
  fptoccc_iso_term : @Isomorphism D
                       (fptoccc_funct ## (projT1 (@fp_terminal C hC)))
                       (projT1 (@fp_terminal D cD.(ccc_fp)));
  (** Iso witness: F(A × B) ≅ F(A) × F(B) *)
  fptoccc_iso_prod : forall A B,
                       @Isomorphism D
                         (fptoccc_funct ## (A ×{@fp_binary C hC} B))
                         (fptoccc_funct ## A ×{@fp_binary D cD.(ccc_fp)}
                          fptoccc_funct ## B);
}.

Arguments fptoccc_funct    {C D hC cD}.
Arguments fptoccc_iso_term {C D hC cD}.
Arguments fptoccc_iso_prod {C D hC cD}.

(** Convenience constructor: build an [FPtoCCCFunctor] from a strict
    preservation (degenerate iso = identity).  This is the degenerate
    special case where the iso is [iso_refl], allowing legacy
    strict-equality preservation arguments to coerce into the
    iso-loosened record. *)

Definition FPtoCCCFunctor_strict {C D : Category} {hC : HasFiniteProducts C}
    {cD : IsCartesianClosed D}
    (F : Functor C D)
    (Hterm : F ## (projT1 (@fp_terminal C hC)) =
             projT1 (@fp_terminal D cD.(ccc_fp)))
    (Hprod : forall A B,
                F ## (A ×{@fp_binary C hC} B) =
                F ## A ×{@fp_binary D cD.(ccc_fp)} F ## B)
    : FPtoCCCFunctor hC cD :=
  {| fptoccc_funct    := F;
     fptoccc_iso_term := match Hterm in _ = X return @Isomorphism D _ X with
                          | eq_refl => iso_refl _
                          end;
     fptoccc_iso_prod := fun A B =>
       match Hprod A B in _ = X return @Isomorphism D _ X with
       | eq_refl => iso_refl _
       end;
  |}.

(** ** Natural isomorphism (object-wise equality version)

    For our purposes we use pointwise equality of objects as the
    notion of "natural isomorphism" of functors.  A proper treatment
    would use NatTrans with iso components. *)

Definition FunctorObjEq {C D : Category} (F G : Functor C D) : Prop :=
  forall A, F ## A = G ## A.

(** ** Relatively free CCC *)

Record RelativelyFreeCCC
    {C : Category} (hC : HasFiniteProducts C)
    {TC : Category} (cTC : IsCartesianClosed TC)
    (J : FPtoCCCFunctor hC cTC) : Type := {

  (** Universal extension: any FP-functor F : C → D into a CCC
      extends to a CCC functor F̄ : TC → D *)
  rfccc_ext : forall {D : Category} (cD : IsCartesianClosed D)
                (F : FPtoCCCFunctor hC cD),
              CCCFunctor cTC cD;

  (** Comparison: F̄ ∘ J ≅ F on objects *)
  rfccc_cmp : forall {D : Category} (cD : IsCartesianClosed D)
                (F : FPtoCCCFunctor hC cD),
              FunctorObjEq
                (rfccc_ext cD F ∘F J.(fptoccc_funct))
                F.(fptoccc_funct);

  (** Uniqueness: if F̄' also extends F then F̄' ≅ F̄ *)
  rfccc_uniq : forall {D : Category} (cD : IsCartesianClosed D)
                 (F : FPtoCCCFunctor hC cD)
                 (Fbar' : CCCFunctor cTC cD),
               FunctorObjEq (Fbar' ∘F J.(fptoccc_funct)) F.(fptoccc_funct) ->
               FunctorObjEq Fbar' (rfccc_ext cD F);
}.

Arguments rfccc_ext  {C hC TC cTC J} _ {D cD}.
Arguments rfccc_cmp  {C hC TC cTC J} _ {D cD}.
Arguments rfccc_uniq {C hC TC cTC J} _ {D cD}.

(** ** Generated Ax-theory and the functor I

    Given an algebraic theory Th, its generated Ax-theory Th' has:
    - same signature as Th
    - no axioms (beta/eta are structural in AxThEq)
    The classifying category Cl(Th') = AxCl Th.(th_sig) is a CCC.

    The functor I : Cl(Th) → AxCl(Th) sends:
    - a list [α₁,...,αₙ] in Cl(Th) to the iterated product α₁ ×ax ... ×ax αₙ
    - a morphism (tuple of terms) to a corresponding single Ax-term via pairing *)

Definition alg_to_ax_type {Sg : Signature} (τ : Sg.(sg_ty)) : AxType Sg :=
  ax_ground τ.

(** Iterated product of a list of Ax-types (left-nested) *)
Fixpoint ax_iter_prod {Sg : Signature} (αs : list (AxType Sg)) : AxType Sg :=
  match αs with
  | []      => ax_unit
  | [α]     => α
  | α :: αs => ax_prod α (ax_iter_prod αs)
  end.

(** I on objects: map a list of ground sorts to their iterated product *)
Definition I_obj {Sg : Signature} (αs : list Sg.(sg_ty)) : AxType Sg :=
  ax_iter_prod (List.map ax_ground αs).

(* ax_iter_proj removed: false-as-stated. The axiom claimed [ax_var 0]
   (which has type [ax_iter_prod αs]) also has type [α] (the j-th
   component), without applying any projection. This is wrong unless
   α = ax_iter_prod αs (i.e. αs is a singleton). The proper statement
   needs a projection term [proj_j (ax_var 0)] of type α, not [ax_var 0]
   itself. The comment self-identified as a placeholder. Was unused. *)

(* ================================================================== *)
(** ** Translation from algebraic to Ax syntax (Task A.2)              *)
(* ================================================================== *)

(** Atom embedding: an algebraic term [t : Term Sg] becomes the
    structurally identical [AxTerm Sg] (variables go to [ax_var],
    function applications stay function applications). *)
Fixpoint atom {Sg : Signature} (t : Term Sg) : AxTerm Sg :=
  match t with
  | t_var i        => ax_var i
  | t_app f args   => ax_app_fn f (List.map atom args)
  end.

(** Atom embedding preserves typing.  An algebraic term [t] of sort
    [τ] in algebraic context [αs] becomes an Ax-term of type
    [ax_ground τ] in the matching Ax-context [List.map ax_ground αs]. *)
Lemma atom_preserves_type (Sg : Signature) (αs : list Sg.(sg_ty)) :
    forall t τ, HasType Sg αs t τ ->
                AxHasType Sg (List.map ax_ground αs) (atom t) (ax_ground τ).
Proof.
  fix IH 3.
  intros t τ Ht. destruct Ht as [n τ Hn | f args Hargs].
  - (* t_var n *)
    simpl. apply ax_ht_var.
    rewrite List.nth_error_map, Hn. reflexivity.
  - (* t_app f args *)
    simpl. apply ax_ht_fn.
    induction Hargs as [|a σ rest dom' Ha Hrest IHrest].
    + constructor.
    + constructor.
      * exact (IH a σ Ha).
      * exact IHrest.
Qed.

(** Iterated projections: [proj_at αs i M] produces a term of type
    [αs[i]] from [M : ax_iter_prod αs] via a chain of [ax_fst]/[ax_snd]. *)
Fixpoint proj_at {Sg : Signature} (αs : list (AxType Sg))
    (i : nat) (M : AxTerm Sg) : AxTerm Sg :=
  match αs with
  | []        => M  (* unreachable: i out of range *)
  | [_]       => M  (* αs is a singleton: ax_iter_prod = α; M itself is the value *)
  | _ :: αs'  =>
      match i with
      | 0   => ax_fst M
      | S j => proj_at αs' j (ax_snd M)
      end
  end.

Lemma proj_at_typed (Sg : Signature) (Γ : list (AxType Sg)) :
    forall (αs : list (AxType Sg)) (i : nat) (τ : AxType Sg) (M : AxTerm Sg),
      List.nth_error αs i = Some τ ->
      AxHasType Sg Γ M (ax_iter_prod αs) ->
      AxHasType Sg Γ (proj_at αs i M) τ.
Proof.
  intro αs.
  induction αs as [|α αs' IH]; intros i τ M Hi HM.
  - destruct i; discriminate.
  - (* αs = α :: αs' *)
    destruct αs' as [|α' αs''].
    + (* αs = [α] *)
      destruct i as [|i].
      * simpl in Hi. injection Hi as <-. simpl. exact HM.
      * destruct i; discriminate.
    + (* αs = α :: α' :: αs'' *)
      change (proj_at (α :: α' :: αs'') i M) with
        (match i with
         | 0   => ax_fst M
         | S j => proj_at (α' :: αs'') j (ax_snd M)
         end).
      destruct i as [|j].
      * simpl in Hi. injection Hi as <-.
        apply (ax_ht_fst Sg Γ M α (ax_iter_prod (α' :: αs''))).
        change (ax_iter_prod (α :: α' :: αs''))
          with (ax_prod α (ax_iter_prod (α' :: αs''))) in HM.
        exact HM.
      * simpl in Hi.
        apply IH.
        -- exact Hi.
        -- apply (ax_ht_snd Sg Γ M α (ax_iter_prod (α' :: αs''))).
           change (ax_iter_prod (α :: α' :: αs''))
             with (ax_prod α (ax_iter_prod (α' :: αs''))) in HM.
           exact HM.
Qed.

(** [unpack αs] is the substitution
    [proj_at (map ax_ground αs) 0 (ax_var 0); ...; proj_at ... (n-1) (ax_var 0)]
    where n = length αs.  It maps the singleton context [I_obj αs] to
    the multi-context [List.map ax_ground αs]. *)
Definition unpack {Sg : Signature} (αs : list Sg.(sg_ty)) : list (AxTerm Sg) :=
  List.map (fun i => proj_at (List.map ax_ground αs) i (ax_var 0))
           (List.seq 0 (length αs)).

Lemma unpack_typed (Sg : Signature) (αs : list Sg.(sg_ty)) :
    Forall2 (AxHasType Sg [I_obj αs]) (unpack αs) (List.map ax_ground αs).
Proof.
  unfold unpack, I_obj.
  set (M0 := ax_var 0 : AxTerm Sg).
  set (sortlist := List.map ax_ground αs).
  assert (HM0 : AxHasType Sg [ax_iter_prod sortlist] M0 (ax_iter_prod sortlist)).
  { apply ax_ht_var. reflexivity. }
  assert (Hlen : length αs = length sortlist).
  { unfold sortlist. symmetry. apply List.length_map. }
  rewrite Hlen.
  (* Generalize over the sublist viewpoint. *)
  assert (Hgen : forall (L0 : list (AxType Sg)) (k : nat),
             (forall i τ, List.nth_error L0 i = Some τ ->
                          List.nth_error sortlist (k + i) = Some τ) ->
             Forall2 (AxHasType Sg [ax_iter_prod sortlist])
                     (List.map (fun i => proj_at sortlist i M0)
                               (List.seq k (length L0)))
                     L0).
  { induction L0 as [|τ L0' IH'].
    - intros k _. constructor.
    - intros k Hnth.
      simpl. constructor.
      + apply (proj_at_typed Sg [ax_iter_prod sortlist] sortlist k τ M0).
        * specialize (Hnth 0 τ eq_refl). rewrite Nat.add_0_r in Hnth. exact Hnth.
        * exact HM0.
      + apply (IH' (S k)).
        intros i τ' Hi. specialize (Hnth (S i) τ' Hi).
        replace (S k + i) with (k + S i) by lia.
        exact Hnth. }
  apply (Hgen sortlist 0).
  intros i τ Hi. simpl. exact Hi.
Qed.

(** Iterated pair: matches the structure of [ax_iter_prod]. *)
Fixpoint pack {Sg : Signature} (Ms : list (AxTerm Sg)) : AxTerm Sg :=
  match Ms with
  | []           => ax_tt
  | [M]          => M
  | M :: Ms'     => ax_pair M (pack Ms')
  end.

Lemma pack_typed (Sg : Signature) (Γ : list (AxType Sg)) :
    forall (Ms : list (AxTerm Sg)) (αs : list (AxType Sg)),
      Forall2 (AxHasType Sg Γ) Ms αs ->
      AxHasType Sg Γ (pack Ms) (ax_iter_prod αs).
Proof.
  intro Ms.
  induction Ms as [|M Ms' IH]; intros αs Hf.
  - inversion Hf. simpl. apply ax_ht_tt.
  - inversion Hf as [|M0 α Ms0 αs' HM Hf' EM Eα]; subst.
    destruct Ms' as [|M' Ms''].
    + (* Ms = [M] *)
      inversion Hf'. subst. simpl. exact HM.
    + (* Ms = M :: M' :: Ms'' *)
      inversion Hf' as [|M0' α' Ms0' αs'' HM' Hf'' EM' Eα']; subst.
      change (pack (M :: M' :: Ms''))
        with (ax_pair M (pack (M' :: Ms''))).
      change (ax_iter_prod (α :: α' :: αs''))
        with (ax_prod α (ax_iter_prod (α' :: αs''))).
      apply ax_ht_pair.
      * exact HM.
      * apply IH. constructor; assumption.
Qed.

(** Translation of one algebraic term to the singleton Ax-context. *)
Definition tr_term {Sg : Signature} (αs : list Sg.(sg_ty))
    (t : Term Sg) : AxTerm Sg :=
  ax_subst (unpack αs) (atom t).

Lemma tr_term_typed (Sg : Signature) (αs : list Sg.(sg_ty))
    (t : Term Sg) (τ : Sg.(sg_ty)) :
    HasType Sg αs t τ ->
    AxHasType Sg [I_obj αs] (tr_term αs t) (ax_ground τ).
Proof.
  intro Ht. unfold tr_term.
  apply (ax_subst_preserves_type Sg [I_obj αs] (List.map ax_ground αs)
                                 (unpack αs) (unpack_typed Sg αs)).
  apply atom_preserves_type. exact Ht.
Qed.

(** Translation of a list of algebraic terms (= packing). *)
Definition tr_terms {Sg : Signature} (αs : list Sg.(sg_ty))
    (ts : list (Term Sg)) : AxTerm Sg :=
  pack (List.map (tr_term αs) ts).

Lemma tr_terms_typed (Sg : Signature) (αs βs : list Sg.(sg_ty))
    (ts : list (Term Sg)) :
    Forall2 (HasType Sg αs) ts βs ->
    AxHasType Sg [I_obj αs] (tr_terms αs ts) (I_obj βs).
Proof.
  intro Hts. unfold tr_terms, I_obj.
  apply pack_typed.
  induction Hts as [|t τ ts' βs' Ht Hts' IH].
  - constructor.
  - simpl. constructor.
    + exact (tr_term_typed Sg αs t τ Ht).
    + exact IH.
Qed.

(* ================================================================== *)
(** ** I_map: lift an algebraic morphism to AxCl                       *)
(* ================================================================== *)

Definition I_map_rep {Sg : Signature} (αs βs : list Sg.(sg_ty))
    (f : Cl Sg ⟦ αs, βs ⟧) : AxClMor Sg (I_obj αs) (I_obj βs) :=
  {| axcl_term  := tr_terms αs f.(clmor_terms);
     axcl_typed := tr_terms_typed Sg αs βs f.(clmor_terms) f.(clmor_typed); |}.

(** I on morphisms (quotient version). *)
Definition I_map {Sg : Signature}
    (αs βs : list Sg.(sg_ty))
    (f : Cl Sg ⟦ αs, βs ⟧) :
    AxCl Sg ⟦ I_obj αs, I_obj βs ⟧ :=
  mk_q (I_map_rep αs βs f).

(* ================================================================== *)
(** ** I_fmap_id: I preserves identity                                  *)
(* ================================================================== *)

(** Iterated unpack of [M] via [αs]: list of projections of [M]. *)
Definition unpack_of {Sg : Signature} (αs : list (AxType Sg))
    (M : AxTerm Sg) : list (AxTerm Sg) :=
  List.map (fun i => proj_at αs i M) (List.seq 0 (length αs)).

Lemma map_seq_S {A : Type} (f : nat -> A) (start n : nat) :
    List.map f (List.seq (S start) n) =
    List.map (fun i => f (S i)) (List.seq start n).
Proof.
  revert start. induction n as [|n IH]; intro start.
  - reflexivity.
  - simpl. f_equal. apply IH.
Qed.

(** Unpack of [α :: α' :: αs'] applied to M peels off [ax_fst M] then
    proceeds with [α' :: αs'] on [ax_snd M]. *)
Lemma unpack_of_cons_cons (Sg : Signature) (α α' : AxType Sg)
    (αs : list (AxType Sg)) (M : AxTerm Sg) :
    unpack_of (α :: α' :: αs) M =
    ax_fst M :: unpack_of (α' :: αs) (ax_snd M).
Proof.
  unfold unpack_of.
  change (length (α :: α' :: αs)) with (S (length (α' :: αs))).
  change (List.seq 0 (S (length (α' :: αs))))
    with (0 :: List.seq 1 (length (α' :: αs))).
  cbn [List.map].
  change (proj_at (α :: α' :: αs) 0 M) with (ax_fst M).
  f_equal.
  rewrite map_seq_S.
  apply List.map_ext_in. intros i _.
  cbn [proj_at]. reflexivity.
Qed.

(** Pack-unpack identity (η-pair) for the non-singleton case. *)
Lemma pack_unpack_eta_nonempty (Sg : Signature) (Γ : list (AxType Sg)) :
    forall (αs : list (AxType Sg)) (M : AxTerm Sg),
      αs <> [] ->
      AxHasType Sg Γ M (ax_iter_prod αs) ->
      AxThEq Sg [] Γ (pack (unpack_of αs M)) M (ax_iter_prod αs).
Proof.
  intro αs.
  induction αs as [|α αs' IH]; intros M Hne HM.
  - exfalso. apply Hne. reflexivity.
  - destruct αs' as [|α' αs''].
    + (* αs = [α], singleton *)
      unfold unpack_of. simpl. apply axeq_refl. exact HM.
    + (* αs = α :: α' :: αs'' *)
      rewrite unpack_of_cons_cons.
      change (ax_iter_prod (α :: α' :: αs''))
        with (ax_prod α (ax_iter_prod (α' :: αs''))) in HM.
      change (ax_iter_prod (α :: α' :: αs''))
        with (ax_prod α (ax_iter_prod (α' :: αs''))).
      change (pack (ax_fst M :: unpack_of (α' :: αs'') (ax_snd M)))
        with (ax_pair (ax_fst M) (pack (unpack_of (α' :: αs'') (ax_snd M)))).
      apply (axeq_trans Sg [] Γ
               (ax_pair (ax_fst M) (pack (unpack_of (α' :: αs'') (ax_snd M))))
               (ax_pair (ax_fst M) (ax_snd M))
               M
               (ax_prod α (ax_iter_prod (α' :: αs'')))).
      * apply axeq_pair.
        -- apply axeq_refl.
           apply (ax_ht_fst Sg Γ M α (ax_iter_prod (α' :: αs''))).
           exact HM.
        -- apply IH.
           ++ discriminate.
           ++ apply (ax_ht_snd Sg Γ M α (ax_iter_prod (α' :: αs''))).
              exact HM.
      * apply axeq_eta_prod. exact HM.
Qed.

(** [tr_term αs (t_var i) = proj_at (map ax_ground αs) i (ax_var 0)]
    when [i < length αs]. *)
Lemma nth_error_seq_lt (start n i : nat) :
    (i < n)%nat ->
    List.nth_error (List.seq start n) i = Some (start + i).
Proof.
  revert start i. induction n as [|n IH]; intros start i Hi.
  - lia.
  - destruct i as [|i'].
    + simpl. f_equal. lia.
    + simpl. rewrite IH by lia. f_equal. lia.
Qed.

Lemma tr_term_var (Sg : Signature) (αs : list Sg.(sg_ty)) (i : nat) :
    (i < length αs)%nat ->
    tr_term αs (t_var i) =
    proj_at (List.map ax_ground αs) i (ax_var 0).
Proof.
  intro Hi. unfold tr_term, atom, unpack.
  cbn [ax_subst].
  rewrite List.nth_error_map.
  rewrite (nth_error_seq_lt 0 (length αs) i Hi). cbn.
  reflexivity.
Qed.

(** Map of tr_term over the identity substitution gives the unpack list. *)
Lemma tr_terms_id_sub (Sg : Signature) (αs : list Sg.(sg_ty)) :
    List.map (tr_term αs) (id_sub Sg (length αs)) =
    unpack_of (List.map ax_ground αs) (ax_var 0).
Proof.
  unfold id_sub, unpack_of.
  rewrite List.map_map.
  assert (Hlen : length αs = length (List.map ax_ground αs)).
  { rewrite List.length_map. reflexivity. }
  rewrite Hlen.
  apply List.map_ext_in. intros i Hi.
  apply List.in_seq in Hi. destruct Hi as [_ Hi].
  apply tr_term_var. rewrite List.length_map in Hi. exact Hi.
Qed.

(** I preserves identity.  The empty-context case ([αs = []]) requires
    unit-η in [AxThEq] which is NOT in Syntax.v; we fall back to
    [axcl_terminal_unique] (an Axiom in ClassifyingCategory.v that
    encapsulates exactly this missing rule).  The non-empty cases are
    discharged via the [η-pair] derivation [pack_unpack_eta_nonempty]. *)
Lemma I_fmap_id : forall {Sg : Signature} (αs : list Sg.(sg_ty)),
    I_map αs αs ((Cl Sg).(id) αs) = (AxCl Sg).(id) (I_obj αs).
Proof.
  intros Sg αs.
  destruct αs as [|α0 αs0].
  - (* αs = [], so I_obj αs = ax_unit and both sides land in
       AxCl Sg ⟦ ax_unit, ax_unit ⟧ — use terminal uniqueness. *)
    transitivity (axcl_to_unit Sg ax_unit).
    + apply axcl_terminal_unique.
    + symmetry. apply axcl_terminal_unique.
  - (* αs = α0 :: αs0, non-empty *)
    set (αs := α0 :: αs0).
    unfold I_map, I_map_rep.
    cbn [ClassifyingCat id cl_id clmor_terms].
    unfold axcl_id.
    apply mk_q_eq_iff.
    unfold AxClMor_eq, axcl_id_rep. cbn [axcl_term].
    unfold tr_terms.
    rewrite tr_terms_id_sub.
    unfold I_obj.
    assert (Hne : List.map ax_ground αs <> []).
    { unfold αs. simpl. discriminate. }
    apply pack_unpack_eta_nonempty.
    + exact Hne.
    + apply ax_ht_var. reflexivity.
Qed.

(* ================================================================== *)
(** ** I_fmap_comp: I preserves composition                             *)
(* ================================================================== *)

(** A custom induction principle for [Term Sg] that handles the
    [t_app] case via [Forall (P ∘ argument)]. *)
Lemma Term_ind_full (Sg : Signature) (P : Term Sg -> Prop) :
    (forall n, P (t_var n)) ->
    (forall (f : Sg.(sg_fun)) (args : list (Term Sg)),
        Forall P args -> P (t_app f args)) ->
    forall t, P t.
Proof.
  intros Hvar Happ.
  fix IH 1.
  intro t. destruct t as [n | f args].
  - apply Hvar.
  - apply Happ.
    induction args as [|a args' IHargs].
    + constructor.
    + constructor.
      * apply IH.
      * exact IHargs.
Qed.

(** The atom embedding commutes with substitution.  Stated for typed terms
    so the out-of-range branches don't bite. *)
Lemma atom_subst (Sg : Signature) (Γ : list Sg.(sg_ty))
    (sub : list (Term Sg)) :
    forall (t : Term Sg) (Γ' : list Sg.(sg_ty)) (τ : Sg.(sg_ty)),
      Forall2 (HasType Sg Γ) sub Γ' ->
      HasType Sg Γ' t τ ->
      atom (subst_term Sg sub t) =
      ax_subst (List.map atom sub) (atom t).
Proof.
  intro t.
  induction t as [n | fn args IHargs] using (Term_ind_full Sg);
    intros Γ' τ Hsub Ht.
  - inversion Ht as [n0 τ0 Hn0 | ]; subst.
    cbn [atom subst_term ax_subst].
    rewrite List.nth_error_map.
    destruct (Forall2_nth_error_l _ _ _ Hsub n τ Hn0) as [t' [Ht' _]].
    rewrite Ht'. simpl. reflexivity.
  - inversion Ht as [|fn0 args0 Hargs0 Efn0]; subst.
    simpl. f_equal.
    rewrite List.map_map.
    clear Ht.
    generalize dependent (Sg.(sg_dom) fn).
    induction IHargs as [|a args' Ha IHa IHrest]; intros dom Hargs.
    + inversion Hargs. reflexivity.
    + inversion Hargs as [|a' σ args0' dom' Ha' Hrest Ea Edom]; subst.
      simpl. f_equal.
      * exact (Ha _ σ Hsub Ha').
      * exact (IHrest _ Hrest).
Qed.

(** Substitution distributes over [proj_at]. *)
Lemma ax_subst_proj_at (Sg : Signature) (sub : list (AxTerm Sg)) :
    forall (αs : list (AxType Sg)) (i : nat) (M : AxTerm Sg),
      ax_subst sub (proj_at αs i M) = proj_at αs i (ax_subst sub M).
Proof.
  intro αs.
  induction αs as [|α αs' IH]; intros i M.
  - reflexivity.
  - destruct αs' as [|α' αs''].
    + reflexivity.
    + change (proj_at (α :: α' :: αs'') i ?N)
        with (match i with
              | 0   => ax_fst N
              | S j => proj_at (α' :: αs'') j (ax_snd N)
              end).
      destruct i as [|j].
      * reflexivity.
      * rewrite IH. reflexivity.
Qed.

(** β-pair on the [pack] structure. *)
Lemma proj_at_pack (Sg : Signature) (Γ : list (AxType Sg)) :
    forall (αs : list (AxType Sg)) (Ms : list (AxTerm Sg))
           (i : nat) (M : AxTerm Sg) (τ : AxType Sg),
      Forall2 (AxHasType Sg Γ) Ms αs ->
      List.nth_error Ms i = Some M ->
      List.nth_error αs i = Some τ ->
      AxThEq Sg [] Γ (proj_at αs i (pack Ms)) M τ.
Proof.
  intro αs.
  induction αs as [|α αs' IH]; intros Ms i M τ Hf HMi Hαi.
  - destruct i; discriminate.
  - inversion Hf as [|M0 α0 Ms0 αs0 HM0 Hf' EM Eα]; subst.
    destruct αs' as [|α' αs''].
    + (* αs = [α], singleton *)
      inversion Hf'. subst.
      destruct i as [|i].
      * simpl in HMi, Hαi. injection HMi as <-. injection Hαi as <-.
        simpl. apply axeq_refl. exact HM0.
      * destruct i; discriminate.
    + (* αs = α :: α' :: αs'' *)
      inversion Hf' as [|M0' α0' Ms0' αs0' HM' Hf'' EM' Eα']; subst.
      change (pack (M0 :: M0' :: Ms0'))
        with (ax_pair M0 (pack (M0' :: Ms0'))).
      destruct i as [|j].
      * simpl in HMi, Hαi. injection HMi as <-. injection Hαi as <-.
        change (proj_at (α :: α' :: αs'') 0 ?N) with (ax_fst N).
        apply axeq_beta_fst with (β := ax_iter_prod (α' :: αs'')).
        -- exact HM0.
        -- apply pack_typed. constructor; assumption.
      * change (proj_at (α :: α' :: αs'') (S j) ?N)
          with (proj_at (α' :: αs'') j (ax_snd N)).
        simpl in HMi, Hαi.
        (* Step 1: ax_snd (ax_pair M0 P) ~~ P, then proj_at congruence. *)
        assert (Hsnd : AxThEq Sg [] Γ
                  (ax_snd (ax_pair M0 (pack (M0' :: Ms0'))))
                  (pack (M0' :: Ms0'))
                  (ax_iter_prod (α' :: αs''))).
        { apply axeq_beta_snd with (α := α).
          - exact HM0.
          - apply pack_typed. constructor; assumption. }
        (* Step 2: proj_at on either side via ax_subst_cong on a singleton sub. *)
        assert (Hcong : AxThEq Sg [] Γ
                  (proj_at (α' :: αs'') j (ax_snd (ax_pair M0 (pack (M0' :: Ms0')))))
                  (proj_at (α' :: αs'') j (pack (M0' :: Ms0')))
                  τ).
        { (* congruence: rewrite both as ax_subst of the var-form *)
          set (P1 := ax_snd (ax_pair M0 (pack (M0' :: Ms0')))).
          set (P2 := pack (M0' :: Ms0')).
          assert (HP : AxThEq Sg [] Γ P1 P2 (ax_iter_prod (α' :: αs''))).
          { exact Hsnd. }
          (* Express both projections as ax_subst [P_k] (proj_at (α'::αs'') j (ax_var 0)). *)
          assert (E1 : proj_at (α' :: αs'') j P1 =
                       ax_subst [P1] (proj_at (α' :: αs'') j (ax_var 0))).
          { rewrite ax_subst_proj_at. cbn [ax_subst]. reflexivity. }
          assert (E2 : proj_at (α' :: αs'') j P2 =
                       ax_subst [P2] (proj_at (α' :: αs'') j (ax_var 0))).
          { rewrite ax_subst_proj_at. cbn [ax_subst]. reflexivity. }
          rewrite E1, E2.
          apply (ax_subst_cong Sg [] Γ
                   [ax_iter_prod (α' :: αs'')] [P1] [P2]
                   (proj_at (α' :: αs'') j (ax_var 0))
                   (proj_at (α' :: αs'') j (ax_var 0)) τ).
          - constructor.
            + apply (ax_ht_snd Sg Γ (ax_pair M0 (pack (M0' :: Ms0'))) α
                       (ax_iter_prod (α' :: αs''))).
              apply ax_ht_pair.
              * exact HM0.
              * apply pack_typed. constructor; assumption.
            + constructor.
          - constructor.
            + apply pack_typed. constructor; assumption.
            + constructor.
          - intros k βk s s' Hβk Hsk Hsk'.
            destruct k as [|k].
            + simpl in Hβk. injection Hβk as <-.
              simpl in Hsk. injection Hsk as <-.
              simpl in Hsk'. injection Hsk' as <-.
              exact HP.
            + destruct k; simpl in Hβk; discriminate.
          - apply axeq_refl.
            apply (proj_at_typed Sg [ax_iter_prod (α' :: αs'')]
                     (α' :: αs'') j τ (ax_var 0) Hαi).
            apply ax_ht_var. reflexivity. }
        (* Now combine: LHS ~~ proj_at j P2 ~~ M *)
        apply (axeq_trans Sg [] Γ
                 (proj_at (α' :: αs'') j (ax_snd (ax_pair M0 (pack (M0' :: Ms0')))))
                 (proj_at (α' :: αs'') j (pack (M0' :: Ms0')))
                 M τ).
        -- exact Hcong.
        -- apply (IH (M0' :: Ms0') j M τ).
           ++ constructor; assumption.
           ++ exact HMi.
           ++ exact Hαi.
Qed.

(** Translation of a list of typed terms is well-typed at the
    iterated-product level, given as a Forall2 (used in tr_term_subst). *)
Lemma map_tr_term_typed (Sg : Signature) (αs βs : list Sg.(sg_ty))
    (ts : list (Term Sg)) :
    Forall2 (HasType Sg αs) ts βs ->
    Forall2 (AxHasType Sg [I_obj αs])
            (List.map (tr_term αs) ts)
            (List.map ax_ground βs).
Proof.
  intro H. induction H as [|t σ ts' βs' Ht Hts IH].
  - constructor.
  - simpl. constructor.
    + apply tr_term_typed. exact Ht.
    + exact IH.
Qed.

(** Translation commutes with substitution at the term level (modulo AxThEq). *)
Lemma tr_term_subst (Sg : Signature) (αs βs : list Sg.(sg_ty))
    (f_ts : list (Term Sg)) (Hft : Forall2 (HasType Sg αs) f_ts βs)
    (t : Term Sg) (τ : Sg.(sg_ty))
    (Ht : HasType Sg βs t τ) :
    AxThEq Sg [] [I_obj αs]
      (tr_term αs (subst_term Sg f_ts t))
      (ax_subst [tr_terms αs f_ts] (tr_term βs t))
      (ax_ground τ).
Proof.
  unfold tr_term.
  rewrite (atom_subst Sg αs f_ts t βs τ Hft Ht).
  (* LHS = ax_subst (unpack αs) (ax_subst (map atom f_ts) (atom t))
     RHS = ax_subst [tr_terms αs f_ts] (ax_subst (unpack βs) (atom t)) *)
  (* Apply ax_subst_comp on both sides to reduce to ax_subst sub_LHS / sub_RHS (atom t). *)
  assert (Hatom_ft : Forall2 (AxHasType Sg (List.map ax_ground αs))
                              (List.map atom f_ts)
                              (List.map ax_ground βs)).
  { clear t τ Ht.
    induction Hft as [|t' σ ts' βs' Ht' Hts' IHts].
    - constructor.
    - simpl. constructor.
      + apply atom_preserves_type. exact Ht'.
      + exact IHts. }
  assert (Hatom_t : AxHasType Sg (List.map ax_ground βs) (atom t) (ax_ground τ)).
  { apply atom_preserves_type. exact Ht. }
  assert (Hlen_atom_ft : length (List.map atom f_ts) = length (List.map ax_ground βs)).
  { rewrite !List.length_map. exact (Forall2_length Hft). }
  rewrite (ax_subst_comp Sg (List.map ax_ground βs)
             (unpack αs) (List.map atom f_ts) (atom t) (ax_ground τ)
             Hlen_atom_ft Hatom_t).
  (* Now LHS becomes: ax_subst (map (ax_subst (unpack αs)) (map atom f_ts)) (atom t)
     RHS:             ax_subst [tr_terms αs f_ts] (ax_subst (unpack βs) (atom t)) *)
  (* Apply ax_subst_comp on RHS with M = atom t in context (map ax_ground βs). *)
  assert (Hunpack_β : Forall2 (AxHasType Sg [I_obj βs])
                              (unpack βs) (List.map ax_ground βs)).
  { apply unpack_typed. }
  assert (Hlen_unpack_β : length (unpack βs) = length (List.map ax_ground βs)).
  { exact (Forall2_length Hunpack_β). }
  rewrite (ax_subst_comp Sg (List.map ax_ground βs)
             [tr_terms αs f_ts] (unpack βs) (atom t) (ax_ground τ)
             Hlen_unpack_β Hatom_t).
  (* Now both sides are ax_subst sub_X (atom t). Apply ax_subst_cong with Hatom_t. *)
  apply (ax_subst_cong Sg [] [I_obj αs] (List.map ax_ground βs)
           (List.map (ax_subst (unpack αs)) (List.map atom f_ts))
           (List.map (ax_subst [tr_terms αs f_ts]) (unpack βs))
           (atom t) (atom t) (ax_ground τ)).
  - (* Forall2 typing of LHS sub *)
    rewrite List.map_map.
    (* Goal: Forall2 (AxHasType Sg [I_obj αs])
              (map (fun x => ax_subst (unpack αs) (atom x)) f_ts)
              (map ax_ground βs).
       Build pointwise from Hft. *)
    clear Hatom_t Hatom_ft Hlen_atom_ft Hunpack_β Hlen_unpack_β Ht t τ.
    induction Hft as [|t' σ ts' βs' Ht' Hts' IH'].
    + simpl. constructor.
    + simpl. constructor.
      * apply (ax_subst_preserves_type Sg [I_obj αs] (List.map ax_ground αs)
                 (unpack αs) (unpack_typed Sg αs)).
        apply atom_preserves_type. exact Ht'.
      * exact IH'.
  - (* Forall2 typing of RHS sub *)
    assert (HtrFs : AxHasType Sg [I_obj αs] (tr_terms αs f_ts) (I_obj βs)).
    { apply tr_terms_typed. exact Hft. }
    clear Hatom_t Hatom_ft Hlen_atom_ft Hlen_unpack_β Ht t τ.
    (* Goal: Forall2 (AxHasType Sg [I_obj αs])
              (map (ax_subst [tr_terms αs f_ts]) (unpack βs))
              (map ax_ground βs). *)
    assert (Goal2 : forall xs ys,
              Forall2 (AxHasType Sg [I_obj βs]) xs ys ->
              Forall2 (AxHasType Sg [I_obj αs])
                      (List.map (ax_subst [tr_terms αs f_ts]) xs) ys).
    { intros xs ys H.
      induction H as [|x β xs' ys' Hx Hrest IHrest].
      - simpl. constructor.
      - simpl. constructor.
        + apply (ax_subst_preserves_type Sg [I_obj αs] [I_obj βs]
                   [tr_terms αs f_ts]).
          * constructor; [exact HtrFs|constructor].
          * exact Hx.
        + exact IHrest. }
    apply Goal2. apply unpack_typed.
  - (* Pointwise AxThEq for the two substitutions *)
    intros i βk s s' Hβk Hsi Hsi'.
    (* βk = ax_ground (βs[i]) *)
    rewrite List.nth_error_map in Hβk.
    destruct (List.nth_error βs i) as [β_i|] eqn:Eβi; [|discriminate].
    injection Hβk as <-.
    (* s = (map (ax_subst (unpack αs)) (map atom f_ts))[i]
         = ax_subst (unpack αs) (atom (f_ts[i])) *)
    rewrite List.map_map in Hsi.
    rewrite List.nth_error_map in Hsi.
    destruct (List.nth_error f_ts i) as [t_i|] eqn:Eti; [|discriminate].
    injection Hsi as <-.
    (* s' = (map (ax_subst [tr_terms αs f_ts]) (unpack βs))[i]
          = ax_subst [tr_terms αs f_ts] (proj_at (map ax_ground βs) i (ax_var 0)) *)
    unfold unpack in Hsi'.
    rewrite List.map_map in Hsi'.
    rewrite List.nth_error_map in Hsi'.
    rewrite (nth_error_seq_lt 0 (length βs) i) in Hsi'.
    + cbn in Hsi'. injection Hsi' as <-.
      rewrite ax_subst_proj_at. cbn [ax_subst].
      (* Goal: AxThEq [] [I_obj αs]
                 (ax_subst (unpack αs) (atom t_i))
                 (proj_at (map ax_ground βs) i (tr_terms αs f_ts))
                 (ax_ground β_i) *)
      apply axeq_sym.
      (* Use proj_at_pack. *)
      set (Ms := List.map (tr_term αs) f_ts).
      change (tr_terms αs f_ts) with (pack Ms).
      assert (HMs : Forall2 (AxHasType Sg [I_obj αs]) Ms (List.map ax_ground βs)).
      { apply map_tr_term_typed. exact Hft. }
      assert (HMsi : List.nth_error Ms i =
                     Some (tr_term αs t_i)).
      { unfold Ms. rewrite List.nth_error_map, Eti. reflexivity. }
      apply (proj_at_pack Sg [I_obj αs] (List.map ax_ground βs) Ms i
               (tr_term αs t_i) (ax_ground β_i) HMs HMsi).
      rewrite List.nth_error_map, Eβi. reflexivity.
    + apply List.nth_error_Some. rewrite Eβi. discriminate.
  - apply axeq_refl. exact Hatom_t.
Qed.

(** Translation commutes with substitution at the term-list level. *)
Lemma tr_terms_subst (Sg : Signature) (αs βs γs : list Sg.(sg_ty))
    (f_ts g_ts : list (Term Sg))
    (Hft : Forall2 (HasType Sg αs) f_ts βs)
    (Hgt : Forall2 (HasType Sg βs) g_ts γs) :
    AxThEq Sg [] [I_obj αs]
      (tr_terms αs (subst_list Sg f_ts g_ts))
      (ax_subst [tr_terms αs f_ts] (tr_terms βs g_ts))
      (I_obj γs).
Proof.
  unfold tr_terms, subst_list.
  rewrite List.map_map.
  (* Goal: AxThEq Sg [] [I_obj αs]
            (pack (map (tr_term αs ∘ subst_term Sg f_ts) g_ts))
            (ax_subst [tr_terms αs f_ts] (pack (map (tr_term βs) g_ts)))
            (I_obj γs) *)
  unfold I_obj.
  generalize dependent γs.
  induction g_ts as [|g g_ts' IHg]; intros γs Hgt.
  - inversion Hgt. subst. simpl.
    apply axeq_refl. apply ax_ht_tt.
  - destruct γs as [|γ γs']; [inversion Hgt|].
    inversion Hgt as [|g0 γ0 g_ts0 γs0 Hg Hgt' Eg Eγ]; subst.
    destruct g_ts' as [|g' g_ts''].
    + (* g_ts = [g] (singleton) *)
      inversion Hgt'. subst.
      cbn [List.map pack].
      change (List.map ax_ground [γ]) with [ax_ground γ].
      change (ax_iter_prod [ax_ground γ]) with (ax_ground γ).
      apply tr_term_subst with (βs := βs); assumption.
    + (* g_ts = g :: g' :: g_ts'' (≥2) *)
      inversion Hgt' as [|g0' γ0' g_ts0' γs0' Hg' Hgt'' Eg' Eγ']; subst.
      cbn [List.map].
      change (pack (?M :: ?M' :: ?Ms))
        with (ax_pair M (pack (M' :: Ms))).
      change (List.map ax_ground (γ :: γ0' :: γs0'))
        with (ax_ground γ :: List.map ax_ground (γ0' :: γs0')).
      change (ax_iter_prod (ax_ground γ :: List.map ax_ground (γ0' :: γs0')))
        with (ax_prod (ax_ground γ) (ax_iter_prod (List.map ax_ground (γ0' :: γs0')))).
      cbn [ax_subst].
      apply axeq_pair.
      * apply tr_term_subst with (βs := βs); assumption.
      * specialize (IHg (γ0' :: γs0') Hgt').
        cbn [List.map] in IHg.
        change (pack (?M' :: ?Ms))
          with (match Ms with [] => M' | _ => ax_pair M' (pack Ms) end).
        (* simplification *)
        change (List.map ax_ground (γ0' :: γs0'))
          with (ax_ground γ0' :: List.map ax_ground γs0') in IHg.
        change (ax_iter_prod (ax_ground γ0' :: List.map ax_ground γs0'))
          with (ax_iter_prod (List.map ax_ground (γ0' :: γs0'))) in IHg.
        exact IHg.
Qed.

Lemma I_fmap_comp : forall {Sg : Signature}
    (αs βs γs : list Sg.(sg_ty))
    (g : Cl Sg ⟦ βs, γs ⟧) (f : Cl Sg ⟦ αs, βs ⟧),
    I_map αs γs (g ∘ f) = I_map βs γs g ∘ I_map αs βs f.
Proof.
  intros Sg αs βs γs g f.
  unfold I_map.
  cbn [ClassifyingCat comp cl_comp clmor_terms].
  cbn [AxCl comp].
  rewrite axcl_comp_mk.
  apply mk_q_eq_iff.
  unfold AxClMor_eq, axcl_comp_rep, I_map_rep. cbn [axcl_term].
  apply tr_terms_subst with (βs := βs).
  - exact f.(clmor_typed).
  - exact g.(clmor_typed).
Qed.

Definition I_functor (Sg : Signature) : Functor (Cl Sg) (AxCl Sg) :=
  Build_Functor (Cl Sg) (AxCl Sg)
    I_obj
    (fun αs βs f => I_map αs βs f)
    (@I_fmap_id Sg)
    (@I_fmap_comp Sg).

(** ** Proposition 4.10.2

    The functor I : Cl(Th) → Cl(Th') presents Cl(Th') as the
    relatively free CCC generated by Cl(Th).

    HISTORY.  The α-A.2 round (2026-05-01) documented a STRUCTURAL
    OBSTRUCTION in the original strict-equality version of
    [FPtoCCCFunctor]: that record demanded
        F ## (αs ++ βs) = F ## αs ×ax F ## βs
    which is false for [I_obj] (e.g. αs = βs = [] would force
    [ax_unit = ax_prod ax_unit ax_unit], refutable by [discriminate]
    on the [AxType] inductive).

    α-A.2.next (2026-05-01).  The [FPtoCCCFunctor] record above has
    been LOOSENED to require [Isomorphism] witnesses in place of
    strict equality, removing the structural obstruction.

    Under the loosened record, [I_fp_functor] is structurally
    constructible:
      - [fptoccc_iso_term]: trivial — both sides definitionally
        equal to [ax_unit], so [iso_refl ax_unit] suffices.
      - [fptoccc_iso_prod]: requires constructing an
        [AxClMor_q]-level isomorphism between
            I_obj (αs ++ βs)  and  ax_prod (I_obj αs) (I_obj βs)
        via [pack] / [unpack_of] mediation; soundness follows from
        the same η-laws ([axeq_eta_prod], [axeq_pair]) used in
        [pack_unpack_eta_nonempty].

    The morphism-level content [I_map] / [I_fmap_id] / [I_fmap_comp]
    is fully discharged as Lemmas above.  The remaining items below
    are:
      - [I_fp_functor]: Parameter, awaiting the explicit prod-iso
        construction (clean follow-up scoped in REFACTOR_PLAN.org
        Task A.2.next-prod).  No longer structurally blocked.
      - [classifying_CCC_is_relatively_free]: Axiom, awaiting the
        universal-extension content (independent of the iso
        loosening; this is the "free CCC on a FP category" universal
        property whose construction is sketched in the gluing
        development of GluingSetup.v / Conservativity.v).
    Both are now consistent under the iso-loosened record. *)

(* ================================================================== *)
(** ** Prod-iso for I_fp_functor [α R10 — 2026-05-01, Task A.2.next-prod]

    The strict-equality form of the prod-preservation field was
    unprovable (αs=βs=[] forces [ax_unit = ax_prod ax_unit ax_unit]);
    the iso-loosened form (delivered in α R9) requires constructing a
    categorical iso

        I_obj (αs ++ βs)  ≅  I_obj αs ×ax I_obj βs    in AxCl Sg.

    This section delivers the iso witness fully:
    - [pack_unpack_eta] — universal η-pair lifting (covers the empty
      case via [axeq_eta_unit]).
    - [unpack_of_typed], [pack_unpack_of_typed] — typing helpers.
    - [block_typed_alpha], [block_typed_beta] — typing of the αs-/βs-
      block packs of forward projections.
    - [prod_iso_fwd_term], [prod_iso_bwd_term] — explicit term-level
      witnesses, [pack]/[unpack_of]-mediated.
    - [prod_iso_fwd_typed], [prod_iso_bwd_typed] — their typings.
    - [prod_iso_fwd_rep], [prod_iso_bwd_rep] — packaged [AxClMor]
      representatives.
    - [pack_cong] — pointwise-AxThEq congruence for [pack].
    - [ax_subst_pack], [ax_subst_unpack_of] — distribution helpers.
    - [prod_iso_fwd_bwd_eq], [prod_iso_bwd_fwd_eq] — DISCHARGED
      AxThEq round-trip equations.  These lift to AxCl-level
      composition equations [prod_iso_fwd_bwd_AxCl] /
      [prod_iso_bwd_fwd_AxCl].
    - [I_prod_iso], [I_term_iso] — assembled categorical iso witnesses.
    - [I_fp_functor] — DEFINITION (no longer Parameter), assembled
      from [I_functor], [I_term_iso], [I_prod_iso].  [Print
      Assumptions I_fp_functor] yields the standard axiom set:
      [propositional_extensionality], [functional_extensionality_dep],
      [ax_subst_cong], [ax_subst_comp].  No new admits introduced. *)

(** Universal pack/unpack-η: includes [αs = []] case via [axeq_eta_unit]. *)
Lemma pack_unpack_eta (Sg : Signature) (Γ : list (AxType Sg)) :
    forall (αs : list (AxType Sg)) (M : AxTerm Sg),
      AxHasType Sg Γ M (ax_iter_prod αs) ->
      AxThEq Sg [] Γ (pack (unpack_of αs M)) M (ax_iter_prod αs).
Proof.
  intros αs M HM.
  destruct αs as [|α αs'].
  - unfold unpack_of. simpl.
    apply axeq_sym. apply axeq_eta_unit. exact HM.
  - apply pack_unpack_eta_nonempty; [discriminate|exact HM].
Qed.

Lemma length_unpack_of_inline {Sg : Signature} (αs : list (AxType Sg)) (M : AxTerm Sg) :
    length (unpack_of αs M) = length αs.
Proof.
  unfold unpack_of. rewrite List.length_map, List.length_seq. reflexivity.
Qed.

(** [unpack_of] of a typed term is a typed substitution at αs. *)
Lemma unpack_of_typed (Sg : Signature) (Γ : list (AxType Sg))
    (αs : list (AxType Sg)) (M : AxTerm Sg) :
    AxHasType Sg Γ M (ax_iter_prod αs) ->
    Forall2 (AxHasType Sg Γ) (unpack_of αs M) αs.
Proof.
  intro HM. unfold unpack_of.
  assert (Hgen : forall (k : nat) (αs0 : list (AxType Sg)),
             (forall i τ, List.nth_error αs0 i = Some τ ->
                          List.nth_error αs (k + i) = Some τ) ->
             Forall2 (AxHasType Sg Γ)
                     (List.map (fun i => proj_at αs i M) (List.seq k (length αs0)))
                     αs0).
  { intros k αs0. revert k.
    induction αs0 as [|τ αs0' IH']; intros k Hnth.
    - simpl. constructor.
    - simpl. constructor.
      + apply (proj_at_typed Sg Γ αs k τ M).
        * specialize (Hnth 0 τ eq_refl). rewrite Nat.add_0_r in Hnth. exact Hnth.
        * exact HM.
      + apply (IH' (S k)).
        intros i τ' Hi'. specialize (Hnth (S i) τ' Hi').
        replace (S k + i) with (k + S i) by lia.
        exact Hnth. }
  apply (Hgen 0 αs).
  intros i τ Hi. simpl. exact Hi.
Qed.

(** Typing of the αs-block of forward projections. *)
Lemma block_typed_alpha (Sg : Signature) (αs βs : list Sg.(sg_ty)) :
    AxHasType Sg [I_obj (αs ++ βs)]
      (pack (List.map
              (fun i => proj_at (List.map ax_ground (αs ++ βs)) i (ax_var 0))
              (List.seq 0 (length αs))))
      (I_obj αs).
Proof.
  apply pack_typed.
  set (sortAB := List.map ax_ground (αs ++ βs)).
  set (sortA  := List.map ax_ground αs).
  unfold I_obj.
  assert (Hv0 : AxHasType Sg [I_obj (αs ++ βs)] (ax_var 0)
                  (ax_iter_prod sortAB)).
  { apply ax_ht_var. reflexivity. }
  assert (HlenA : length αs = length sortA).
  { unfold sortA. symmetry. apply List.length_map. }
  rewrite HlenA.
  assert (Hgen : forall (k : nat) (L0 : list (AxType Sg)),
             (forall i τ, List.nth_error L0 i = Some τ ->
                          List.nth_error sortAB (k + i) = Some τ) ->
             Forall2 (AxHasType Sg [I_obj (αs ++ βs)])
                     (List.map (fun i => proj_at sortAB i (ax_var 0))
                               (List.seq k (length L0)))
                     L0).
  { intros k L0. revert k.
    induction L0 as [|τ L0' IH']; intros k Hnth.
    - simpl. constructor.
    - simpl. constructor.
      + apply (proj_at_typed Sg [I_obj (αs ++ βs)] sortAB k τ (ax_var 0)).
        * specialize (Hnth 0 τ eq_refl). rewrite Nat.add_0_r in Hnth. exact Hnth.
        * exact Hv0.
      + apply (IH' (S k)).
        intros i τ' Hi'. specialize (Hnth (S i) τ' Hi').
        replace (S k + i) with (k + S i) by lia.
        exact Hnth. }
  apply (Hgen 0 sortA).
  intros i τ Hi.
  assert (HiA : i < length sortA).
  { apply List.nth_error_Some. intro Hcontra.
    rewrite Hi in Hcontra. discriminate. }
  unfold sortAB. rewrite List.map_app.
  fold sortA.
  rewrite List.nth_error_app1 by exact HiA.
  simpl. exact Hi.
Qed.

(** Typing of the βs-block of forward projections. *)
Lemma block_typed_beta (Sg : Signature) (αs βs : list Sg.(sg_ty)) :
    AxHasType Sg [I_obj (αs ++ βs)]
      (pack (List.map
              (fun i => proj_at (List.map ax_ground (αs ++ βs)) i (ax_var 0))
              (List.seq (length αs) (length βs))))
      (I_obj βs).
Proof.
  apply pack_typed.
  set (sortAB := List.map ax_ground (αs ++ βs)).
  set (sortB  := List.map ax_ground βs).
  unfold I_obj.
  assert (Hv0 : AxHasType Sg [I_obj (αs ++ βs)] (ax_var 0)
                  (ax_iter_prod sortAB)).
  { apply ax_ht_var. reflexivity. }
  assert (HlenB : length βs = length sortB).
  { unfold sortB. symmetry. apply List.length_map. }
  rewrite HlenB.
  assert (HlenA_sortA : length αs = length (List.map ax_ground αs)).
  { symmetry. apply List.length_map. }
  assert (Hgen : forall (k : nat) (L0 : list (AxType Sg)),
             (forall i τ, List.nth_error L0 i = Some τ ->
                          List.nth_error sortAB (length αs + k + i) = Some τ) ->
             Forall2 (AxHasType Sg [I_obj (αs ++ βs)])
                     (List.map (fun i => proj_at sortAB i (ax_var 0))
                               (List.seq (length αs + k) (length L0)))
                     L0).
  { intros k L0. revert k.
    induction L0 as [|τ L0' IH']; intros k Hnth.
    - simpl. constructor.
    - simpl. constructor.
      + apply (proj_at_typed Sg [I_obj (αs ++ βs)] sortAB
                 (length αs + k) τ (ax_var 0)).
        * specialize (Hnth 0 τ eq_refl). rewrite Nat.add_0_r in Hnth.
          exact Hnth.
        * exact Hv0.
      + replace (S (length αs + k)) with (length αs + S k) by lia.
        apply (IH' (S k)).
        intros i τ' Hi'. specialize (Hnth (S i) τ' Hi').
        replace (length αs + S k + i) with (length αs + k + S i) by lia.
        exact Hnth. }
  replace (length αs) with (length αs + 0) at 1 by lia.
  apply (Hgen 0 sortB).
  intros i τ Hi.
  unfold sortAB. rewrite List.map_app.
  rewrite List.nth_error_app2.
  - rewrite <- HlenA_sortA. replace (length αs + 0 + i - length αs) with i by lia.
    simpl. exact Hi.
  - rewrite <- HlenA_sortA. lia.
Qed.

(** Forward representative term. *)
Definition prod_iso_fwd_term {Sg : Signature} (αs βs : list Sg.(sg_ty))
    : AxTerm Sg :=
  let sortAB := List.map ax_ground (αs ++ βs) in
  ax_pair
    (pack (List.map (fun i => proj_at sortAB i (ax_var 0))
                    (List.seq 0 (length αs))))
    (pack (List.map (fun i => proj_at sortAB i (ax_var 0))
                    (List.seq (length αs) (length βs)))).

(** Backward representative term. *)
Definition prod_iso_bwd_term {Sg : Signature} (αs βs : list Sg.(sg_ty))
    : AxTerm Sg :=
  let sortA := List.map ax_ground αs in
  let sortB := List.map ax_ground βs in
  pack (unpack_of sortA (ax_fst (ax_var 0)) ++
        unpack_of sortB (ax_snd (ax_var 0))).

Lemma prod_iso_fwd_typed (Sg : Signature) (αs βs : list Sg.(sg_ty)) :
    AxHasType Sg [I_obj (αs ++ βs)]
      (prod_iso_fwd_term αs βs)
      (I_obj αs ×ax I_obj βs).
Proof.
  unfold prod_iso_fwd_term. apply ax_ht_pair.
  - apply block_typed_alpha.
  - apply block_typed_beta.
Qed.

Lemma prod_iso_bwd_typed (Sg : Signature) (αs βs : list Sg.(sg_ty)) :
    AxHasType Sg [I_obj αs ×ax I_obj βs]
      (prod_iso_bwd_term αs βs)
      (I_obj (αs ++ βs)).
Proof.
  unfold prod_iso_bwd_term, I_obj.
  rewrite List.map_app.
  apply pack_typed.
  apply List.Forall2_app.
  - apply unpack_of_typed.
    apply (ax_ht_fst Sg [I_obj αs ×ax I_obj βs] (ax_var 0)
             (I_obj αs) (I_obj βs)).
    apply ax_ht_var. reflexivity.
  - apply unpack_of_typed.
    apply (ax_ht_snd Sg [I_obj αs ×ax I_obj βs] (ax_var 0)
             (I_obj αs) (I_obj βs)).
    apply ax_ht_var. reflexivity.
Qed.

(** [AxClMor] representatives. *)
Definition prod_iso_fwd_rep {Sg : Signature} (αs βs : list Sg.(sg_ty))
    : AxClMor Sg (I_obj (αs ++ βs)) (I_obj αs ×ax I_obj βs) :=
  {| axcl_term  := prod_iso_fwd_term αs βs;
     axcl_typed := prod_iso_fwd_typed Sg αs βs |}.

Definition prod_iso_bwd_rep {Sg : Signature} (αs βs : list Sg.(sg_ty))
    : AxClMor Sg (I_obj αs ×ax I_obj βs) (I_obj (αs ++ βs)) :=
  {| axcl_term  := prod_iso_bwd_term αs βs;
     axcl_typed := prod_iso_bwd_typed Sg αs βs |}.

(** AxCl-level (quotient) morphisms. *)
Definition prod_iso_fwd {Sg : Signature} (αs βs : list Sg.(sg_ty))
    : AxCl Sg ⟦ I_obj (αs ++ βs), I_obj αs ×ax I_obj βs ⟧ :=
  mk_q (prod_iso_fwd_rep αs βs).

Definition prod_iso_bwd {Sg : Signature} (αs βs : list Sg.(sg_ty))
    : AxCl Sg ⟦ I_obj αs ×ax I_obj βs, I_obj (αs ++ βs) ⟧ :=
  mk_q (prod_iso_bwd_rep αs βs).

(** ** Helpers used by the round-trip equations *)

(** [ax_subst] commutes with [pack] (= map and reassemble). *)
Lemma ax_subst_pack (Sg : Signature) (sub : list (AxTerm Sg))
    (Ms : list (AxTerm Sg)) :
    ax_subst sub (pack Ms) =
    pack (List.map (ax_subst sub) Ms).
Proof.
  induction Ms as [|M Ms IH].
  - reflexivity.
  - destruct Ms as [|M' Ms''].
    + reflexivity.
    + change (pack (M :: M' :: Ms'')) with (ax_pair M (pack (M' :: Ms''))).
      cbn [ax_subst List.map].
      change (pack (ax_subst sub M :: ax_subst sub M'
                    :: List.map (ax_subst sub) Ms''))
        with (ax_pair (ax_subst sub M)
                      (pack (ax_subst sub M' :: List.map (ax_subst sub) Ms''))).
      f_equal.
      change (List.map (ax_subst sub) (M' :: Ms''))
        with (ax_subst sub M' :: List.map (ax_subst sub) Ms'') in IH.
      exact IH.
Qed.

(** [ax_subst] commutes with [unpack_of]. *)
Lemma ax_subst_unpack_of (Sg : Signature) (sub : list (AxTerm Sg))
    (αs : list (AxType Sg)) (M : AxTerm Sg) :
    List.map (ax_subst sub) (unpack_of αs M) =
    unpack_of αs (ax_subst sub M).
Proof.
  unfold unpack_of. rewrite List.map_map.
  apply List.map_ext. intro i.
  apply ax_subst_proj_at.
Qed.

(** Indexed pointwise-AxThEq predicate (avoids [combine] reduction issues). *)
Definition list_axeq_pointwise {Sg : Signature} (Γ : list (AxType Sg))
    (Ms Ms' : list (AxTerm Sg)) (γs : list (AxType Sg)) : Prop :=
  forall (i : nat) (τ : AxType Sg) (M M' : AxTerm Sg),
    List.nth_error γs i = Some τ ->
    List.nth_error Ms i = Some M ->
    List.nth_error Ms' i = Some M' ->
    AxThEq Sg [] Γ M M' τ.

(** Pack-congruence (cleaned formulation). *)
Lemma pack_cong (Sg : Signature) (Γ : list (AxType Sg)) :
    forall (Ms Ms' : list (AxTerm Sg)) (γs : list (AxType Sg)),
      Forall2 (AxHasType Sg Γ) Ms γs ->
      Forall2 (AxHasType Sg Γ) Ms' γs ->
      list_axeq_pointwise Γ Ms Ms' γs ->
      AxThEq Sg [] Γ (pack Ms) (pack Ms') (ax_iter_prod γs).
Proof.
  intros Ms.
  induction Ms as [|M Ms IH]; intros Ms' γs HMs HMs' Hcong.
  - inversion HMs; subst.
    inversion HMs'; subst.
    cbn [pack ax_iter_prod].
    apply axeq_refl. apply ax_ht_tt.
  - destruct Ms' as [|M' Ms''].
    + apply Forall2_length in HMs'. simpl in HMs'.
      apply Forall2_length in HMs. simpl in HMs. lia.
    + inversion HMs as [|? γ ? γs0 HM Hrest E1 E2]; subst.
      inversion HMs' as [|? ? ? ? HM' Hrest']; subst.
      destruct Ms as [|M2 Ms2].
      * (* Ms = [M], so γs0 = []. *)
        inversion Hrest. subst γs0.
        destruct Ms'' as [|M2' Ms2'];
          [|apply Forall2_length in Hrest'; simpl in Hrest'; lia].
        cbn [pack ax_iter_prod].
        apply (Hcong 0 γ M M'); reflexivity.
      * destruct Ms'' as [|M2' Ms2'].
        { apply Forall2_length in Hrest'. simpl in Hrest'.
          apply Forall2_length in Hrest. simpl in Hrest. lia. }
        change (pack (M :: M2 :: Ms2)) with (ax_pair M (pack (M2 :: Ms2))).
        change (pack (M' :: M2' :: Ms2')) with (ax_pair M' (pack (M2' :: Ms2'))).
        inversion Hrest as [|? γ_first ? γs1 HM2 Hrest2 E3 E4]; subst.
        inversion Hrest' as [|? ? ? ? HM2' Hrest2']; subst.
        change (ax_iter_prod (γ :: γ_first :: γs1))
          with (ax_prod γ (ax_iter_prod (γ_first :: γs1))).
        apply axeq_pair.
        -- apply (Hcong 0 γ M M'); reflexivity.
        -- apply IH with (γs := γ_first :: γs1).
           ++ constructor; assumption.
           ++ constructor; assumption.
           ++ intros i τ X X' Hτi HXi HX'i.
              apply (Hcong (S i) τ X X'); cbn; assumption.
Qed.

(** ** Round-trip equations *)

(** [bwd ∘ fwd ~~ id] in AxThEq.

    Substituting [prod_iso_fwd_term αs βs] for var 0 in
    [prod_iso_bwd_term αs βs] yields
    [pack (unpack_of sortA (ax_fst FWD) ++ unpack_of sortB (ax_snd FWD))]
    where FWD = ax_pair PA PB.  By β-pair, this AxThEq-rewrites to
    [pack (unpack_of sortA PA ++ unpack_of sortB PB)].  Each block then
    AxThEq-rewrites pointwise (via [proj_at_pack] applied to PA, PB)
    to [unpack_of sortAB (ax_var 0)] (after combining sortA ++ sortB =
    sortAB by [List.map_app]).  Finally [pack_unpack_eta] on
    [ax_var 0 : I_obj (αs ++ βs)] closes to [ax_var 0]. *)

Lemma prod_iso_bwd_fwd_eq (Sg : Signature) (αs βs : list Sg.(sg_ty)) :
    AxThEq Sg [] [I_obj (αs ++ βs)]
      (ax_subst [prod_iso_fwd_term αs βs] (prod_iso_bwd_term αs βs))
      (ax_var 0)
      (I_obj (αs ++ βs)).
Proof.
  set (Γ := [I_obj (αs ++ βs)]).
  set (sortA := List.map ax_ground αs).
  set (sortB := List.map ax_ground βs).
  set (sortAB := List.map ax_ground (αs ++ βs)).
  assert (HsortAB : sortA ++ sortB = sortAB).
  { unfold sortA, sortB, sortAB. rewrite List.map_app. reflexivity. }
  assert (HlenA : length αs = length sortA).
  { unfold sortA. symmetry. apply List.length_map. }
  assert (HlenB : length βs = length sortB).
  { unfold sortB. symmetry. apply List.length_map. }
  set (PA := pack (List.map (fun i => proj_at sortAB i (ax_var 0))
                            (List.seq 0 (length αs)))).
  set (PB := pack (List.map (fun i => proj_at sortAB i (ax_var 0))
                            (List.seq (length αs) (length βs)))).
  assert (HPA : AxHasType Sg Γ PA (I_obj αs)).
  { unfold PA. apply block_typed_alpha. }
  assert (HPB : AxHasType Sg Γ PB (I_obj βs)).
  { unfold PB. apply block_typed_beta. }
  assert (Hv0 : AxHasType Sg Γ (ax_var 0) (ax_iter_prod sortAB)).
  { apply ax_ht_var. reflexivity. }
  (* Distribute ax_subst through prod_iso_bwd_term. *)
  unfold prod_iso_bwd_term.
  rewrite ax_subst_pack.
  rewrite List.map_app.
  rewrite !ax_subst_unpack_of.
  cbn [ax_subst].
  (* Goal: pack (unpack_of sortA (ax_fst FWD) ++ unpack_of sortB (ax_snd FWD))
            ~~ ax_var 0 *)
  (* We use FWD = ax_pair PA PB definitionally. *)
  change (prod_iso_fwd_term αs βs) with (ax_pair PA PB).
  (* Step: rewrite via β-pair to ax_pair PA PB → PA, PB. *)
  apply (axeq_trans Sg [] Γ _
            (pack (unpack_of sortA PA ++ unpack_of sortB PB))
            (ax_var 0) (I_obj (αs ++ βs))).
  - (* β-pair lift. Use ax_subst_cong with template
       [pack (unpack_of sortA (ax_var 1) ++ unpack_of sortB (ax_var 0))]
       and substitutions [ax_fst (ax_pair PA PB); ax_snd (ax_pair PA PB)]
       vs [PA; PB]. *)
    set (T := pack (unpack_of sortA (ax_var 0) ++ unpack_of sortB (ax_var 1))).
    assert (HT : AxHasType Sg [I_obj αs; I_obj βs] T (ax_iter_prod (sortA ++ sortB))).
    { unfold T. apply pack_typed. apply List.Forall2_app.
      - apply unpack_of_typed.
        apply ax_ht_var. cbn. reflexivity.
      - apply unpack_of_typed.
        apply ax_ht_var. cbn. reflexivity. }
    set (F := ax_fst (ax_pair PA PB)).
    set (S := ax_snd (ax_pair PA PB)).
    assert (HF : AxThEq Sg [] Γ F PA (I_obj αs)).
    { apply (axeq_beta_fst Sg [] Γ PA PB (I_obj αs) (I_obj βs) HPA HPB). }
    assert (HS : AxThEq Sg [] Γ S PB (I_obj βs)).
    { apply (axeq_beta_snd Sg [] Γ PA PB (I_obj αs) (I_obj βs) HPA HPB). }
    assert (HFt : AxHasType Sg Γ F (I_obj αs)).
    { unfold F. apply (ax_ht_fst Sg Γ (ax_pair PA PB) (I_obj αs) (I_obj βs)).
      apply ax_ht_pair; assumption. }
    assert (HSt : AxHasType Sg Γ S (I_obj βs)).
    { unfold S. apply (ax_ht_snd Sg Γ (ax_pair PA PB) (I_obj αs) (I_obj βs)).
      apply ax_ht_pair; assumption. }
    apply (axeq_trans Sg [] Γ _ (ax_subst [F; S] T) _ _).
    { unfold T. rewrite ax_subst_pack, List.map_app, !ax_subst_unpack_of.
      simpl ax_subst. apply axeq_refl.
      change (I_obj (αs ++ βs)) with (ax_iter_prod sortAB).
      rewrite <- HsortAB.
      apply pack_typed. apply List.Forall2_app.
      - apply unpack_of_typed. exact HFt.
      - apply unpack_of_typed. exact HSt. }
    apply (axeq_trans Sg [] Γ _ (ax_subst [PA; PB] T) _ _).
    2: { unfold T. rewrite ax_subst_pack, List.map_app, !ax_subst_unpack_of.
         simpl ax_subst. apply axeq_refl.
         change (I_obj (αs ++ βs)) with (ax_iter_prod sortAB).
         rewrite <- HsortAB.
         apply pack_typed. apply List.Forall2_app.
         - apply unpack_of_typed. exact HPA.
         - apply unpack_of_typed. exact HPB. }
    change (I_obj (αs ++ βs)) with (ax_iter_prod sortAB).
    rewrite <- HsortAB.
    apply (ax_subst_cong Sg [] Γ [I_obj αs; I_obj βs]
             [F; S] [PA; PB] T T (ax_iter_prod (sortA ++ sortB))).
    + constructor; [exact HFt|]. constructor; [exact HSt|]. constructor.
    + constructor; [exact HPA|]. constructor; [exact HPB|]. constructor.
    + intros k τ s s' Hτk Hsk Hs'k.
      destruct k as [|k]; cbn in *.
      * injection Hτk as <-. injection Hsk as <-. injection Hs'k as <-. exact HF.
      * destruct k as [|k]; cbn in *.
        -- injection Hτk as <-. injection Hsk as <-. injection Hs'k as <-. exact HS.
        -- destruct k; discriminate.
    + apply axeq_refl. exact HT.
  - (* pack(unpack_of sortA PA ++ unpack_of sortB PB) ~~ ax_var 0.
       Goal: AxThEq [] Γ (pack ...) (ax_var 0) (I_obj (αs ++ βs)). *)
    change (I_obj (αs ++ βs)) with (ax_iter_prod sortAB).
    rewrite <- HsortAB.
    apply (axeq_trans Sg [] Γ _
              (pack (unpack_of (sortA ++ sortB) (ax_var 0)))
              (ax_var 0) (ax_iter_prod (sortA ++ sortB))).
    + (* pack of (sortA-PA-projs ++ sortB-PB-projs) ~~ pack(unpack_of sortAB v0)
         pointwise via proj_at_pack. *)
      apply pack_cong with (γs := sortA ++ sortB).
      * apply List.Forall2_app.
        -- apply unpack_of_typed. exact HPA.
        -- apply unpack_of_typed. exact HPB.
      * unfold unpack_of.
        rewrite List.length_app.
        rewrite List.seq_app.
        rewrite List.map_app.
        apply List.Forall2_app.
        -- (* αs-block of unpack_of sortAB v0 *)
           assert (Hgen : forall (k : nat) (L0 : list (AxType Sg)),
                     (forall j τ, List.nth_error L0 j = Some τ ->
                                  List.nth_error sortAB (k + j) = Some τ) ->
                     Forall2 (AxHasType Sg Γ)
                             (List.map (fun j => proj_at sortAB j (ax_var 0))
                                       (List.seq k (length L0)))
                             L0).
           { intros k L0. revert k.
             induction L0 as [|τ L0' IH']; intros k Hnth.
             - simpl. constructor.
             - simpl. constructor.
               + apply (proj_at_typed Sg Γ sortAB k τ (ax_var 0)).
                 * specialize (Hnth 0 τ eq_refl). rewrite Nat.add_0_r in Hnth.
                   exact Hnth.
                 * exact Hv0.
               + apply (IH' (S k)).
                 intros j τ' Hj. specialize (Hnth (S j) τ' Hj).
                 replace (S k + j) with (k + S j) by lia. exact Hnth. }
           rewrite HsortAB.
           apply (Hgen 0 sortA).
           intros j τ Hj.
           assert (HjA : j < length sortA).
           { apply List.nth_error_Some. intro Hc. rewrite Hj in Hc. discriminate. }
           rewrite <- HsortAB.
           rewrite List.nth_error_app1 by exact HjA. exact Hj.
        -- (* βs-block of unpack_of sortAB v0 *)
           assert (Hgen : forall (k : nat) (L0 : list (AxType Sg)),
                     (forall j τ, List.nth_error L0 j = Some τ ->
                                  List.nth_error sortAB (length sortA + k + j) = Some τ) ->
                     Forall2 (AxHasType Sg Γ)
                             (List.map (fun j => proj_at sortAB j (ax_var 0))
                                       (List.seq (length sortA + k) (length L0)))
                             L0).
           { intros k L0. revert k.
             induction L0 as [|τ L0' IH']; intros k Hnth.
             - simpl. constructor.
             - simpl. constructor.
               + apply (proj_at_typed Sg Γ sortAB (length sortA + k) τ (ax_var 0)).
                 * specialize (Hnth 0 τ eq_refl). rewrite Nat.add_0_r in Hnth.
                   exact Hnth.
                 * exact Hv0.
               + replace (S (length sortA + k)) with (length sortA + S k) by lia.
                 apply (IH' (S k)).
                 intros j τ' Hj. specialize (Hnth (S j) τ' Hj).
                 replace (length sortA + S k + j) with (length sortA + k + S j) by lia.
                 exact Hnth. }
           rewrite HsortAB.
           replace (0 + length sortA) with (length sortA + 0) by lia.
           apply (Hgen 0 sortB).
           intros j τ Hj.
           assert (HjB : j < length sortB).
           { apply List.nth_error_Some. intro Hc. rewrite Hj in Hc. discriminate. }
           rewrite <- HsortAB.
           rewrite List.nth_error_app2 by lia.
           replace (length sortA + 0 + j - length sortA) with j by lia.
           exact Hj.
      * intros i τ X X' Hτi HXi HX'i.
        (* X = (unpack_of sortA PA ++ unpack_of sortB PB)[i]
           X' = unpack_of (sortA ++ sortB) (ax_var 0) [i] *)
        rewrite List.nth_error_app in HXi.
        rewrite length_unpack_of_inline in HXi.
        destruct (Nat.ltb_spec0 i (length sortA)) as [HiA | HiA].
        -- (* αs-block *)
           unfold unpack_of in HXi.
           rewrite List.nth_error_map in HXi.
           rewrite nth_error_seq_lt in HXi by exact HiA.
           cbn in HXi. injection HXi as <-.
           unfold unpack_of in HX'i.
           rewrite List.nth_error_map in HX'i.
           rewrite nth_error_seq_lt in HX'i.
           2: { rewrite List.length_app. lia. }
           cbn in HX'i. injection HX'i as <-.
           assert (Hτi_AB : List.nth_error sortAB i = Some τ).
           { rewrite <- HsortAB.
             rewrite List.nth_error_app1 in Hτi by lia.
             rewrite List.nth_error_app1 by exact HiA. exact Hτi. }
           (* Goal: AxThEq Γ (proj_at sortA i PA) (proj_at sortAB i (ax_var 0)) τ.
              Use proj_at_pack on PA. *)
           rewrite List.nth_error_app1 in Hτi by lia.
           assert (HMs_PA : Forall2 (AxHasType Sg Γ)
                              (List.map (fun j => proj_at sortAB j (ax_var 0))
                                        (List.seq 0 (length αs)))
                              sortA).
           { (* Inline argument matching block_typed_alpha. *)
             assert (Hgen : forall (k : nat) (L0 : list (AxType Sg)),
                       (forall j τ', List.nth_error L0 j = Some τ' ->
                                    List.nth_error sortAB (k + j) = Some τ') ->
                       Forall2 (AxHasType Sg Γ)
                               (List.map (fun j => proj_at sortAB j (ax_var 0))
                                         (List.seq k (length L0)))
                               L0).
             { intros k L0. revert k.
               induction L0 as [|τ' L0' IH']; intros k Hnth.
               - simpl. constructor.
               - simpl. constructor.
                 + apply (proj_at_typed Sg Γ sortAB k τ' (ax_var 0)).
                   * specialize (Hnth 0 τ' eq_refl). rewrite Nat.add_0_r in Hnth.
                     exact Hnth.
                   * exact Hv0.
                 + apply (IH' (S k)).
                   intros j τ'' Hj'. specialize (Hnth (S j) τ'' Hj').
                   replace (S k + j) with (k + S j) by lia. exact Hnth. }
             rewrite HlenA.
             apply (Hgen 0 sortA).
             intros j τ' Hj'.
             assert (HjA' : j < length sortA).
             { apply List.nth_error_Some. intro Hc. rewrite Hj' in Hc. discriminate. }
             rewrite <- HsortAB. rewrite List.nth_error_app1 by exact HjA'. exact Hj'. }
           change PA with (pack (List.map
                            (fun j => proj_at sortAB j (ax_var 0))
                            (List.seq 0 (length αs)))).
           rewrite HlenA in *.
           assert (Hpos_in_PAlist :
             List.nth_error
               (List.map (fun j => proj_at sortAB j (ax_var 0))
                         (List.seq 0 (length sortA))) i =
             Some (proj_at sortAB i (ax_var 0))).
           { rewrite List.nth_error_map. rewrite nth_error_seq_lt by exact HiA.
             cbn. reflexivity. }
           rewrite <- HsortAB in *.
           apply (proj_at_pack Sg Γ sortA
                    (List.map (fun j => proj_at (sortA ++ sortB) j (ax_var 0))
                              (List.seq 0 (length sortA))) i
                    (proj_at (sortA ++ sortB) i (ax_var 0)) τ
                    HMs_PA Hpos_in_PAlist Hτi).
        -- (* βs-block *)
           apply Nat.nlt_ge in HiA.
           assert (HiBspec : i - length sortA < length sortB).
           { rewrite List.nth_error_app2 in Hτi by exact HiA.
             apply List.nth_error_Some. rewrite Hτi. discriminate. }
           unfold unpack_of in HXi.
           rewrite List.nth_error_map in HXi.
           rewrite nth_error_seq_lt in HXi by exact HiBspec.
           cbn in HXi. injection HXi as <-.
           (* HX'i: nth_error (map(...) (seq 0 (|sortA|+|sortB|))) i = Some X' *)
           unfold unpack_of in HX'i.
           rewrite List.nth_error_map in HX'i.
           rewrite nth_error_seq_lt in HX'i.
           2: { apply List.nth_error_Some. rewrite Hτi. discriminate. }
           cbn in HX'i. injection HX'i as <-.
           (* HiBspec already in context from earlier. *)
           rewrite List.nth_error_app2 in Hτi by exact HiA.
           (* Goal: AxThEq (proj_at sortB (i-|sortA|) PB) (proj_at sortAB i v0) τ. *)
           change PB with (pack (List.map
                            (fun j => proj_at sortAB j (ax_var 0))
                            (List.seq (length αs) (length βs)))).
           assert (HMs_PB : Forall2 (AxHasType Sg Γ)
                              (List.map (fun j => proj_at sortAB j (ax_var 0))
                                        (List.seq (length αs) (length βs)))
                              sortB).
           { assert (Hgen : forall (k : nat) (L0 : list (AxType Sg)),
                       (forall j τ', List.nth_error L0 j = Some τ' ->
                                    List.nth_error sortAB (length αs + k + j) = Some τ') ->
                       Forall2 (AxHasType Sg Γ)
                               (List.map (fun j => proj_at sortAB j (ax_var 0))
                                         (List.seq (length αs + k) (length L0)))
                               L0).
             { intros k L0. revert k.
               induction L0 as [|τ' L0' IH']; intros k Hnth.
               - simpl. constructor.
               - simpl. constructor.
                 + apply (proj_at_typed Sg Γ sortAB (length αs + k) τ' (ax_var 0)).
                   * specialize (Hnth 0 τ' eq_refl). rewrite Nat.add_0_r in Hnth.
                     exact Hnth.
                   * exact Hv0.
                 + replace (S (length αs + k)) with (length αs + S k) by lia.
                   apply (IH' (S k)).
                   intros j τ'' Hj'. specialize (Hnth (S j) τ'' Hj').
                   replace (length αs + S k + j) with (length αs + k + S j) by lia.
                   exact Hnth. }
             rewrite HlenB.
             replace (length αs) with (length αs + 0) at 1 by lia.
             apply (Hgen 0 sortB).
             intros j τ' Hj'.
             assert (HjB' : j < length sortB).
             { apply List.nth_error_Some. intro Hc. rewrite Hj' in Hc. discriminate. }
             rewrite <- HsortAB. rewrite List.nth_error_app2 by lia.
             replace (length αs + 0 + j - length sortA) with j by lia. exact Hj'. }
           assert (Hpos_in_PBlist :
             List.nth_error
               (List.map (fun j => proj_at sortAB j (ax_var 0))
                         (List.seq (length αs) (length βs)))
               (i - length sortA) =
             Some (proj_at sortAB i (ax_var 0))).
           { rewrite List.nth_error_map.
             rewrite nth_error_seq_lt.
             - cbn. f_equal. f_equal. lia.
             - rewrite HlenB. exact HiBspec. }
           rewrite <- HsortAB in *.
           apply (proj_at_pack Sg Γ sortB
                    (List.map (fun j => proj_at (sortA ++ sortB) j (ax_var 0))
                              (List.seq (length αs) (length βs)))
                    (i - length sortA) (proj_at (sortA ++ sortB) i (ax_var 0)) τ
                    HMs_PB Hpos_in_PBlist Hτi).
    + apply pack_unpack_eta.
      rewrite HsortAB. exact Hv0.
Qed.

(** [fwd ∘ bwd ~~ id] in AxThEq.

    Sketch:
    Substituting [prod_iso_bwd_term αs βs] for var 0 in
    [prod_iso_fwd_term αs βs] yields
    [ax_pair (pack αs-block-of-projs of BWD) (pack βs-block-of-projs of BWD)].
    Each block-pack of projs of BWD AxThEq-rewrites (via [proj_at_pack]
    applied to BWD = pack (...append...)) to the corresponding
    [unpack_of sortA (ax_fst (ax_var 0))] and
    [unpack_of sortB (ax_snd (ax_var 0))] respectively.  Then by
    [pack_unpack_eta] on [ax_fst (ax_var 0) : I_obj αs] and
    [ax_snd (ax_var 0) : I_obj βs] (each typed in
    [I_obj αs ×ax I_obj βs]), we get
    [ax_pair (ax_fst (ax_var 0)) (ax_snd (ax_var 0))], which by
    [axeq_eta_prod] equals [ax_var 0]. *)

Lemma prod_iso_fwd_bwd_eq (Sg : Signature) (αs βs : list Sg.(sg_ty)) :
    AxThEq Sg [] [I_obj αs ×ax I_obj βs]
      (ax_subst [prod_iso_bwd_term αs βs] (prod_iso_fwd_term αs βs))
      (ax_var 0)
      (I_obj αs ×ax I_obj βs).
Proof.
  set (Γ := [I_obj αs ×ax I_obj βs]).
  set (sortA := List.map ax_ground αs).
  set (sortB := List.map ax_ground βs).
  set (sortAB := List.map ax_ground (αs ++ βs)).
  assert (HsortAB : sortA ++ sortB = sortAB).
  { unfold sortA, sortB, sortAB. rewrite List.map_app. reflexivity. }
  set (BWD := prod_iso_bwd_term αs βs).
  set (FST := ax_fst (ax_var 0) : AxTerm Sg).
  set (SND := ax_snd (ax_var 0) : AxTerm Sg).
  assert (HFST : AxHasType Sg Γ FST (I_obj αs)).
  { apply (ax_ht_fst Sg Γ (ax_var 0) (I_obj αs) (I_obj βs)).
    apply ax_ht_var. reflexivity. }
  assert (HSND : AxHasType Sg Γ SND (I_obj βs)).
  { apply (ax_ht_snd Sg Γ (ax_var 0) (I_obj αs) (I_obj βs)).
    apply ax_ht_var. reflexivity. }
  (* BWD = pack (unpack_of sortA FST ++ unpack_of sortB SND) *)
  assert (EBWD : BWD =
            pack (unpack_of sortA FST ++ unpack_of sortB SND)).
  { reflexivity. }
  (* Typing of pieces *)
  assert (HBWD_app : Forall2 (AxHasType Sg Γ)
            (unpack_of sortA FST ++ unpack_of sortB SND) (sortA ++ sortB)).
  { apply List.Forall2_app.
    - apply unpack_of_typed. exact HFST.
    - apply unpack_of_typed. exact HSND. }
  assert (HBWD_typed : AxHasType Sg Γ BWD (ax_iter_prod (sortA ++ sortB))).
  { rewrite EBWD. apply pack_typed. exact HBWD_app. }
  (* Goal LHS distributes through ax_subst on prod_iso_fwd_term. *)
  unfold prod_iso_fwd_term. cbn [ax_subst].
  rewrite !ax_subst_pack.
  rewrite !List.map_map.
  (* Each entry: ax_subst [BWD] (proj_at sortAB i (ax_var 0)) =
     proj_at sortAB i BWD by ax_subst_proj_at + cbn. *)
  erewrite (List.map_ext _ (fun i => proj_at sortAB i BWD)) by
    (intro i; rewrite ax_subst_proj_at; cbn [ax_subst]; reflexivity).
  match goal with
  | |- AxThEq _ _ _ (ax_pair _ ?B) _ _ =>
      replace B with (pack (List.map (fun i => proj_at sortAB i BWD)
                                     (List.seq (length αs) (length βs))))
  end.
  2: { f_equal. apply List.map_ext.
       intro i. rewrite ax_subst_proj_at. cbn [ax_subst]. reflexivity. }
  (* Step: this AxThEq-equals ax_pair FST SND. *)
  apply (axeq_trans Sg [] Γ _ (ax_pair FST SND) (ax_var 0)
            (I_obj αs ×ax I_obj βs)).
  - apply axeq_pair.
    + (* αs-block: pack(map (proj_at sortAB i BWD) (seq 0 |αs|)) ~~ FST. *)
      apply (axeq_trans Sg [] Γ _
                (pack (unpack_of sortA FST))
                FST (I_obj αs)).
      * (* pointwise: proj_at sortAB i BWD ~~ unpack_of sortA FST [i] for i < |αs|. *)
        unfold I_obj.
        assert (HlenA : length αs = length sortA).
        { unfold sortA. symmetry. apply List.length_map. }
        rewrite HlenA.
        apply pack_cong with (γs := sortA).
        -- (* LHS typing *)
           clear EBWD.
           rewrite HsortAB in HBWD_typed.
           assert (Hgen : forall (k : nat) (L0 : list (AxType Sg)),
                     (forall j τ, List.nth_error L0 j = Some τ ->
                                  List.nth_error sortAB (k + j) = Some τ) ->
                     Forall2 (AxHasType Sg Γ)
                             (List.map (fun j => proj_at sortAB j BWD)
                                       (List.seq k (length L0)))
                             L0).
           { intros k L0. revert k.
             induction L0 as [|τ L0' IH']; intros k Hnth.
             - simpl. constructor.
             - simpl. constructor.
               + apply (proj_at_typed Sg Γ sortAB k τ BWD).
                 * specialize (Hnth 0 τ eq_refl). rewrite Nat.add_0_r in Hnth.
                   exact Hnth.
                 * exact HBWD_typed.
               + apply (IH' (S k)).
                 intros j τ' Hj. specialize (Hnth (S j) τ' Hj).
                 replace (S k + j) with (k + S j) by lia. exact Hnth. }
           apply (Hgen 0 sortA).
           intros j τ Hj.
           assert (HjA : j < length sortA).
           { apply List.nth_error_Some. intro Hcontra.
             rewrite Hj in Hcontra. discriminate. }
           unfold sortAB. rewrite List.map_app.
           fold sortA.
           rewrite List.nth_error_app1 by exact HjA.
           simpl. exact Hj.
        -- apply unpack_of_typed. exact HFST.
        -- intros i τ X X' Hτi HXi HX'i.
           (* X = proj_at sortAB i BWD; X' = proj_at sortA i FST = unpack_of sortA FST [i]. *)
           assert (HiA : i < length sortA).
           { apply List.nth_error_Some. intro Hc. rewrite Hτi in Hc. discriminate. }
           assert (Eτ_ground : List.nth_error sortAB i = Some τ).
           { unfold sortAB. rewrite List.map_app. fold sortA.
             rewrite List.nth_error_app1 by exact HiA. exact Hτi. }
           (* HXi: nth_error of map f (seq 0 _) at i is Some (f i). *)
           rewrite List.nth_error_map in HXi.
           rewrite nth_error_seq_lt in HXi by exact HiA.
           cbn in HXi. injection HXi as <-.
           (* HX'i: unpack_of sortA FST is map(...) (seq 0 |sortA|). *)
           unfold unpack_of in HX'i.
           rewrite List.nth_error_map in HX'i.
           rewrite nth_error_seq_lt in HX'i by exact HiA.
           cbn in HX'i. injection HX'i as <-.
           (* Now: AxThEq (proj_at sortAB i BWD) (proj_at sortA i FST) τ.
              Use proj_at_pack on BWD = pack(unpack_of sortA FST ++ unpack_of sortB SND). *)
           rewrite EBWD.
           rewrite <- HsortAB.
           set (Ms_concat := unpack_of sortA FST ++ unpack_of sortB SND).
           assert (HMs_concat_typed :
             Forall2 (AxHasType Sg Γ) Ms_concat (sortA ++ sortB)).
           { unfold Ms_concat. apply List.Forall2_app.
             - apply unpack_of_typed. exact HFST.
             - apply unpack_of_typed. exact HSND. }
           assert (Hpos_in_concat :
             List.nth_error Ms_concat i = Some (proj_at sortA i FST)).
           { unfold Ms_concat. rewrite List.nth_error_app1.
             - unfold unpack_of.
               rewrite List.nth_error_map.
               rewrite nth_error_seq_lt by exact HiA.
               cbn. reflexivity.
             - rewrite length_unpack_of_inline. exact HiA. }
           apply (proj_at_pack Sg Γ (sortA ++ sortB) Ms_concat i
                    (proj_at sortA i FST) τ HMs_concat_typed Hpos_in_concat).
           rewrite List.nth_error_app1 by exact HiA. exact Hτi.
      * (* pack(unpack_of sortA FST) ~~ FST by pack_unpack_eta. *)
        apply pack_unpack_eta. unfold I_obj in HFST. exact HFST.
    + (* βs-block: similar *)
      apply (axeq_trans Sg [] Γ _
                (pack (unpack_of sortB SND))
                SND (I_obj βs)).
      * unfold I_obj.
        assert (HlenB : length βs = length sortB).
        { unfold sortB. symmetry. apply List.length_map. }
        rewrite HlenB.
        assert (HlenA_sortA : length αs = length sortA).
        { unfold sortA. symmetry. apply List.length_map. }
        apply pack_cong with (γs := sortB).
        -- (* LHS typing: each (proj_at sortAB (|αs|+i) BWD) typed at sortB[i]. *)
           rewrite HsortAB in HBWD_typed.
           assert (Hgen : forall (k : nat) (L0 : list (AxType Sg)),
                     (forall j τ, List.nth_error L0 j = Some τ ->
                                  List.nth_error sortAB (length αs + k + j) = Some τ) ->
                     Forall2 (AxHasType Sg Γ)
                             (List.map (fun j => proj_at sortAB j BWD)
                                       (List.seq (length αs + k) (length L0)))
                             L0).
           { intros k L0. revert k.
             induction L0 as [|τ L0' IH']; intros k Hnth.
             - simpl. constructor.
             - simpl. constructor.
               + apply (proj_at_typed Sg Γ sortAB (length αs + k) τ BWD).
                 * specialize (Hnth 0 τ eq_refl). rewrite Nat.add_0_r in Hnth.
                   exact Hnth.
                 * exact HBWD_typed.
               + replace (S (length αs + k)) with (length αs + S k) by lia.
                 apply (IH' (S k)).
                 intros j τ' Hj. specialize (Hnth (S j) τ' Hj).
                 replace (length αs + S k + j) with (length αs + k + S j) by lia.
                 exact Hnth. }
           replace (length αs) with (length αs + 0) at 1 by lia.
           apply (Hgen 0 sortB).
           intros j τ Hj.
           unfold sortAB. rewrite List.map_app. fold sortA.
           rewrite List.nth_error_app2.
           ++ rewrite <- HlenA_sortA.
              replace (length αs + 0 + j - length αs) with j by lia.
              simpl. exact Hj.
           ++ rewrite <- HlenA_sortA. lia.
        -- apply unpack_of_typed. exact HSND.
        -- intros i τ X X' Hτi HXi HX'i.
           assert (HiB : i < length sortB).
           { apply List.nth_error_Some. intro Hc. rewrite Hτi in Hc. discriminate. }
           assert (Eτ_ground : List.nth_error sortAB (length αs + i) = Some τ).
           { unfold sortAB. rewrite List.map_app. fold sortA.
             rewrite List.nth_error_app2 by lia.
             rewrite <- HlenA_sortA. replace (length αs + i - length αs) with i by lia.
             exact Hτi. }
           rewrite List.nth_error_map in HXi.
           rewrite nth_error_seq_lt in HXi by exact HiB.
           cbn in HXi. injection HXi as <-.
           unfold unpack_of in HX'i.
           rewrite List.nth_error_map in HX'i.
           rewrite nth_error_seq_lt in HX'i by exact HiB.
           cbn in HX'i. injection HX'i as <-.
           (* Goal: AxThEq (proj_at sortAB (length αs + i) BWD)
                          (proj_at sortB i SND) τ. *)
           rewrite EBWD.
           rewrite <- HsortAB.
           set (Ms_concat := unpack_of sortA FST ++ unpack_of sortB SND).
           assert (HMs_concat_typed :
             Forall2 (AxHasType Sg Γ) Ms_concat (sortA ++ sortB)).
           { unfold Ms_concat. apply List.Forall2_app.
             - apply unpack_of_typed. exact HFST.
             - apply unpack_of_typed. exact HSND. }
           assert (Hpos_in_concat :
             List.nth_error Ms_concat (length αs + i) = Some (proj_at sortB i SND)).
           { unfold Ms_concat. rewrite List.nth_error_app2.
             - rewrite length_unpack_of_inline.
               replace (length αs + i - length sortA) with i by lia.
               unfold unpack_of.
               rewrite List.nth_error_map.
               rewrite nth_error_seq_lt by exact HiB.
               cbn. reflexivity.
             - rewrite length_unpack_of_inline. lia. }
           apply (proj_at_pack Sg Γ (sortA ++ sortB) Ms_concat (length αs + i)
                    (proj_at sortB i SND) τ HMs_concat_typed Hpos_in_concat).
           rewrite List.nth_error_app2 by lia.
           rewrite <- HlenA_sortA. replace (length αs + i - length αs) with i by lia.
           exact Hτi.
      * apply pack_unpack_eta. unfold I_obj in HSND. exact HSND.
  - (* ax_pair (ax_fst v0) (ax_snd v0) ~~ v0 by axeq_eta_prod. *)
    apply axeq_eta_prod.
    apply ax_ht_var. reflexivity.
Qed.

(** Assemble the iso. *)

Lemma prod_iso_bwd_fwd_AxCl (Sg : Signature) (αs βs : list Sg.(sg_ty)) :
    prod_iso_bwd αs βs ∘ prod_iso_fwd αs βs =
    (AxCl Sg).(id) (I_obj (αs ++ βs)).
Proof.
  unfold prod_iso_bwd, prod_iso_fwd.
  cbn [AxCl comp].
  rewrite axcl_comp_mk.
  apply mk_q_eq_iff.
  unfold AxClMor_eq, axcl_comp_rep, axcl_id_rep, prod_iso_bwd_rep,
         prod_iso_fwd_rep. cbn [axcl_term].
  apply prod_iso_bwd_fwd_eq.
Qed.

Lemma prod_iso_fwd_bwd_AxCl (Sg : Signature) (αs βs : list Sg.(sg_ty)) :
    prod_iso_fwd αs βs ∘ prod_iso_bwd αs βs =
    (AxCl Sg).(id) (I_obj αs ×ax I_obj βs).
Proof.
  unfold prod_iso_bwd, prod_iso_fwd.
  cbn [AxCl comp].
  rewrite axcl_comp_mk.
  apply mk_q_eq_iff.
  unfold AxClMor_eq, axcl_comp_rep, axcl_id_rep, prod_iso_bwd_rep,
         prod_iso_fwd_rep. cbn [axcl_term].
  apply prod_iso_fwd_bwd_eq.
Qed.

Definition I_prod_iso (Sg : Signature) (αs βs : list Sg.(sg_ty)) :
    @Isomorphism (AxCl Sg)
      (I_obj (αs ++ βs))
      (I_obj αs ×ax I_obj βs) :=
  {| iso_fwd     := prod_iso_fwd αs βs;
     iso_bwd     := prod_iso_bwd αs βs;
     iso_fwd_bwd := prod_iso_bwd_fwd_AxCl Sg αs βs;
     iso_bwd_fwd := prod_iso_fwd_bwd_AxCl Sg αs βs;
  |}.

(** Terminal iso: [I_obj [] = ax_unit] definitionally. *)

Definition I_term_iso (Sg : Signature) :
    @Isomorphism (AxCl Sg) (I_obj []) ax_unit :=
  @iso_refl (AxCl Sg) ax_unit.

(* ================================================================== *)
(** ** I_fp_functor                                                     *)
(* ================================================================== *)

(** The iso witnesses, packaged with [I_functor], produce the
    [FPtoCCCFunctor].  Note the codomain types differ from the
    abstract ones in [FPtoCCCFunctor] only by definitional unfolding
    of [cl_finite_products] and [axcl_ccc] / [axcl_finite_products]. *)

Definition I_fp_functor (Sg : Signature) :
    FPtoCCCFunctor (cl_finite_products Sg) (axcl_ccc Sg).
Proof.
  refine {|
    fptoccc_funct    := I_functor Sg;
    fptoccc_iso_term := _;
    fptoccc_iso_prod := fun A B => _;
  |}.
  - (* terminal iso: [I_obj [] = ax_unit] definitionally; both sides
       of the iso reduce to [ax_unit]. *)
    cbn. exact (@iso_refl (AxCl Sg) ax_unit).
  - (* prod iso *)
    cbn. exact (I_prod_iso Sg A B).
Defined.

(* ================================================================== *)
(** ** Universal extension: structural skeleton [β R18 — 2026-05-01]    *)
(* ================================================================== *)

(** This section delivers the object-level witness and structural
    sub-lemmas of the universal extension underlying
    [classifying_CCC_is_relatively_free].

    Given a CCC [D] (with [cD : IsCartesianClosed D]) and an FP-functor
    [F : Cl Sg → D] (in the iso-loosened sense [FPtoCCCFunctor]), the
    extension [F̃ : AxCl Sg → D] is determined RECURSIVELY on the
    [AxType Sg] inductive:

    - [F̃(ax_ground τ)] := [F ## [τ]]                       (singleton list)
    - [F̃(ax_unit)]     := [projT1 (fp_terminal cD.(ccc_fp))]   (terminal)
    - [F̃(α ×ax β)]     := [F̃(α) ×{cD.(ccc_fp).(fp_binary)} F̃(β)]
    - [F̃(α ⇒ax β)]     := [F̃(α) ⇒{cD} F̃(β)]

    The MORPHISM-level extension is more delicate: a morphism
    [α → β] in [AxCl Sg] is an [AxThEq]-class of a typed [AxTerm].
    For each [AxTerm M : AxHasType [α] M β], the standard
    interpretation [⟦M⟧ : F̃(α) → F̃(β)] is built recursively over the
    [AxHasType] derivation via D's CCC structure (variables → projections
    of the context, [ax_pair] → [bp_pair], [ax_fst]/[ax_snd] →
    [bp_proj1]/[bp_proj2], [ax_lam] → [exp_curry], [ax_ap] →
    [exp_eval ∘ ⟨_, _⟩], [ax_app_fn f] → [F #> (some morphism)]).
    The well-definedness modulo [AxThEq] is the heart of the proof.

    α R8 closed an analogous L.3 completeness statement
    ([term_to_clmor_q] / [interp_term_data] in the ATT subsystem); the
    construction here is structurally similar but lifts to the AxCl
    side.  See [REFACTOR_PLAN.org] Task A.2.next-prod / A.2.next.

    DELIVERED IN THIS ROUND (β R18):
    - [Fbar_obj]          — recursive object map, fully concrete.
    - [Fbar_obj_unit]     — unit case definitional.
    - [Fbar_obj_prod]     — product case definitional.
    - [Fbar_obj_exp]      — exponential case definitional.
    - [Fbar_obj_ground_singleton] — [F̃(ax_ground τ) = F ## [τ]].
    - [Fbar_obj_iter_prod_via_iso] — the iterated-product object map
      reaches [F ## αs] up to iterated [fptoccc_iso_prod] mediation
      (statement only as a comment; full proof depends on a
      [Fbar_iter_prod_iso] iso-chain construction which is a separate
      sub-task).

    DEFERRED (paper-attributable, scoped for future rounds):
    - [Fbar_term]         — interpretation of typed AxTerms in D.
    - [Fbar_term_well_defined] — congruence wrt [AxThEq].
    - [Fbar_functor]      — assembly into a Functor.
    - [Fbar_ccc_functor]  — CCCFunctor preservation laws.
    - [Fbar_triangle]     — F̃ ∘ I = F (FunctorObjEq).
    - [Fbar_uniq]         — uniqueness clause.

    Until those land, the umbrella statement
    [classifying_CCC_is_relatively_free] remains an Axiom: a
    paper-attributable universal property of the relative free CCC
    construction (cf. Lambek–Scott Part I §11; Pitts "Categorical Logic"
    §6.1).  Per project policy, paper-attributable axioms in
    foundational categorical-logic constructions are acceptable when
    flagged with informal-definition comments. *)

Section UniversalExtension.
  Context {Sg : Signature}.
  Context {D : Category} (cD : IsCartesianClosed D).
  Context (F : FPtoCCCFunctor (cl_finite_products Sg) cD).

  (** Object-level extension: recursive on [AxType Sg]. *)
  Fixpoint Fbar_obj (α : AxType Sg) : D.(Ob) :=
    match α with
    | ax_ground τ  => F.(fptoccc_funct) ## [τ]
    | ax_unit      => projT1 (@fp_terminal D cD.(ccc_fp))
    | ax_prod α' β => Fbar_obj α' ×{@fp_binary D cD.(ccc_fp)} Fbar_obj β
    | ax_exp  α' β => Fbar_obj α' ⇒{cD} Fbar_obj β
    end.

  (** Structural cases — definitional equalities packaged as Lemmas
      for downstream use in well-definedness proofs. *)

  Lemma Fbar_obj_unit :
      Fbar_obj ax_unit = projT1 (@fp_terminal D cD.(ccc_fp)).
  Proof. reflexivity. Qed.

  Lemma Fbar_obj_prod (α β : AxType Sg) :
      Fbar_obj (α ×ax β) =
      Fbar_obj α ×{@fp_binary D cD.(ccc_fp)} Fbar_obj β.
  Proof. reflexivity. Qed.

  Lemma Fbar_obj_exp (α β : AxType Sg) :
      Fbar_obj (α ⇒ax β) = Fbar_obj α ⇒{cD} Fbar_obj β.
  Proof. reflexivity. Qed.

  Lemma Fbar_obj_ground (τ : Sg.(sg_ty)) :
      Fbar_obj (ax_ground τ) = F.(fptoccc_funct) ## [τ].
  Proof. reflexivity. Qed.

End UniversalExtension.

Arguments Fbar_obj {Sg D cD} F α.

(** Object-level triangle — preliminary: on the special shape
    [I_obj [τ]] (singleton list), the witness reaches the F-image
    directly. *)

Lemma Fbar_obj_I_singleton {Sg : Signature}
    {D : Category} (cD : IsCartesianClosed D)
    (F : FPtoCCCFunctor (cl_finite_products Sg) cD)
    (τ : Sg.(sg_ty)) :
    Fbar_obj F (I_obj [τ]) = F.(fptoccc_funct) ## [τ].
Proof.
  unfold I_obj. simpl. reflexivity.
Qed.

(** Object-level triangle — empty list case: reaches D's terminal. *)

Lemma Fbar_obj_I_nil {Sg : Signature}
    {D : Category} (cD : IsCartesianClosed D)
    (F : FPtoCCCFunctor (cl_finite_products Sg) cD) :
    Fbar_obj F (I_obj []) = projT1 (@fp_terminal D cD.(ccc_fp)).
Proof.
  unfold I_obj. simpl. reflexivity.
Qed.

(** [classifying_CCC_is_relatively_free] — the universal property of
    the relative free CCC.  Paper-attributable (Lambek–Scott Part I §11
    "syntactic categories of typed lambda calculi"; Pitts "Categorical
    Logic" §6.1 Theorem 6.1.6).  The full discharge requires a
    morphism-level extension function [Fbar_term] together with its
    well-definedness modulo AxThEq, the CCC-functor laws on the
    extension, and the uniqueness clause — all standard but spanning
    several files of bookkeeping (cf. α R8's analogous L.3 completeness
    closure for the ATT side).  The OBJECT-LEVEL skeleton is delivered
    above as [Fbar_obj] + [Fbar_obj_unit] / [_prod] / [_exp] /
    [_ground] / [_I_singleton] / [_I_nil]; the morphism-level content
    is scoped for next rounds. *)

Axiom classifying_CCC_is_relatively_free : forall (Sg : Signature),
    RelativelyFreeCCC (cl_finite_products Sg) (axcl_ccc Sg) (I_fp_functor Sg).
