(** * Order/Ideal.v
    Ideals of a join-semilattice, ideal completion,
    and Proposition 1.5.18: ideal completion is an algebraic complete lattice. *)

Require Import CAG.Order.Poset.
Require Import CAG.Order.Lattice.
Require Import CAG.Order.DCPO.
Require Import CAG.Order.Compact.
From Stdlib Require Import Logic.FunctionalExtensionality.
From Stdlib Require Import Logic.ProofIrrelevance.
From Stdlib Require Import Logic.Classical.
From Stdlib Require Import Logic.PropExtensionality.
From Stdlib Require Import Sets.Ensembles.
From Stdlib Require Import Lists.List.

Open Scope order_scope.

(** ** Ideal of a join-semilattice

    An ideal I ⊆ X satisfies:
    1. ⊥ ∈ I (nonempty)
    2. x, y ∈ I implies x ∨ y ∈ I (closed under binary joins)
    3. x ∈ I and y ≤ x implies y ∈ I (downward-closed) *)

Record IsIdeal (J : JoinSemilattice) (I : J.(carrier) -> Prop) : Prop := {
  ideal_bot    : I ⊥{J};
  ideal_join   : forall x y, I x -> I y -> I (x ∨{J} y);
  ideal_down   : forall x y, I x -> y ≤[J] x -> I y;
}.

(** ** Ideal completion — the set of all ideals, ordered by inclusion *)

(** The ideal completion of a JSL J is the set of all ideals of J,
    ordered by subset inclusion. *)

Definition IdealCompletion (J : JoinSemilattice) : Poset.
Proof.
  refine {|
    carrier    := { I : J.(carrier) -> Prop | IsIdeal J I };
    le         := fun I1 I2 => forall x, proj1_sig I1 x -> proj1_sig I2 x;
    le_refl    := fun I x Hx => Hx;
    le_trans   := fun I1 I2 I3 h12 h23 x Hx => h23 x (h12 x Hx);
    le_antisym := _;
  |}.
  intros I1 I2 h12 h21.
  apply eq_sig_hprop.
  - intros x. apply proof_irrelevance.
  - apply functional_extensionality. intros x.
    apply propositional_extensionality. split; [apply h12 | apply h21].
Defined.

Notation "'IdCompl' J" := (IdealCompletion J) (at level 9) : order_scope.

(** Principal ideal generated by x: the downward closure of {x} *)
Definition principal_ideal (J : JoinSemilattice) (x : J.(carrier)) :
    { I : J.(carrier) -> Prop | IsIdeal J I }.
Proof.
  exists (fun y => y ≤[J] x).
  constructor.
  - apply J.(jsl_bot_le).
  - intros a b Ha Hb.
    apply J.(jsl_join_lub); assumption.
  - intros a b Ha Hle.
    apply J.(le_trans) with a; assumption.
Defined.

Notation "x ↓i{ J }" := (principal_ideal J x) (at level 5) : order_scope.

(** ** Ideal completion as a complete lattice

    Proposition 1.5.18: IdCompl J is an algebraic complete lattice.
    - Meets are intersections.
    - Directed joins are unions.
    - Compact elements are principal ideals. *)

(** *** Arbitrary meets: intersection of ideals is an ideal *)

Lemma inter_ideal (J : JoinSemilattice) (F : (J.(carrier) -> Prop) -> Prop)
    (hF : forall I, F I -> IsIdeal J I)
    (hne : exists I, F I) :
    IsIdeal J (fun x => forall I, F I -> I x).
Proof.
  constructor.
  - intros I HI. exact (ideal_bot _ _ (hF I HI)).
  - intros x y Hx Hy I HI.
    apply (ideal_join _ _ (hF I HI)). apply Hx. exact HI. apply Hy. exact HI.
  - intros x y Hx Hle I HI.
    apply (ideal_down _ _ (hF I HI)) with x. apply Hx. exact HI. exact Hle.
Qed.

(** *** Directed joins: union of a directed family of ideals is an ideal *)

Lemma union_directed_ideal (J : JoinSemilattice)
    (F : (J.(carrier) -> Prop) -> Prop)
    (hF : forall I, F I -> IsIdeal J I)
    (hdir : IsDirected (IdealCompletion J) (fun I => F (proj1_sig I))) :
    IsIdeal J (fun x => exists I, F I /\ I x).
Proof.
  constructor.
  - (* ⊥ is in the union *)
    destruct (dir_inh _ _ hdir) as [[I hI] HFI].
    exists I. split. exact HFI. exact (ideal_bot _ _ (hF I HFI)).
  - (* closed under join *)
    intros x y [Ix [HIx Hxx]] [Iy [HIy Hyy]].
    (* Since F is directed, there exists Iz containing both Ix and Iy *)
    destruct (dir_upper _ _ hdir
        (exist _ Ix (hF Ix HIx))
        (exist _ Iy (hF Iy HIy))
        HIx HIy) as [[Iz hIz] [HIzF [HxzI HyzI]]].
    exists Iz. split. exact HIzF.
    apply (ideal_join _ _ (hF Iz HIzF)).
    + apply HxzI. exact Hxx.
    + apply HyzI. exact Hyy.
  - (* downward-closed *)
    intros x y [Ix [HIx Hxx]] Hle.
    exists Ix. split. exact HIx.
    apply (ideal_down _ _ (hF Ix HIx)) with x; assumption.
Qed.

(** *** The ideal completion is a complete lattice *)

(** The ideal generated by a set A is the smallest ideal containing A. *)
Definition ideal_generated (J : JoinSemilattice) (A : J.(carrier) -> Prop) :
    J.(carrier) -> Prop :=
  fun x => exists (xs : list J.(carrier)),
    (forall y, List.In y xs -> A y) /\
    x ≤[J] finite_join J xs.

Lemma ideal_generated_is_ideal (J : JoinSemilattice) (A : J.(carrier) -> Prop) :
    IsIdeal J (ideal_generated J A).
Proof.
  (* Helper: finite_join xs ≤ finite_join (xs ++ ys) *)
  assert (fj_app_left : forall xs ys,
      finite_join J xs ≤[J] finite_join J (xs ++ ys)).
  { intros xs. induction xs as [|x xs' IH]; intro ys.
    - cbn. apply J.(jsl_bot_le).
    - cbn. apply J.(jsl_join_lub).
      + apply J.(jsl_join_ub1).
      + apply J.(le_trans) with (finite_join J (xs' ++ ys)).
        * apply IH.
        * apply J.(jsl_join_ub2). }
  (* Helper: finite_join ys ≤ finite_join (xs ++ ys) *)
  assert (fj_app_right : forall xs ys,
      finite_join J ys ≤[J] finite_join J (xs ++ ys)).
  { intros xs. induction xs as [|x xs' IH]; intro ys.
    - cbn. apply J.(le_refl).
    - cbn. apply J.(le_trans) with (finite_join J (xs' ++ ys)).
      + apply IH.
      + apply J.(jsl_join_ub2). }
  constructor.
  - (* ⊥ ∈ ideal_generated: take xs = nil *)
    exists nil. split.
    + intros y Hy. exact (False_rect _ (List.in_nil Hy)).
    + cbn. apply J.(le_refl).
  - (* closed under join *)
    intros x y [xs [Hxs Hx]] [ys [Hys Hy]].
    exists (xs ++ ys). split.
    + intros z Hz. apply List.in_app_or in Hz. destruct Hz as [H | H].
      * apply Hxs. exact H.
      * apply Hys. exact H.
    + apply J.(jsl_join_lub).
      * apply J.(le_trans) with (finite_join J xs).
        -- exact Hx.
        -- apply fj_app_left.
      * apply J.(le_trans) with (finite_join J ys).
        -- exact Hy.
        -- apply fj_app_right.
  - (* downward-closed *)
    intros x y [xs [Hxs Hx]] Hle.
    exists xs. split.
    + exact Hxs.
    + apply J.(le_trans) with x; assumption.
Qed.

(** Helper: an ideal is closed under finite_join *)
Lemma ideal_finite_join_closed_pre (J : JoinSemilattice)
    (I : J.(carrier) -> Prop) (hI : IsIdeal J I)
    (xs : list J.(carrier)) :
    (forall y, List.In y xs -> I y) -> I (finite_join J xs).
Proof.
  induction xs as [| x xs' IH]; intro Hin.
  - simpl. exact (ideal_bot J I hI).
  - simpl. apply (ideal_join J I hI).
    + apply Hin. left. reflexivity.
    + apply IH. intros y Hy. apply Hin. right. exact Hy.
Qed.

(** Sup of a family S of ideals: ideal generated by the union. *)

Theorem ideal_compl_sup_ideal : forall (J : JoinSemilattice)
    (S : {I : J.(carrier) -> Prop | IsIdeal J I} -> Prop),
    IsIdeal J (ideal_generated J (fun x => exists I : {I : _ | IsIdeal J I}, S I /\ proj1_sig I x)).
Proof.
  intros J S. exact (ideal_generated_is_ideal J _).
Qed.

Theorem ideal_compl_sup_ub : forall (J : JoinSemilattice)
    (S : {I : J.(carrier) -> Prop | IsIdeal J I} -> Prop)
    (I : {I : J.(carrier) -> Prop | IsIdeal J I}),
    S I ->
    forall x, proj1_sig I x ->
    proj1_sig (exist _ (ideal_generated J (fun x => exists I' : {I : _ | IsIdeal J I}, S I' /\ proj1_sig I' x))
                       (ideal_compl_sup_ideal J S)) x.
Proof.
  intros J S I HI x Hx.
  cbn. unfold ideal_generated.
  exists (x :: nil). split.
  - intros y Hy. simpl in Hy. destruct Hy as [<- | []].
    exists I. split. exact HI. exact Hx.
  - simpl. apply J.(jsl_join_ub1).
Qed.

Theorem ideal_compl_sup_lub : forall (J : JoinSemilattice)
    (S : {I : J.(carrier) -> Prop | IsIdeal J I} -> Prop)
    (z : {I : J.(carrier) -> Prop | IsIdeal J I}),
    (forall I, S I -> forall x, proj1_sig I x -> proj1_sig z x) ->
    forall w,
    proj1_sig (exist _ (ideal_generated J (fun x => exists I' : {I : _ | IsIdeal J I}, S I' /\ proj1_sig I' x))
                       (ideal_compl_sup_ideal J S)) w ->
    proj1_sig z w.
Proof.
  intros J S z Hz w Hw.
  cbn in Hw. unfold ideal_generated in Hw.
  destruct Hw as [xs [Hxs Hwle]].
  apply (ideal_down J _ (proj2_sig z) (finite_join J xs) w).
  - apply ideal_finite_join_closed_pre.
    + exact (proj2_sig z).
    + intros xi Hxi.
      destruct (Hxs xi Hxi) as [I' [HI' HIxi]].
      exact (Hz I' HI' xi HIxi).
  - exact Hwle.
Qed.

Definition IdealCompl_CompleteLattice (J : JoinSemilattice) : CompleteLattice := {|
  cl_poset := IdealCompletion J;
  cl_sup   := fun S =>
    exist _ (ideal_generated J (fun x => exists I : {I : _ | IsIdeal J I}, S I /\ proj1_sig I x))
           (ideal_compl_sup_ideal J S);
  cl_sup_ub := fun S I HI x Hx => ideal_compl_sup_ub J S I HI x Hx;
  cl_sup_lub := fun S z Hz x Hx => ideal_compl_sup_lub J S z Hz x Hx;
|}.

(** *** Proposition 1.5.18: Compact elements of IdCompl J are principal ideals *)

(** Helper: in a directed family of ideals, any finite list of elements
    is covered by a single ideal in the family. *)
Lemma directed_covers_finite_list (J : JoinSemilattice)
    (D : {I : J.(carrier) -> Prop | IsIdeal J I} -> Prop)
    (hD : IsDirected (IdealCompletion J) D)
    (xs : list J.(carrier)) :
    (forall y, List.In y xs -> exists I, D I /\ proj1_sig I y) ->
    exists Iz, D Iz /\ forall y, List.In y xs -> proj1_sig Iz y.
Proof.
  induction xs as [| x xs' IH]; intro Hin.
  - destruct (dir_inh _ _ hD) as [I HI].
    exists I. split. exact HI. intros y Hy. exact (False_rect _ (List.in_nil Hy)).
  - destruct (Hin x (or_introl eq_refl)) as [Ix [HIx HxIx]].
    destruct (IH (fun y Hy => Hin y (or_intror Hy))) as [Iz [HIz Hiz]].
    destruct (dir_upper _ _ hD Ix Iz HIx HIz) as [Iw [HIw [HxIxw HIzw]]].
    exists Iw. split. exact HIw.
    intros y Hy. simpl in Hy. destruct Hy as [<- | Hy].
    + apply HxIxw. exact HxIx.
    + apply HIzw. apply Hiz. exact Hy.
Qed.

(** A principal ideal x↓ is compact in IdCompl J. *)
Lemma principal_ideal_compact (J : JoinSemilattice) (x : J.(carrier)) :
    IsCompact (cl_to_dcpo (IdealCompl_CompleteLattice J)) (x ↓i{J}).
Proof.
  intros D hD Hle.
  assert (Hx : proj1_sig (cl_sup (IdealCompl_CompleteLattice J) D) x).
  { apply Hle. apply J.(le_refl). }
  cbn in Hx. unfold ideal_generated in Hx.
  destruct Hx as [xs [Hxs Hxle]].
  destruct (directed_covers_finite_list J D hD xs Hxs) as [Iz [HIz Hiz]].
  exists Iz. split.
  - exact HIz.
  - intros z Hz.
    apply (ideal_down J _ (proj2_sig Iz) (finite_join J xs) z).
    + exact (ideal_finite_join_closed_pre J _ (proj2_sig Iz) xs Hiz).
    + apply J.(le_trans) with x; assumption.
Qed.

(** Every compact ideal is a principal ideal of a finite join. *)
Lemma compact_ideal_is_principal (J : JoinSemilattice)
    (I : { I : J.(carrier) -> Prop | IsIdeal J I })
    (hI : IsCompact (cl_to_dcpo (IdealCompl_CompleteLattice J)) I) :
    exists x : J.(carrier), proj1_sig I = proj1_sig (x ↓i{J}).
Proof.
  (* Family of principal sub-ideals of I *)
  set (D := fun Iz : { I' : J.(carrier) -> Prop | IsIdeal J I' } =>
        exists x, proj1_sig I x /\ Iz = (x ↓i{J})).
  (* D is directed *)
  assert (hD : IsDirected (IdealCompletion J) D).
  { constructor.
    - (* Non-empty: ⊥↓ ∈ D *)
      exists (⊥{J} ↓i{J}).
      exists ⊥{J}. split.
      + exact (ideal_bot J _ (proj2_sig I)).
      + reflexivity.
    - (* Upper bound *)
      intros Ix Iy [x [Hx HxeqIx]] [y [Hy HyeqIy]].
      subst Ix. subst Iy.
      exists ((x ∨{J} y) ↓i{J}). split.
      + exists (x ∨{J} y). split.
        * exact (ideal_join J _ (proj2_sig I) x y Hx Hy).
        * reflexivity.
      + split.
        * intros z Hz. cbn in *. apply J.(le_trans) with x.
          -- exact Hz.
          -- apply J.(jsl_join_ub1).
        * intros z Hz. cbn in *. apply J.(le_trans) with y.
          -- exact Hz.
          -- apply J.(jsl_join_ub2).
  }
  (* I ≤ ⊔D *)
  assert (hIle : I ≤[IdealCompl_CompleteLattice J] ⊔{IdealCompl_CompleteLattice J} D).
  { intros z Hz.
    cbn. unfold ideal_generated.
    exists (z :: nil). split.
    - intros w Hw. simpl in Hw. destruct Hw as [<- | []].
      exists (z ↓i{J}). split.
      + exists z. split. exact Hz. reflexivity.
      + cbn. apply J.(le_refl).
    - simpl. apply J.(jsl_join_ub1).
  }
  (* Apply compactness *)
  destruct (hI D hD hIle) as [Iz [HDIz HIIz]].
  destruct HDIz as [x [Hx ->]].
  (* I = x↓ *)
  exists x.
  apply functional_extensionality. intro z.
  apply propositional_extensionality. split.
  - intro Hz. cbn. exact (HIIz z Hz).
  - intro Hz. cbn in Hz.
    exact (ideal_down J _ (proj2_sig I) x z Hx Hz).
Qed.

(** *** Proposition 1.5.18 statement *)

Theorem ideal_completion_algebraic (J : JoinSemilattice) :
    IsAlgebraic (cl_to_dcpo (IdealCompl_CompleteLattice J)).
Proof.
  intro I. split.
  - (* Directedness of compact elements below I *)
    constructor.
    + (* Non-empty: ⊥↓ is compact and ≤ I *)
      exists (⊥{J} ↓i{J}). split.
      * exact (principal_ideal_compact J ⊥{J}).
      * intros z Hz. cbn in Hz.
        exact (ideal_down J _ (proj2_sig I) ⊥{J} z (ideal_bot J _ (proj2_sig I)) Hz).
    + (* Upper bound: compact elements e1 ≤ I and e2 ≤ I are covered by (x∨y)↓ *)
      intros e1 e2 [he1comp he1le] [he2comp he2le].
      destruct (compact_ideal_is_principal J e1 he1comp) as [x Hx].
      destruct (compact_ideal_is_principal J e2 he2comp) as [y Hy].
      assert (HxI : proj1_sig I x).
      { apply he1le. rewrite Hx. cbn. apply J.(le_refl). }
      assert (HyI : proj1_sig I y).
      { apply he2le. rewrite Hy. cbn. apply J.(le_refl). }
      exists ((x ∨{J} y) ↓i{J}). split.
      * split.
        -- exact (principal_ideal_compact J (x ∨{J} y)).
        -- intros z Hz. cbn in Hz.
           exact (ideal_down J _ (proj2_sig I) (x ∨{J} y) z
                    (ideal_join J _ (proj2_sig I) x y HxI HyI) Hz).
      * split.
        -- intros z Hz. cbn. rewrite Hx in Hz. cbn in Hz.
           apply J.(le_trans) with x. exact Hz. apply J.(jsl_join_ub1).
        -- intros z Hz. cbn. rewrite Hy in Hz. cbn in Hz.
           apply J.(le_trans) with y. exact Hz. apply J.(jsl_join_ub2).
  - (* I is the sup of compact elements below it *)
    intros ub Hub z Hz.
    assert (hz_compact : IsCompact (cl_to_dcpo (IdealCompl_CompleteLattice J)) (z ↓i{J})).
    { exact (principal_ideal_compact J z). }
    assert (hz_down_le_I : z ↓i{J} ≤[IdealCompl_CompleteLattice J] I).
    { intros w Hw. cbn in Hw.
      exact (ideal_down J _ (proj2_sig I) z w Hz Hw). }
    assert (hz_down_le_ub : z ↓i{J} ≤[IdealCompl_CompleteLattice J] ub).
    { exact (Hub (z ↓i{J}) hz_compact hz_down_le_I). }
    apply hz_down_le_ub. cbn. apply J.(le_refl).
Qed.

(** ** Embedding of J into its ideal completion *)

Definition jsl_to_ideal (J : JoinSemilattice) : J.(carrier) -> IdealCompletion J :=
  fun x => x ↓i{J}.

Lemma jsl_to_ideal_mono (J : JoinSemilattice) (x y : J.(carrier)) :
    x ≤[J] y -> jsl_to_ideal J x ≤[IdCompl J] jsl_to_ideal J y.
Proof.
  intros Hxy z Hz. cbn in *. apply J.(le_trans) with x; assumption.
Qed.

(** Helper: if each element of xs is bounded by x or y, then finite_join xs ≤ x∨y *)
Lemma finite_join_le_join (J : JoinSemilattice) (x y : J.(carrier)) (xs : list J.(carrier)) :
    (forall w, List.In w xs -> w ≤[J] x \/ w ≤[J] y) ->
    finite_join J xs ≤[J] (x ∨{J} y).
Proof.
  induction xs as [| xi xs' IH]; intro Hin.
  - simpl. apply J.(jsl_bot_le).
  - simpl. apply J.(jsl_join_lub).
    + destruct (Hin xi (or_introl eq_refl)) as [H | H].
      * apply J.(le_trans) with x. exact H. apply J.(jsl_join_ub1).
      * apply J.(le_trans) with y. exact H. apply J.(jsl_join_ub2).
    + apply IH. intros w Hw. apply Hin. right. exact Hw.
Qed.

Lemma jsl_to_ideal_preserves_join (J : JoinSemilattice) (x y : J.(carrier)) :
    jsl_to_ideal J (x ∨{J} y) =
    cl_join (IdealCompl_CompleteLattice J) (jsl_to_ideal J x) (jsl_to_ideal J y).
Proof.
  unfold cl_join, jsl_to_ideal.
  apply (le_antisym (IdealCompletion J)).
  - (* (x∨y)↓ ≤ sup{x↓, y↓} *)
    intros z Hz. cbn. unfold ideal_generated.
    exists (x :: y :: nil). split.
    + intros w Hw. simpl in Hw. destruct Hw as [<- | [<- | []]].
      * exists (x ↓i{J}). split. left. reflexivity. simpl. apply J.(le_refl).
      * exists (y ↓i{J}). split. right. reflexivity. simpl. apply J.(le_refl).
    + simpl. apply J.(le_trans) with (x ∨{J} y).
      * exact Hz.
      * apply J.(jsl_join_lub).
        -- apply J.(jsl_join_ub1).
        -- apply J.(le_trans) with (y ∨{J} ⊥{J}).
           ++ apply J.(jsl_join_ub1).
           ++ apply J.(jsl_join_ub2).
  - (* sup{x↓, y↓} ≤ (x∨y)↓ *)
    intros z Hz. cbn. cbn in Hz. unfold ideal_generated in Hz.
    destruct Hz as [xs [Hxs Hzle]].
    apply J.(le_trans) with (finite_join J xs).
    + exact Hzle.
    + apply finite_join_le_join.
      intros w Hw.
      destruct (Hxs w Hw) as [I [HI HIw]].
      destruct HI as [-> | ->]; simpl in HIw.
      * left. exact HIw.
      * right. exact HIw.
Qed.
